module Ploeh.Numsense.DanishExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                              "nul",          0)>]
[<InlineData(                                             " nul",          0)>]
[<InlineData(                                             "nul ",          0)>]
[<InlineData(                                          "  nul  ",          0)>]
[<InlineData(                                              "Nul",          0)>]
[<InlineData(                                              "NUL",          0)>]
[<InlineData(                                            "nUl\t",          0)>]
[<InlineData(                                               "et",          1)>]
[<InlineData(                                               "en",          1)>]
[<InlineData(                                               "ET",          1)>]
[<InlineData(                                               "to",          2)>]
[<InlineData(                                              " to",          2)>]
[<InlineData(                                              "tre",          3)>]
[<InlineData(                                            "tre  ",          3)>]
[<InlineData(                                             "fire",          4)>]
[<InlineData(                                          "  fire ",          4)>]
[<InlineData(                                              "fem",          5)>]
[<InlineData(                                              "FeM",          5)>]
[<InlineData(                                             "seks",          6)>]
[<InlineData(                                         "  SEKS  ",          6)>]
[<InlineData(                                              "syv",          7)>]
[<InlineData(                                          "    sYv",          7)>]
[<InlineData(                                             "otte",          8)>]
[<InlineData(                                             "oTTE",          8)>]
[<InlineData(                                               "ni",          9)>]
[<InlineData(                                             "Ni  ",          9)>]
[<InlineData(                                               "ti",         10)>]
[<InlineData(                                           "elleve",         11)>]
[<InlineData(                                             "tolv",         12)>]
[<InlineData(                                          "tretten",         13)>]
[<InlineData(                                          "fjorten",         14)>]
[<InlineData(                                           "femten",         15)>]
[<InlineData(                                          "seksten",         16)>]
[<InlineData(                                           "sytten",         17)>]
[<InlineData(                                            "atten",         18)>]
[<InlineData(                                           "nitten",         19)>]
[<InlineData(                                             "tyve",         20)>]
[<InlineData(                                         "enogtyve",         21)>]
[<InlineData(                                          "tredive",         30)>]
[<InlineData(                                    "fireogtredive",         34)>]
[<InlineData(                                            "fyrre",         40)>]
[<InlineData(                                      "fireogfyrre",         44)>]
[<InlineData(                                        "halvtreds",         50)>]
[<InlineData(                                   "syvoghalvtreds",         57)>]
[<InlineData(                                             "tres",         60)>]
[<InlineData(                                        "femogtres",         65)>]
[<InlineData(                                       "halvfjerds",         70)>]
[<InlineData(                                   "nioghalvfjerds",         79)>]
[<InlineData(                                             "firs",         80)>]
[<InlineData(                                       "seksogfirs",         86)>]
[<InlineData(                                         "halvfems",         90)>]
[<InlineData(                                    "treoghalvfems",         93)>]
[<InlineData(                                         "hundrede",        100)>]
[<InlineData(                                       "ethundrede",        100)>]
[<InlineData(                                       "hundredeet",        101)>]
[<InlineData(                                     "hundredeoget",        101)>]
[<InlineData(                                   "hundrede-og-et",        101)>]
[<InlineData(                                     "ethundredeet",        101)>]
[<InlineData(                                   "ethundredeoget",        101)>]
[<InlineData(                                "et-hundrede-og-et",        101)>]
[<InlineData(                                       "tohundrede",        200)>]
[<InlineData(                           "tohundredesyvogtredive",        237)>]
[<InlineData(                       "trehundredefemoghalvfjerds",        375)>]
[<InlineData(                             "firehundredehalvfems",        490)>]
[<InlineData(                             "femhundredetreogtres",        563)>]
[<InlineData(                                "sekshundredeatten",        618)>]
[<InlineData(                       "syvhundredesyvoghalvfjerds",        777)>]
[<InlineData(                                "ottehundredeogfem",        805)>]
[<InlineData(                               "ottehundredeogseks",        806)>]
[<InlineData(                             "otte-hundrede-og-syv",        807)>]
[<InlineData(                          "nihundredenioghalvtreds",        959)>]
let ``tryOfDanish returns correct result`` (danish : string, expected : int) =
    let actual = Numeral.tryOfDanish danish
    Some expected =! actual

