module Ploeh.Numsense.DutchExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                                           "nul",          0)>]
[<InlineData(                                                          " nul",          0)>]
[<InlineData(                                                          "nul ",          0)>]
[<InlineData(                                                       "  nul  ",          0)>]
[<InlineData(                                                           "Nul",          0)>]
[<InlineData(                                                           "NUL",          0)>]
[<InlineData(                                                        " nUl\t",          0)>]
[<InlineData(                                                           "een",          1)>]
[<InlineData(                                                           "ééN",          1)>]
[<InlineData(                                                           "EEN",          1)>]
[<InlineData(                                                          "twee",          2)>]
[<InlineData(                                                         " twee",          2)>]
[<InlineData(                                                          "drie",          3)>]
[<InlineData(                                                        "drie  ",          3)>]
[<InlineData(                                                          "vier",          4)>]
[<InlineData(                                                       "  vier ",          4)>]
[<InlineData(                                                          "vijf",          5)>]
[<InlineData(                                                          "VijF",          5)>]
[<InlineData(                                                           "zes",          6)>]
[<InlineData(                                                       "  ZES  ",          6)>]
[<InlineData(                                                         "zeven",          7)>]
[<InlineData(                                                     "    zeVen",          7)>]
[<InlineData(                                                          "acht",          8)>]
[<InlineData(                                                          "acHT",          8)>]
[<InlineData(                                                         "negen",          9)>]
[<InlineData(                                                       "NeGeN  ",          9)>]
[<InlineData(                                                          "tien",         10)>]
[<InlineData(                                                           "elf",         11)>]
[<InlineData(                                                        "twaalf",         12)>]
[<InlineData(                                                       "dertien",         13)>]
[<InlineData(                                                      "veertien",         14)>]
[<InlineData(                                                      "vijftien",         15)>]
[<InlineData(                                                       "zestien",         16)>]
[<InlineData(                                                     "zeventien",         17)>]
[<InlineData(                                                      "achttien",         18)>]
[<InlineData(                                                     "negentien",         19)>]
[<InlineData(                                                       "twintig",         20)>]
[<InlineData(                                                  "eenentwintig",         21)>]
[<InlineData(                                                  "éénentwintig",         21)>]
[<InlineData(                                                        "dertig",         30)>]
[<InlineData(                                                  "vierendertig",         34)>]
[<InlineData(                                                  "achtendertig",         38)>]
[<InlineData(                                                       "veertig",         40)>]
[<InlineData(                                                  "eenenveertig",         41)>]
[<InlineData(                                                  "éénenveertig",         41)>]
[<InlineData(                                                 "vierenveertig",         44)>]
[<InlineData(                                                       "vijftig",         50)>]
[<InlineData(                                                "zevenenvijftig",         57)>]
[<InlineData(                                                        "zestig",         60)>]
[<InlineData(                                                  "vijfenzestig",         65)>]
[<InlineData(                                                      "zeventig",         70)>]
[<InlineData(                                               "zevenenzeventig",         77)>]
[<InlineData(                                               "negenenzeventig",         79)>]
[<InlineData(                                                       "tachtig",         80)>]
[<InlineData(                                                  "zesentachtig",         86)>]
[<InlineData(                                                      "negentig",         90)>]
[<InlineData(                                                "drieënnegentig",         93)>]
[<InlineData(                                                       "honderd",        100)>]
[<InlineData(                                                    "honderdeen",        101)>]
[<InlineData(                                                    "honderdéén",        101)>]
[<InlineData(                                                "honderd en een",        101)>]
[<InlineData(                                                "honderd en één",        101)>]
[<InlineData(                                                   "tweehonderd",        200)>]
[<InlineData(                                      "tweehonderdzevenendertig",        237)>]
[<InlineData(                                      "driehonderdvijfenzeventig",       375)>]
[<InlineData(                                           "vierhonderdnegentig",        490)>]
[<InlineData(                                      "vijfhonderddrieënzestig",         563)>]
[<InlineData(                                            "zeshonderdachttien",        618)>]
[<InlineData(                                   "zevenhonderdzevenenzeventig",        777)>]
[<InlineData(                                               "achthonderdvijf",        805)>]
[<InlineData(                                            "achthonderd en zes",        806)>]
[<InlineData(                                            "achthonderdenzeven",        807)>]
[<InlineData(                                          "achthonderd en zeven",        807)>]
[<InlineData(                                    "negenhonderdnegenenvijftig",        959)>]
[<InlineData(                                                       "duizend",       1000)>]
[<InlineData(                                                   "duizend een",       1001)>]
[<InlineData(                                                   "duizend één",       1001)>]
[<InlineData(                                                "duizend en een",       1001)>]
[<InlineData(                                                "duizend en één",       1001)>]
[<InlineData(                                          "duizend vierenzestig",       1064)>]
[<InlineData(                                                 "twaalfhonderd",       1200)>]
[<InlineData(                                 "zestienhonderdzevenenzeventig",       1677)>]
[<InlineData(                                                   "tweeduizend",       2000)>]
[<InlineData(                          "achtduizend zevenhonderdeenentwintig",       8721)>]
[<InlineData(                            "negenduizend honderddrieëntwintig",        9123)>]
[<InlineData(                                                   "tienduizend",      10000)>]
[<InlineData(                                        "tienduizend honderdeen",      10101)>]
[<InlineData(                                        "tienduizend honderdéén",      10101)>]
[<InlineData(                                    "tienduizend honderd en een",      10101)>]
[<InlineData(                                    "tienduizend honderd en één",      10101)>]
[<InlineData(                                       "tienduizend honderdtwee",      10102)>]
[<InlineData(                                   "tienduizend honderd en twee",      10102)>]
[<InlineData(                  "drieëntwintigduizend vijfhonderdvierenzestig",      23564)>]
[<InlineData(                                           "tachtigduizend tien",      80010)>]
[<InlineData(                                        "tachtigduizend en tien",      80010)>]
[<InlineData(                                                "honderdduizend",     100000)>]
[<InlineData(                                            "honderdduizend een",     100001)>]
[<InlineData(                                         "honderdduizend en een",     100001)>]
[<InlineData(                                         "honderdduizend en één",     100001)>]
[<InlineData(         "driehonderdnegentienduizend driehonderdnegenenveertig",     319349)>]
[<InlineData(                                                       "miljoen",    1000000)>]
[<InlineData(                                                   "een miljoen",    1000000)>]
[<InlineData(                                                   "één miljoen",    1000000)>]
[<InlineData(                                               "een miljoen een",    1000001)>]
[<InlineData(                                            "een miljoen en een",    1000001)>]
[<InlineData(                                               "één miljoen een",    1000001)>]
[<InlineData(                                            "één miljoen en één",    1000001)>]
[<InlineData(                                             "twee miljoen tien",    2000010)>]
[<InlineData(                                          "twee miljoen en tien",    2000010)>]
[<InlineData(                                     "zes miljoen dertigduizend",    6030000)>]
[<InlineData(       "negen miljoen tweehonderdeneenduizend zeshonderdtachtig",    9201680)>]
[<InlineData(                                                  "tien miljoen",   10000000)>]
[<InlineData(                                            "tien miljoen negen",   10000009)>]
[<InlineData(                                         "tien miljoen en negen",   10000009)>]
[<InlineData(                                          "eenentwintig miljoen",   21000000)>]
[<InlineData(    "zevenenveertig miljoen zeshonderdeenenzestigduizend zestig",   47661060)>]
[<InlineData( "zevenenveertig miljoen zeshonderdeenenzestigduizend en zestig",   47661060)>]
[<InlineData(                                               "honderd miljoen",  100000000)>]
[<InlineData(                                       "tweehonderdvijf miljoen",  205000000)>]
[<InlineData(                                      "driehonderdzeven miljoen",  307000000)>]
[<InlineData(                                  "driehonderd en zeven miljoen",  307000000)>]
[<InlineData(       "vierhonderdeneenzestig miljoen zestigduizend zeshonderd",  461060600)>]
[<InlineData(    "vierhonderdeneenzestig miljoen zestigduizend en zeshonderd",  461060600)>]
[<InlineData(                                                       "miljard", 1000000000)>]
[<InlineData(                                                   "een miljard", 1000000000)>]
[<InlineData(                                                   "één miljard", 1000000000)>]
[<InlineData(                                                  "twee miljard", 2000000000)>]
[<InlineData(  "twee miljard negenenveertig miljoen zeshonderdvijftigduizend", 2049650000)>]
[<InlineData(
    "twee miljard honderdzevenenveertig miljoen vierhonderddrieëntachtigduizend zeshonderdzevenenveertig",
    System.Int32.MaxValue)>]
let ``tryOfDutch returns correct result`` (dutch, expected) =
    let actual = Numeral.tryParseDutch dutch
    Some expected =! actual

[<Theory>]
[<InlineData(         0, "nul")>]
[<InlineData(         1, "een")>]
[<InlineData(         2, "twee")>]
[<InlineData(         3, "drie")>]
[<InlineData(         4, "vier")>]
[<InlineData(         5, "vijf")>]
[<InlineData(         6, "zes")>]
[<InlineData(         7, "zeven")>]
[<InlineData(         8, "acht")>]
[<InlineData(         9, "negen")>]
[<InlineData(        10, "tien")>]
[<InlineData(        11, "elf")>]
[<InlineData(        12, "twaalf")>]
[<InlineData(        13, "dertien")>]
[<InlineData(        14, "veertien")>]
[<InlineData(        15, "vijftien")>]
[<InlineData(        16, "zestien")>]
[<InlineData(        17, "zeventien")>]
[<InlineData(        18, "achttien")>]
[<InlineData(        19, "negentien")>]
[<InlineData(        20, "twintig")>]
[<InlineData(        21, "eenentwintig")>]
[<InlineData(        30, "dertig")>]
[<InlineData(        34, "vierendertig")>]
[<InlineData(        40, "veertig")>]
[<InlineData(        42, "tweeënveertig")>]
[<InlineData(        50, "vijftig")>]
[<InlineData(        58, "achtenvijftig")>]
[<InlineData(        60, "zestig")>]
[<InlineData(        65, "vijfenzestig")>]
[<InlineData(        70, "zeventig")>]
[<InlineData(        79, "negenenzeventig")>]
[<InlineData(        80, "tachtig")>]
[<InlineData(        86, "zesentachtig")>]
[<InlineData(        90, "negentig")>]
[<InlineData(        93, "drieënnegentig")>]
[<InlineData(       100, "honderd")>]
[<InlineData(       101, "honderdeen")>]
[<InlineData(       110, "honderdtien")>]
[<InlineData(       114, "honderdveertien")>]
[<InlineData(       135, "honderdvijfendertig")>]
[<InlineData(       200, "tweehonderd")>]
[<InlineData(       282, "tweehonderdtweeëntachtig")>]
[<InlineData(       331, "driehonderdeenendertig")>]
[<InlineData(       407, "vierhonderdzeven")>]
[<InlineData(       520, "vijfhonderdtwintig")>]
[<InlineData(       666, "zeshonderdzesenzestig")>]
[<InlineData(       798, "zevenhonderdachtennegentig")>]
[<InlineData(       857, "achthonderdzevenenvijftig")>]
[<InlineData(       999, "negenhonderdnegenennegentig")>]
[<InlineData(      1000, "duizend")>]
[<InlineData(      1001, "duizend een")>]
[<InlineData(      1010, "duizend tien")>]
[<InlineData(      1066, "duizend zesenzestig")>]
[<InlineData(      1337, "duizend driehonderdzevenendertig")>]
[<InlineData(      1984, "duizend negenhonderdvierentachtig")>]
[<InlineData(      2015, "tweeduizend vijftien")>]
[<InlineData(      3000, "drieduizend")>]
[<InlineData(      3297, "drieduizend tweehonderdzevenennegentig")>]
[<InlineData(      4080, "vierduizend tachtig")>]
[<InlineData(      5011, "vijfduizend elf")>]
[<InlineData(      6025, "zesduizend vijfentwintig")>]
[<InlineData(      7441, "zevenduizend vierhonderdeenenveertig")>]
[<InlineData(      8513, "achtduizend vijfhonderddertien")>]
[<InlineData(      9000, "negenduizend")>]
[<InlineData(     10000, "tienduizend")>]
[<InlineData(     12001, "twaalfduizend een")>]
[<InlineData(     23456, "drieëntwintigduizend vierhonderdzesenvijftig")>]
[<InlineData(     32109, "tweeëndertigduizend honderdnegen")>]
[<InlineData(     40404, "veertigduizend vierhonderdvier")>]
[<InlineData(     56789, "zesenvijftigduizend zevenhonderdnegenentachtig")>]
[<InlineData(     60015, "zestigduizend vijftien")>]
[<InlineData(     71003, "eenenzeventigduizend drie")>]
[<InlineData(     80522, "tachtigduizend vijfhonderdtweeëntwintig")>]
[<InlineData(     98765, "achtennegentigduizend zevenhonderdvijfenzestig")>]
[<InlineData(    100000, "honderdduizend")>]
[<InlineData(    100001, "honderdduizend een")>]
[<InlineData(    100010, "honderdduizend tien")>]
[<InlineData(    101010, "honderdeenduizend tien")>]
[<InlineData(    200000, "tweehonderdduizend")>]
[<InlineData(    321000, "driehonderdeenentwintigduizend")>]
[<InlineData(    411416, "vierhonderdelfduizend vierhonderdzestien")>]
[<InlineData(    530121, "vijfhonderddertigduizend honderdeenentwintig")>]
[<InlineData(    600000, "zeshonderdduizend")>]
[<InlineData(    788000, "zevenhonderdachtentachtigduizend")>]
[<InlineData(    876540, "achthonderdzesenzeventigduizend vijfhonderdveertig")>]
[<InlineData(    908077, "negenhonderdachtduizend zevenenzeventig")>]
[<InlineData(   1000000, "een miljoen")>]
[<InlineData(   2000002, "twee miljoen twee")>]
[<InlineData(   3040506, "drie miljoen veertigduizend vijfhonderdzes")>]
[<InlineData(   4321000, "vier miljoen driehonderdeenentwintigduizend")>]
[<InlineData(   5004621, "vijf miljoen vierduizend zeshonderdeenentwintig")>]
[<InlineData(   6982001, "zes miljoen negenhonderdtweeëntachtigduizend een")>]
[<InlineData(   7000000, "zeven miljoen")>]
[<InlineData(   8000220, "acht miljoen tweehonderdtwintig")>]
[<InlineData(   9099000, "negen miljoen negenennegentigduizend")>]
[<InlineData(  10000000, "tien miljoen")>]
[<InlineData(  24000000, "vierentwintig miljoen")>]
[<InlineData(  39020011, "negenendertig miljoen twintigduizend elf")>]
[<InlineData(  40606100, "veertig miljoen zeshonderdzesduizend honderd")>]
[<InlineData(  53000000, "drieënvijftig miljoen")>]
[<InlineData(  64000098, "vierenzestig miljoen achtennegentig")>]
[<InlineData(  70003190, "zeventig miljoen drieduizend honderdnegentig")>]
[<InlineData(  80000000, "tachtig miljoen")>]
[<InlineData(  99000099, "negenennegentig miljoen negenennegentig")>]
[<InlineData( 100000000, "honderd miljoen")>]
[<InlineData( 209000000, "tweehonderdnegen miljoen")>]
[<InlineData( 398000000, "driehonderdachtennegentig miljoen")>]
[<InlineData( 439011000, "vierhonderdnegenendertig miljoen elfduizend")>]
[<InlineData( 560400000, "vijfhonderdzestig miljoen vierhonderdduizend")>]
[<InlineData( 600010900, "zeshonderd miljoen tienduizend negenhonderd")>]
[<InlineData( 700000000, "zevenhonderd miljoen")>]
[<InlineData( 800116000, "achthonderd miljoen honderdzestienduizend")>]
[<InlineData( 900800007, "negenhonderd miljoen achthonderdduizend zeven")>]
[<InlineData(1000000000, "een miljard")>]
[<InlineData(2121000000, "twee miljard honderdeenentwintig miljoen")>]
[<InlineData(
    System.Int32.MaxValue,
    "twee miljard honderdzevenenveertig miljoen vierhonderddrieëntachtigduizend zeshonderdzevenenveertig")>]
let ``toDutch returns correct result`` (i, expected) =
    let actual = Numeral.toDutch i
    expected =! actual