module Ploeh.Numsense.EnglishExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(      "zero",  0)>]
[<InlineData(     " zero",  0)>]
[<InlineData(     "zero ",  0)>]
[<InlineData(  "  zero  ",  0)>]
[<InlineData(      "Zero",  0)>]
[<InlineData(      "ZERO",  0)>]
[<InlineData(   " zERo\t",  0)>]
[<InlineData(       "one",  1)>]
[<InlineData(       "ONE",  1)>]
[<InlineData(       "two",  2)>]
[<InlineData(      " two",  2)>]
[<InlineData(     "three",  3)>]
[<InlineData(   "three  ",  3)>]
[<InlineData(      "four",  4)>]
[<InlineData(   "  four ",  4)>]
[<InlineData(      "five",  5)>]
[<InlineData(      "FivE",  5)>]
[<InlineData(       "six",  6)>]
[<InlineData(   "  SIX  ",  6)>]
[<InlineData(     "seven",  7)>]
[<InlineData( "    seVen",  7)>]
[<InlineData(     "eight",  8)>]
[<InlineData(     "eIGHT",  8)>]
[<InlineData(      "nine",  9)>]
[<InlineData(    "NiNe  ",  9)>]
[<InlineData(       "ten", 10)>]
[<InlineData(    "eleven", 11)>]
[<InlineData(    "twelve", 12)>]
[<InlineData(  "thirteen", 13)>]
[<InlineData(  "fourteen", 14)>]
[<InlineData(   "fifteen", 15)>]
[<InlineData(   "sixteen", 16)>]
[<InlineData( "seventeen", 17)>]
[<InlineData(  "eighteen", 18)>]
[<InlineData(  "nineteen", 19)>]
[<InlineData(    "twenty", 20)>]
[<InlineData( "twentyone", 21)>]
[<InlineData(    "thirty", 30)>]
[<InlineData("thirtyfour", 34)>]
[<InlineData(     "forty", 40)>]
[<InlineData( "fortyfour", 44)>]
let ``ofEnglish returns correct result`` (english : string, expected : int) =
    let actual = Numeral.ofEnglish english
    expected =! actual