module Ploeh.Numsense.EnglishExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                             "zero",          0)>]
[<InlineData(                                            " zero",          0)>]
[<InlineData(                                            "zero ",          0)>]
[<InlineData(                                         "  zero  ",          0)>]
[<InlineData(                                             "Zero",          0)>]
[<InlineData(                                             "ZERO",          0)>]
[<InlineData(                                          " zERo\t",          0)>]
[<InlineData(                                              "one",          1)>]
[<InlineData(                                              "ONE",          1)>]
[<InlineData(                                              "two",          2)>]
[<InlineData(                                             " two",          2)>]
[<InlineData(                                            "three",          3)>]
[<InlineData(                                          "three  ",          3)>]
[<InlineData(                                             "four",          4)>]
[<InlineData(                                          "  four ",          4)>]
[<InlineData(                                             "five",          5)>]
[<InlineData(                                             "FivE",          5)>]
[<InlineData(                                              "six",          6)>]
[<InlineData(                                          "  SIX  ",          6)>]
[<InlineData(                                            "seven",          7)>]
[<InlineData(                                        "    seVen",          7)>]
[<InlineData(                                            "eight",          8)>]
[<InlineData(                                            "eIGHT",          8)>]
[<InlineData(                                             "nine",          9)>]
[<InlineData(                                           "NiNe  ",          9)>]
[<InlineData(                                              "ten",         10)>]
[<InlineData(                                           "eleven",         11)>]
[<InlineData(                                           "twelve",         12)>]
[<InlineData(                                         "thirteen",         13)>]
[<InlineData(                                         "fourteen",         14)>]
[<InlineData(                                          "fifteen",         15)>]
[<InlineData(                                          "sixteen",         16)>]
[<InlineData(                                        "seventeen",         17)>]
[<InlineData(                                         "eighteen",         18)>]
[<InlineData(                                         "nineteen",         19)>]
[<InlineData(                                           "twenty",         20)>]
[<InlineData(                                        "twentyone",         21)>]
[<InlineData(                                       "twenty-one",         21)>]
[<InlineData(                                           "thirty",         30)>]
[<InlineData(                                       "thirtyfour",         34)>]
[<InlineData(                                     "thirty-eight",         38)>]
[<InlineData(                                            "forty",         40)>]
[<InlineData(                                        "forty-one",         41)>]
[<InlineData(                                        "fortyfour",         44)>]
[<InlineData(                                            "fifty",         50)>]
[<InlineData(                                       "fiftyseven",         57)>]
[<InlineData(                                            "sixty",         60)>]
[<InlineData(                                        "sixtyfive",         65)>]
[<InlineData(                                          "seventy",         70)>]
[<InlineData(                                    "seventy-seven",         77)>]
[<InlineData(                                      "seventynine",         79)>]
[<InlineData(                                           "eighty",         80)>]
[<InlineData(                                        "eightysix",         86)>]
[<InlineData(                                           "ninety",         90)>]
[<InlineData(                                      "ninetythree",         93)>]
[<InlineData(                                          "hundred",        100)>]
[<InlineData(                                       "onehundred",        100)>]
[<InlineData(                                       "hundredone",        101)>]
[<InlineData(                                    "hundredandone",        101)>]
[<InlineData(                                  "hundred-and-one",        101)>]
[<InlineData(                                    "onehundredone",        101)>]
[<InlineData(                                 "onehundredandone",        101)>]
[<InlineData(                              "one-hundred-and-one",        101)>]
[<InlineData(                                       "twohundred",        200)>]
[<InlineData(                            "twohundredthirtyseven",        237)>]
[<InlineData(                          "threehundredseventyfive",        375)>]
[<InlineData(                                "fourhundredninety",        490)>]
[<InlineData(                            "fivehundredsixtythree",        563)>]
[<InlineData(                               "sixhundredeighteen",        618)>]
[<InlineData(                         "sevenhundredseventyseven",        777)>]
[<InlineData(                                 "eighthundredfive",        805)>]
[<InlineData(                               "eighthundredandsix",        806)>]
[<InlineData(                          "eight-hundred-and-seven",        807)>]
[<InlineData(                             "ninehundredfiftynine",        959)>]
[<InlineData(                                         "thousand",       1000)>]
[<InlineData(                                      "onethousand",       1000)>]
[<InlineData(                                      "thousandone",       1001)>]
[<InlineData(                                   "onethousandtwo",       1002)>]
[<InlineData(                             "onethousandsixtyfour",       1064)>]
[<InlineData(                                      "twothousand",       2000)>]
[<InlineData(               "eightthousandsevenhundredtwentyone",       8721)>]
[<InlineData(           "nine-thousand-one-hundred-twenty-three",       9123)>]
[<InlineData(                                      "tenthousand",      10000)>]
[<InlineData(                         "tenthousandonehundredone",      10101)>]
[<InlineData(                 "ten-thousand-one-hundred-and-two",      10102)>]
[<InlineData(          "twentythreethousandfivehundredsixtyfour",      23564)>]
[<InlineData(                                "eightythousandten",      80010)>]
[<InlineData(                                  "hundredthousand",     100000)>]
[<InlineData(                               "onehundredthousand",     100000)>]
[<InlineData(                            "onehundredthousandone",     100001)>]
[<InlineData("threehundrednineteenthousandthreehundredfortynine",     319349)>]
[<InlineData(                                       "onemillion",    1000000)>]
[<InlineData(                                    "onemillionone",    1000001)>]
[<InlineData(                                    "twomillionten",    2000010)>]
[<InlineData(                         "sixmillionthirtythousand",    6030000)>]
[<InlineData( "ninemilliontwohundredonethousandsixhundredeighty",    9201680)>]
[<InlineData(                                       "tenmillion",   10000000)>]
[<InlineData(                                   "tenmillionnine",   10000009)>]
[<InlineData(                                 "twentyonemillion",   21000000)>]
[<InlineData( "fortysevenmillionsixhundredsixtyonethousandsixty",   47661060)>]
[<InlineData(                                   "hundredmillion",  100000000)>]
[<InlineData(                                "onehundredmillion",  100000000)>]
[<InlineData(                            "twohundredfivemillion",  205000000)>]
[<InlineData(                  "three-hundred-and-seven-million",  307000000)>]
[<InlineData("fourhundredsixtyonemillionsixtythousandsixhundred",  461060600)>]
[<InlineData(                                       "onebillion", 1000000000)>]
[<InlineData(                                       "twobillion", 2000000000)>]
[<InlineData("twobillionfortyninemillionsixhundredfiftythousand", 2049650000)>]
[<InlineData(
    "twobilliononehundredfortysevenmillionfourhundredeightythreethousandsixhundredfortyseven",
    System.Int32.MaxValue)>]
let ``tryOfEnglish returns correct result`` (english : string, expected : int) =
    let actual = Numeral.tryOfEnglish english
    Some expected =! actual

[<Theory>]
[<InlineData( 0, "zero")>]
[<InlineData( 1, "one")>]
[<InlineData( 2, "two")>]
[<InlineData( 3, "three")>]
[<InlineData( 4, "four")>]
[<InlineData( 5, "five")>]
[<InlineData( 6, "six")>]
[<InlineData( 7, "seven")>]
[<InlineData( 8, "eight")>]
[<InlineData( 9, "nine")>]
[<InlineData(10, "ten")>]
[<InlineData(11, "eleven")>]
[<InlineData(12, "twelve")>]
[<InlineData(13, "thirteen")>]
[<InlineData(14, "fourteen")>]
[<InlineData(15, "fifteen")>]
[<InlineData(16, "sixteen")>]
[<InlineData(17, "seventeen")>]
[<InlineData(18, "eighteen")>]
[<InlineData(19, "nineteen")>]
[<InlineData(20, "twenty")>]
[<InlineData(21, "twenty-one")>]
[<InlineData(30, "thirty")>]
[<InlineData(34, "thirty-four")>]
[<InlineData(40, "forty")>]
[<InlineData(42, "forty-two")>]
[<InlineData(50, "fifty")>]
[<InlineData(58, "fifty-eight")>]
[<InlineData(60, "sixty")>]
[<InlineData(65, "sixty-five")>]
[<InlineData(70, "seventy")>]
[<InlineData(79, "seventy-nine")>]
[<InlineData(80, "eighty")>]
[<InlineData(86, "eighty-six")>]
[<InlineData(90, "ninety")>]
[<InlineData(93, "ninety-three")>]
let ``toEnglish returns correct result`` (i : int, expected : string) =
    let actual = Numeral.toEnglish i
    expected =! actual