module Ploeh.Numsense.FarsiExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData("صفر",                                                     0)>]
[<InlineData(" صفر",                                                    0)>]
[<InlineData("صفر ",                                                    0)>]
[<InlineData("  صفر  ",                                                 0)>]
[<InlineData(" صفر\t",                                                  0)>]
[<InlineData("یک",                                                      1)>]
[<InlineData("دو",                                                      2)>]
[<InlineData("دو  ",                                                    2)>]
[<InlineData("  دو  ",                                                  2)>]
[<InlineData("   سه",                                                   3)>]
[<InlineData("چهار",                                                    4)>]
[<InlineData("پنج",                                                     5)>]
[<InlineData("شش",                                                      6)>]
[<InlineData("هفت",                                                     7)>]
[<InlineData("هشت",                                                     8)>]
[<InlineData("نه",                                                      9)>]
[<InlineData("ده",                                                     10)>]
[<InlineData("یازده",                                                  11)>]
[<InlineData("دوازده",                                                 12)>]
[<InlineData("سیزده",                                                  13)>]
[<InlineData("چهارده",                                                 14)>]
[<InlineData("پانزده",                                                 15)>]
[<InlineData("شانزده",                                                 16)>]
[<InlineData("هفده",                                                   17)>]
[<InlineData("هجده",                                                   18)>]
[<InlineData("نوزده",                                                  19)>]
[<InlineData("بیست",                                                   20)>]
[<InlineData("بیست و یک",                                              21)>]
[<InlineData("بیست و دو",                                              22)>]
[<InlineData("سی",                                                     30)>]
[<InlineData("سی و سه",                                                33)>]
[<InlineData("چهل",                                                    40)>]
[<InlineData("چهل و چهار",                                             44)>]
[<InlineData("پنجاه",                                                  50)>]
[<InlineData("پنجاه و پنج",                                            55)>]
[<InlineData("شصت",                                                    60)>]
[<InlineData("شصت و شش",                                               66)>]
[<InlineData("هفتاد",                                                  70)>]
[<InlineData("هفتاد و هفت",                                            77)>]
[<InlineData("هشتاد",                                                  80)>]
[<InlineData("هشتاد و هشت",                                            88)>]
[<InlineData("نود",                                                    90)>]
[<InlineData("نود و نه",                                               99)>]
[<InlineData("صد",                                                     100)>]
[<InlineData("صد و یک",                                                101)>]
[<InlineData("صد و ده",                                                110)>]
[<InlineData("صد و یازده",                                             111)>]
[<InlineData("صد و بیست",                                              120)>]
[<InlineData("صد و بیست و دو",                                         122)>]
[<InlineData("صد و سی",                                                130)>]
[<InlineData("صد و سی و سه",                                           133)>]
[<InlineData("صد و چهل",                                               140)>]
[<InlineData("صد و چهل و چهار",                                        144)>]
[<InlineData("صد و پنجاه",                                             150)>]
[<InlineData("صد و پنجاه و پنج",                                       155)>]
[<InlineData("صد و شصت",                                               160)>]
[<InlineData("صد و شصت و شش",                                          166)>]
[<InlineData("صد و هفتاد",                                             170)>]
[<InlineData("صد و هفتاد و هفت",                                       177)>]
[<InlineData("صد و هشتاد",                                             180)>]
[<InlineData("صد و هشتاد و هشت",                                       188)>]
[<InlineData("صد و نود",                                               190)>]
[<InlineData("صد و نود و نه",                                          199)>]
[<InlineData("دویست",                                                  200)>]
[<InlineData("سیصد",                                                   300)>]
[<InlineData("چهارصد",                                                 400)>]
[<InlineData("پانصد",                                                  500)>]
[<InlineData("ششصد",                                                   600)>]
[<InlineData("هفتصد",                                                  700)>]
[<InlineData("هشتصد",                                                  800)>] 
[<InlineData("نهصد",                                                   900)>]
[<InlineData("هزار",                                                   1000)>]
[<InlineData("هزار و یک",                                              1001)>]
[<InlineData("هزار و ده",                                              1010)>]
[<InlineData("هزار و یازده",                                           1011)>]
[<InlineData("هزار و صد و ده",                                         1110)>]
[<InlineData("هزار و صد و یازده",                                      1111)>]
[<InlineData("دو هزار",                                                2000)>]
[<InlineData("سه هزار",                                                3000)>]
[<InlineData("چهار هزار",                                              4000)>]
[<InlineData("پنج هزار",                                               5000)>]
[<InlineData("شش هزار",                                                6000)>]
[<InlineData("هفت هزار",                                               7000)>]
[<InlineData("هشت هزار",                                               8000)>]
[<InlineData("نه هزار",                                                9000)>]
[<InlineData("ده هزار",                                                10000)>]
[<InlineData("ده هزار و یک",                                           10001)>]
[<InlineData("ده هزار و ده",                                           10010)>]
[<InlineData("ده هزار و صد",                                           10100)>]
[<InlineData("ده هزار و صد و یک",                                      10101)>]
[<InlineData("ده هزار و صد و یازده",                                   10111)>]
[<InlineData("یازده هزار و صد و یازده",                                11111)>]
[<InlineData("یازده هزار و یک",                                        11001)>]
[<InlineData("یازده هزار و یازده",                                     11011)>]
[<InlineData("دوازده هزار",                                            12000)>]
[<InlineData("نود هزار",                                               90000)>]
[<InlineData("صد هزار",                                                100000)>]
[<InlineData("دویست هزار",                                             200000)>]
[<InlineData("سیصد هزار",                                              300000)>]
[<InlineData("چهارصد هزار",                                            400000)>]
[<InlineData("پانصد هزار",                                             500000)>]
[<InlineData("ششصد هزار",                                              600000)>]
[<InlineData("هفتصد هزار",                                             700000)>]
[<InlineData("هشتصد هزار",                                             800000)>]
[<InlineData("نهصد هزار",                                              900000)>]
[<InlineData("یک میلیون",                                              1000000)>]
[<InlineData("یک میلیون و یک",                                         1000001)>]
[<InlineData("یک میلیون و ده",                                         1000010)>]
[<InlineData("یک میلیون و یازده",                                      1000011)>]
[<InlineData("دو میلیون و دویست و بیست و دو",                          2000222)>]
[<InlineData("دو میلیون و دو هزار و دویست و بیست و دو",                2002222)>]
[<InlineData("دو میلیون و بیست و دو هزار و دویست و بیست و دو",         2022222)>]
[<InlineData("دو میلیون و دویست و بیست و دو هزار و دویست و بیست و دو", 2222222)>]
[<InlineData("چهل و هفت میلیون و ششصد و شصت و یک هزار و شصت",          47661060)>]
[<InlineData("صد میلیون",                                              100000000)>]
[<InlineData("دویست و پنج میلیون",                                     205000000)>]
[<InlineData("سیصد و هفت میلیون",                                      307000000)>]
[<InlineData("چهارصد و شصت و یک میلیون و شصت هزار و ششصد",             461060600)>]
[<InlineData("یک میلیارد",                                             1000000000)>]
[<InlineData("دو میلیارد",                                             2000000000)>]
[<InlineData("دو میلیارد و چهل و نه میلیون و ششصد و پنجاه هزار",       2049650000)>]
[<InlineData("دو میلیارد و صد و چهل و هفت میلیون و چهارصد و هشتاد و سه هزار و ششصد و چهل و هفت", System.Int32.MaxValue)>]
let ``tryOfFarsi returns correct result`` (farsi, expected) =
    let actual = Numeral.tryParseFarsi farsi
    Some expected =! actual


[<Theory>]
[<InlineData(         0, "صفر")>]
[<InlineData(         1, "یک")>]
[<InlineData(         2, "دو")>]
[<InlineData(         3, "سه")>]
[<InlineData(         4, "چهار")>]
[<InlineData(         5, "پنج")>]
[<InlineData(         6, "شش")>]
[<InlineData(         7, "هفت")>]
[<InlineData(         8, "هشت")>]
[<InlineData(         9, "نه")>]
[<InlineData(        10, "ده")>]
[<InlineData(        11, "یازده")>]
[<InlineData(        12, "دوازده")>]
[<InlineData(        13, "سیزده")>]
[<InlineData(        14, "چهارده")>]
[<InlineData(        15, "پانزده")>]
[<InlineData(        16, "شانزده")>]
[<InlineData(        17, "هفده")>]
[<InlineData(        18, "هجده")>]
[<InlineData(        19, "نوزده")>]
[<InlineData(        20, "بیست")>]
[<InlineData(        21, "بیست و یک")>]
[<InlineData(        22, "بیست و دو")>]
[<InlineData(        30, "سی")>]
[<InlineData(        39, "سی و نه")>]
[<InlineData(        40, "چهل")>]
[<InlineData(        50, "پنجاه")>]
[<InlineData(        60, "شصت")>]
[<InlineData(        70, "هفتاد")>]
[<InlineData(        80, "هشتاد")>]
[<InlineData(        90, "نود")>]
[<InlineData(        99, "نود و نه")>]
[<InlineData(        100, "صد")>]
[<InlineData(        101, "صد و یک")>]
[<InlineData(        110, "صد و ده")>]
[<InlineData(        115, "صد و پانزده")>]
[<InlineData(        123, "صد و بیست و سه")>]
[<InlineData(        200, "دویست")>]
[<InlineData(        201, "دویست و یک")>]
[<InlineData(        222, "دویست و بیست و دو")>]
[<InlineData(        300, "سیصد")>]
[<InlineData(        350, "سیصد و پنجاه")>]
[<InlineData(        400, "چهارصد")>]
[<InlineData(        465, "چهارصد و شصت و پنج")>]
[<InlineData(        500, "پانصد")>]
[<InlineData(        579, "پانصد و هفتاد و نه")>]
[<InlineData(        600, "ششصد")>]
[<InlineData(        666, "ششصد و شصت و شش")>]
[<InlineData(        701, "هفتصد و یک")>]
[<InlineData(        899, "هشتصد و نود و نه")>]
[<InlineData(        900, "نهصد")>]
[<InlineData(        940, "نهصد و چهل")>]
[<InlineData(        1000, "هزار")>]
[<InlineData(        1001, "هزار و یک")>]
[<InlineData(        1010, "هزار و ده")>]
[<InlineData(        1011, "هزار و یازده")>]
[<InlineData(        1020, "هزار و بیست")>]
[<InlineData(        1100, "هزار و صد")>]
[<InlineData(        1110, "هزار و صد و ده")>]
[<InlineData(        1111, "هزار و صد و یازده")>]
[<InlineData(        1200, "هزار و دویست")>]
[<InlineData(        1300, "هزار و سیصد")>]
[<InlineData(        1400, "هزار و چهارصد")>]
[<InlineData(        1500, "هزار و پانصد")>]
[<InlineData(        1600, "هزار و ششصد")>]
[<InlineData(        1700, "هزار و هفتصد")>]
[<InlineData(        1800, "هزار و هشتصد")>]
[<InlineData(        1900, "هزار و نهصد")>]
[<InlineData(        2000, "دو هزار")>]
[<InlineData(        2001, "دو هزار و یک")>]
[<InlineData(        3000, "سه هزار")>]
[<InlineData(        3010, "سه هزار و ده")>]
[<InlineData(        4000, "چهار هزار")>]
[<InlineData(        4100, "چهار هزار و صد")>]
[<InlineData(        5000, "پنج هزار")>]
[<InlineData(        5011, "پنج هزار و یازده")>]
[<InlineData(        6000, "شش هزار")>]
[<InlineData(        6222, "شش هزار و دویست و بیست و دو")>]
[<InlineData(        7000, "هفت هزار")>]
[<InlineData(        7033, "هفت هزار و سی و سه")>]
[<InlineData(        8000, "هشت هزار")>]
[<InlineData(        8000, "هشت هزار")>]
[<InlineData(        9000, "نه هزار")>]
[<InlineData(        9999, "نه هزار و نهصد و نود و نه")>]
[<InlineData(        10000, "ده هزار")>]
[<InlineData(        10001, "ده هزار و یک")>]
[<InlineData(       100000, "صد هزار")>]
[<InlineData(       200000, "دویست هزار")>]
[<InlineData(       300000, "سیصد هزار")>]
[<InlineData(       400000, "چهارصد هزار")>]
[<InlineData(       500000, "پانصد هزار")>]
[<InlineData(       600000, "ششصد هزار")>]
[<InlineData(       700000, "هفتصد هزار")>]
[<InlineData(       800000, "هشتصد هزار")>]
[<InlineData(       900000, "نهصد هزار")>]
[<InlineData(      1000000, "یک میلیون")>]
[<InlineData(     10000000, "ده میلیون")>]
[<InlineData(    100000000, "صد میلیون")>]
[<InlineData(   1000000000, "یک میلیارد")>]
[<InlineData(   2121000000, "دو میلیارد و صد و بیست و یک میلیون")>]
[<InlineData(System.Int32.MaxValue, "دو میلیارد و صد و چهل و هفت میلیون و چهارصد و هشتاد و سه هزار و ششصد و چهل و هفت")>]
let ``toFarsi returns correct result`` (i, expected) =
    let actual = Numeral.toFarsi i
    expected =! actual