module Ploeh.Numsense.FrenchExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                                  "zero",          0)>]
[<InlineData(                                                 " zero",          0)>]
[<InlineData(                                                 "zero ",          0)>]
[<InlineData(                                              "  zéro  ",          0)>]
[<InlineData(                                                  "Zéro",          0)>]
[<InlineData(                                                  "ZERO",          0)>]
[<InlineData(                                               " zERo\t",          0)>]
[<InlineData(                                                    "un",          1)>]
[<InlineData(                                                    "UN",          1)>]
[<InlineData(                                                  "deux",          2)>]
[<InlineData(                                                 " deux",          2)>]
[<InlineData(                                                 "trois",          3)>]
[<InlineData(                                               "trois  ",          3)>]
[<InlineData(                                                "quatre",          4)>]
[<InlineData(                                             "  quatre ",          4)>]
[<InlineData(                                                  "cinq",          5)>]
[<InlineData(                                                  "CinQ",          5)>]
[<InlineData(                                                   "six",          6)>]
[<InlineData(                                               "  SIX  ",          6)>]
[<InlineData(                                                  "sept",          7)>]
[<InlineData(                                              "    sePt",          7)>]
[<InlineData(                                                  "huit",          8)>]
[<InlineData(                                                  "hUIT",          8)>]
[<InlineData(                                                  "neuf",          9)>]
[<InlineData(                                                "Neuf  ",          9)>]
[<InlineData(                                                   "dix",         10)>]
[<InlineData(                                                  "onze",         11)>]
[<InlineData(                                                 "douze",         12)>]
[<InlineData(                                                "treize",         13)>]
[<InlineData(                                              "quatorze",         14)>]
[<InlineData(                                                "quinze",         15)>]
[<InlineData(                                                 "seize",         16)>]
[<InlineData(                                              "dix-sept",         17)>]
[<InlineData(                                              "dix-huit",         18)>]
[<InlineData(                                              "dix-neuf",         19)>]
[<InlineData(                                                 "vingt",         20)>]
[<InlineData(                                           "vingt-et-un",         21)>]
[<InlineData(                                              "vingt-un",         21)>]
[<InlineData(                                                "trente",         30)>]
[<InlineData(                                         "trente-quatre",         34)>]
[<InlineData(                                           "trente-huit",         38)>]
[<InlineData(                                              "quarante",         40)>]
[<InlineData(                                        "quarante-et-un",         41)>]
[<InlineData(                                       "quarante-quatre",         44)>]
[<InlineData(                                             "cinquante",         50)>]
[<InlineData(                                        "cinquante-sept",         57)>]
[<InlineData(                                              "soixante",         60)>]
[<InlineData(                                         "soixante-cinq",         65)>]
[<InlineData(                                          "soixante-dix",         70)>]
[<InlineData(                                      "soixante-et-onze",         71)>]
[<InlineData(                                     "soixante-dix-sept",         77)>]
[<InlineData(                                     "soixante-dix-neuf",         79)>]
[<InlineData(                                         "quatre-vingts",         80)>]
[<InlineData(                                       "quatre-vingt-un",         81)>]
[<InlineData(                                      "quatre-vingt-six",         86)>]
[<InlineData(                                      "quatre-vingt-dix",         90)>]
[<InlineData(                                   "quatre-vingt-treize",         93)>]
[<InlineData(                                                  "cent",        100)>]
[<InlineData(                                               "cent-un",        101)>]
[<InlineData(                                                "centun",        101)>]
[<InlineData(                                             "deuxcents",        200)>]
[<InlineData(                                    "deuxcenttrentesept",        237)>]
[<InlineData(                               "troiscentsoixantequinze",        375)>]
[<InlineData(                              "quatrecentquatrevingtdix",        490)>]
[<InlineData(                                 "cinqcentsoixantetrois",        563)>]
[<InlineData(                                        "sixcentdixhuit",        618)>]
[<InlineData(                               "septcentsoixantedixsept",        777)>]
[<InlineData(                                          "huitcentcinq",        805)>]
[<InlineData(                                           "huitcentsix",        806)>]
[<InlineData(                                        "huit-cent-sept",        807)>]
[<InlineData(                                 "neufcentcinquanteneuf",        959)>]
[<InlineData(                                                 "mille",       1000)>]
[<InlineData(                                               "milleun",       1001)>]
[<InlineData(                                            "mille-deux",       1002)>]
[<InlineData(                                   "millesoixantequatre",       1064)>]
[<InlineData(                                           "quinzecents",       1500)>]
[<InlineData(                                      "quinzecentquinze",       1515)>]
[<InlineData(                            "seizecentquatrevingtquinze",       1695)>]
[<InlineData(                                             "deuxmille",       2000)>]
[<InlineData(                            "huitmilleseptcentvingtetun",       8721)>]
[<InlineData(                           "neuf-mille-cent-vingt-trois",       9123)>]
[<InlineData(                                             "dix-mille",      10000)>]
[<InlineData(                                        "dixmillecentun",      10101)>]
[<InlineData(                                   "dix-mille-cent-deux",      10102)>]
[<InlineData(                   "vingttroismillecinqcentsoixantesept",      23567)>]
[<InlineData(                      "quatrevingtmillequatrevingtdouze",      80092)>]
[<InlineData(                                             "centmille",     100000)>]
[<InlineData(                                      "deux-cents-mille",     200000)>]
[<InlineData(                                         "cent-mille-un",     100001)>]
[<InlineData(            "troiscentdixneufmilletroiscentquaranteneuf",     319349)>]
[<InlineData(                                            "un-million",    1000000)>]
[<InlineData(                                           "unmillionun",    1000001)>]
[<InlineData(                                       "deuxmillionsdix",    2000010)>]
[<InlineData(                                "sixmillionstrentemille",    6030000)>]
[<InlineData(         "neufmillionsdeuxcentunmillesixcentquatrevingt",    9201680)>]
[<InlineData(                                           "dixmillions",   10000000)>]
[<InlineData(                                       "dixmillionsneuf",   10000009)>]
[<InlineData(                                     "vingtetunmillions",   21000000)>]
[<InlineData(  "quaranteseptmillionssixcentsoixanteetunmillesoixante",   47661060)>]
[<InlineData(                                          "centmillions",  100000000)>]
[<InlineData(                                        "centmillionsun",  100000001)>]
[<InlineData(                                     "deuxcentsmillions",  200000000)>]
[<InlineData(                                  "deuxcentcinqmillions",  205000000)>]
[<InlineData(                              "trois-cent-sept-millions",  307000000)>]
[<InlineData(    "quatrecentsoixanteetunmillionssoixantemillesixcent",  461060600)>]
[<InlineData(                                            "unmilliard", 1000000000)>]
[<InlineData(                                         "deuxmilliards", 2000000000)>]
[<InlineData("deuxmilliardsquaranteneufmillionssixcentcinquantemille", 2049650000)>]
[<InlineData("deuxmilliardscentquaranteseptmillionsquatrecentquatrevingttroismillesixcentquarantesept",
    System.Int32.MaxValue)>]
let ``tryOfFrench returns correct result`` (french, expected) =
    let actual = Numeral.tryParseFrench french
    Some expected =! actual

[<Theory>]
[<InlineData(         0, "zéro")>]
[<InlineData(         1, "un")>]
[<InlineData(         2, "deux")>]
[<InlineData(         3, "trois")>]
[<InlineData(         4, "quatre")>]
[<InlineData(         5, "cinq")>]
[<InlineData(         6, "six")>]
[<InlineData(         7, "sept")>]
[<InlineData(         8, "huit")>]
[<InlineData(         9, "neuf")>]
[<InlineData(        10, "dix")>]
[<InlineData(        11, "onze")>]
[<InlineData(        12, "douze")>]
[<InlineData(        13, "treize")>]
[<InlineData(        14, "quatorze")>]
[<InlineData(        15, "quinze")>]
[<InlineData(        16, "seize")>]
[<InlineData(        17, "dix-sept")>]
[<InlineData(        18, "dix-huit")>]
[<InlineData(        19, "dix-neuf")>]
[<InlineData(        20, "vingt")>]
[<InlineData(        21, "vingt-et-un")>]
[<InlineData(        30, "trente")>]
[<InlineData(        34, "trente-quatre")>]
[<InlineData(        40, "quarante")>]
[<InlineData(        42, "quarante-deux")>]
[<InlineData(        50, "cinquante")>]
[<InlineData(        58, "cinquante-huit")>]
[<InlineData(        60, "soixante")>]
[<InlineData(        65, "soixante-cinq")>]
[<InlineData(        70, "soixante-dix")>]
[<InlineData(        79, "soixante-dix-neuf")>]
[<InlineData(        80, "quatre-vingts")>]
[<InlineData(        86, "quatre-vingt-six")>]
[<InlineData(        90, "quatre-vingt-dix")>]
[<InlineData(        93, "quatre-vingt-treize")>]
[<InlineData(       100, "cent")>]
[<InlineData(       101, "cent-un")>]
[<InlineData(       110, "cent-dix")>]
[<InlineData(       114, "cent-quatorze")>]
[<InlineData(       135, "cent-trente-cinq")>]
[<InlineData(       200, "deux-cents")>]
[<InlineData(       282, "deux-cent-quatre-vingt-deux")>]
[<InlineData(       331, "trois-cent-trente-et-un")>]
[<InlineData(       407, "quatre-cent-sept")>]
[<InlineData(       520, "cinq-cent-vingt")>]
[<InlineData(       666, "six-cent-soixante-six")>]
[<InlineData(       798, "sept-cent-quatre-vingt-dix-huit")>]
[<InlineData(       857, "huit-cent-cinquante-sept")>]
[<InlineData(       999, "neuf-cent-quatre-vingt-dix-neuf")>]
[<InlineData(      1000, "mille")>]
[<InlineData(      1001, "mille-un")>]
[<InlineData(      1010, "mille-dix")>]
[<InlineData(      1066, "mille-soixante-six")>]
[<InlineData(      1337, "mille-trois-cent-trente-sept")>]
[<InlineData(      1984, "mille-neuf-cent-quatre-vingt-quatre")>]
[<InlineData(      2015, "deux-mille-quinze")>]
[<InlineData(      3000, "trois-mille")>]
[<InlineData(      3297, "trois-mille-deux-cent-quatre-vingt-dix-sept")>]
[<InlineData(      4080, "quatre-mille-quatre-vingts")>]
[<InlineData(      5011, "cinq-mille-onze")>]
[<InlineData(      6025, "six-mille-vingt-cinq")>]
[<InlineData(      7441, "sept-mille-quatre-cent-quarante-et-un")>]
[<InlineData(      8513, "huit-mille-cinq-cent-treize")>]
[<InlineData(      9000, "neuf-mille")>]
[<InlineData(     10000, "dix-mille")>]
[<InlineData(     12001, "douze-mille-un")>]
[<InlineData(     23456, "vingt-trois-mille-quatre-cent-cinquante-six")>]
[<InlineData(     32109, "trente-deux-mille-cent-neuf")>]
[<InlineData(     40404, "quarante-mille-quatre-cent-quatre")>]
[<InlineData(     56789, "cinquante-six-mille-sept-cent-quatre-vingt-neuf")>]
[<InlineData(     60015, "soixante-mille-quinze")>]
[<InlineData(     71003, "soixante-et-onze-mille-trois")>]
[<InlineData(     80522, "quatre-vingts-mille-cinq-cent-vingt-deux")>]
[<InlineData(     98765, "quatre-vingt-dix-huit-mille-sept-cent-soixante-cinq")>]
[<InlineData(    100000, "cent-mille")>]
[<InlineData(    100001, "cent-mille-un")>]
[<InlineData(    100010, "cent-mille-dix")>]
[<InlineData(    101010, "cent-un-mille-dix")>]
[<InlineData(    200000, "deux-cents-mille")>]
[<InlineData(    321000, "trois-cent-vingt-et-un-mille")>]
[<InlineData(    411416, "quatre-cent-onze-mille-quatre-cent-seize")>]
[<InlineData(    530121, "cinq-cent-trente-mille-cent-vingt-et-un")>]
[<InlineData(    600000, "six-cents-mille")>]
[<InlineData(    788000, "sept-cent-quatre-vingt-huit-mille")>]
[<InlineData(    876540, "huit-cent-soixante-seize-mille-cinq-cent-quarante")>]
[<InlineData(    908077, "neuf-cent-huit-mille-soixante-dix-sept")>]
[<InlineData(   1000000, "un-million")>]
[<InlineData(   2000002, "deux-millions-deux")>]
[<InlineData(   3040506, "trois-millions-quarante-mille-cinq-cent-six")>]
[<InlineData(   4321000, "quatre-millions-trois-cent-vingt-et-un-mille")>]
[<InlineData(   5004621, "cinq-millions-quatre-mille-six-cent-vingt-et-un")>]
[<InlineData(   6982001, "six-millions-neuf-cent-quatre-vingt-deux-mille-un")>]
[<InlineData(   7000000, "sept-millions")>]
[<InlineData(   8000220, "huit-millions-deux-cent-vingt")>]
[<InlineData(   9099000, "neuf-millions-quatre-vingt-dix-neuf-mille")>]
[<InlineData(  10000000, "dix-millions")>]
[<InlineData(  24000000, "vingt-quatre-millions")>]
[<InlineData(  39020011, "trente-neuf-millions-vingt-mille-onze")>]
[<InlineData(  40606100, "quarante-millions-six-cent-six-mille-cent")>]
[<InlineData(  53000000, "cinquante-trois-millions")>]
[<InlineData(  64000098, "soixante-quatre-millions-quatre-vingt-dix-huit")>]
[<InlineData(  70003190, "soixante-dix-millions-trois-mille-cent-quatre-vingt-dix")>]
[<InlineData(  80000000, "quatre-vingts-millions")>]
[<InlineData(  80000080, "quatre-vingts-millions-quatre-vingts")>]
[<InlineData(  80000081, "quatre-vingts-millions-quatre-vingt-un")>]
[<InlineData(  99000099, "quatre-vingt-dix-neuf-millions-quatre-vingt-dix-neuf")>]
[<InlineData( 100000000, "cent-millions")>]
[<InlineData( 209000000, "deux-cent-neuf-millions")>]
[<InlineData( 398000000, "trois-cent-quatre-vingt-dix-huit-millions")>]
[<InlineData( 439011000, "quatre-cent-trente-neuf-millions-onze-mille")>]
[<InlineData( 560400000, "cinq-cent-soixante-millions-quatre-cents-mille")>]
[<InlineData( 600100900, "six-cents-millions-cent-mille-neuf-cents")>]
[<InlineData( 600200900, "six-cents-millions-deux-cents-mille-neuf-cents")>]
[<InlineData( 700000000, "sept-cents-millions")>]
[<InlineData( 800116000, "huit-cents-millions-cent-seize-mille")>]
[<InlineData( 900800007, "neuf-cents-millions-huit-cents-mille-sept")>]
[<InlineData(1000000000, "un-milliard")>]
[<InlineData(2121000000, "deux-milliards-cent-vingt-et-un-millions")>]
[<InlineData(
    System.Int32.MaxValue,
    "deux-milliards-cent-quarante-sept-millions-quatre-cent-quatre-vingt-trois-mille-six-cent-quarante-sept")>]
let ``toFrench returns correct result`` (i, expected) =
    let actual =
        i
        |> Numeral.toFrench
    expected =! actual
