module Ploeh.Numsense.GermanExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                                                "null",          0)>]
[<InlineData(                                                               " null",          0)>]
[<InlineData(                                                               "null ",          0)>]
[<InlineData(                                                            "  null  ",          0)>]
[<InlineData(                                                                "Null",          0)>]
[<InlineData(                                                                "NULL",          0)>]
[<InlineData(                                                             " nULL\t",          0)>]
[<InlineData(                                                                "eins",          1)>]
[<InlineData(                                                                "eins",          1)>]
[<InlineData(                                                                "zwei",          2)>]
[<InlineData(                                                               " zwei",          2)>]
[<InlineData(                                                                "drei",          3)>]
[<InlineData(                                                              "drei  ",          3)>]
[<InlineData(                                                                "vier",          4)>]
[<InlineData(                                                             "  vier ",          4)>]
[<InlineData(                                                                "fünf",          5)>]
[<InlineData(                                                                "FünF",          5)>]
[<InlineData(                                                               "sechs",          6)>]
[<InlineData(                                                           "  SECHS  ",          6)>]
[<InlineData(                                                              "sieben",          7)>]
[<InlineData(                                                          "    sieBen",          7)>]
[<InlineData(                                                                "acht",          8)>]
[<InlineData(                                                                "aCHT",          8)>]
[<InlineData(                                                                "neun",          9)>]
[<InlineData(                                                              "NeUn  ",          9)>]
[<InlineData(                                                                "zehn",         10)>]
[<InlineData(                                                                 "elf",         11)>]
[<InlineData(                                                               "zwölf",         12)>]
[<InlineData(                                                            "dreizehn",         13)>]
[<InlineData(                                                            "vierzehn",         14)>]
[<InlineData(                                                            "fünfzehn",         15)>]
[<InlineData(                                                           "sechszehn",         16)>]
[<InlineData(                                                          "siebenzehn",         17)>]
[<InlineData(                                                            "achtzehn",         18)>]
[<InlineData(                                                            "neunzehn",         19)>]
[<InlineData(                                                             "zwanzig",         20)>]
[<InlineData(                                                     "ein und zwanzig",         21)>]
[<InlineData(                                                       "einundzwanzig",         21)>]
[<InlineData(                                                             "dreißig",         30)>]
[<InlineData(                                                      "vierunddreißig",         34)>]
[<InlineData(                                                    "acht und dreißig",         38)>]
[<InlineData(                                                             "vierzig",         40)>]
[<InlineData(                                                     "ein-und-vierzig",         41)>]
[<InlineData(                                                      "vierundvierzig",         44)>]
[<InlineData(                                                             "fünfzig",         50)>]
[<InlineData(                                                    "siebenundfünfzig",         57)>]
[<InlineData(                                                             "sechzig",         60)>]
[<InlineData(                                                      "fünfundsechzig",         65)>]
[<InlineData(                                                             "siebzig",         70)>]
[<InlineData(                                                  "sieben und siebzig",         77)>]
[<InlineData(                                                    "neun und siebzig",         79)>]
[<InlineData(                                                             "achtzig",         80)>]
[<InlineData(                                                     "sechsundachtzig",         86)>]
[<InlineData(                                                             "neunzig",         90)>]
[<InlineData(                                                    "drei-und-neunzig",         93)>]
[<InlineData(                                                             "hundert",        100)>]
[<InlineData(                                                          "einhundert",        100)>]
[<InlineData(                                                         "hunderteins",        101)>]
[<InlineData(                                                      "hundertundeins",        101)>]
[<InlineData(                                                    "hundert-und-eins",        101)>]
[<InlineData(                                                      "einhunderteins",        101)>]
[<InlineData(                                                   "einhundertundeins",        101)>]
[<InlineData(                                                "ein-hundert-und-eins",        101)>]
[<InlineData(                                                         "zweihundert",        200)>]
[<InlineData(                                         "zweihundertsiebenunddreißig",        237)>]
[<InlineData(                                           "dreihundertfünfundsiebzig",        375)>]
[<InlineData(                                                  "vierhundertneunzig",        490)>]
[<InlineData(                                           "fünfhundertdreiundsechzig",        563)>]
[<InlineData(                                                "sechshundertachtzehn",        618)>]
[<InlineData(                                       "siebenhundertsiebenundsiebzig",        777)>]
[<InlineData(                                                     "achthundertfünf",        805)>]
[<InlineData(                                                 "achthundertundsechs",        806)>]
[<InlineData(                                             "acht-hundert-und-sieben",        807)>]
[<InlineData(                                           "neunhundertneunundfünfzig",        959)>]
[<InlineData(                                                             "tausend",       1000)>]
[<InlineData(                                                          "eintausend",       1000)>]
[<InlineData(                                                         "tausendeins",       1001)>]
[<InlineData(                                                      "eintausendzwei",       1002)>]
[<InlineData(                                            "eintausendvierundsechzig",       1064)>]
[<InlineData(                                                         "zweitausend",       2000)>]
[<InlineData(                               "achttausendsiebenhunderteinundzwanzig",       8721)>]
[<InlineData(                           "neun-tausend-ein-hundert-drei-und-zwanzig",       9123)>]
[<InlineData(                                                         "zehntausend",      10000)>]
[<InlineData(                                           "zehntausendeinhunderteins",      10101)>]
[<InlineData(                                   "zehn-tausend-ein-hundert-und-zwei",      10102)>]
[<InlineData(                      "dreiundzwanzigtausendfünfhundertvierundsechzig",      23564)>]
[<InlineData(                                                  "achtzigtausendzehn",      80010)>]
[<InlineData(                                                      "hunderttausend",     100000)>]
[<InlineData(                                                   "einhunderttausend",     100000)>]
[<InlineData(                                            "einhunderttausendundeins",     100001)>]
[<InlineData(                 "dreihundertneunzehntausenddreihundertneunundvierzig",     319349)>]
[<InlineData(                                                         "einemillion",    1000000)>]
[<InlineData(                                                     "einemillioneins",    1000001)>]
[<InlineData(                                                  "einemillionundeins",    1000001)>]
[<InlineData(                                                   "zweimillionenzehn",    2000010)>]
[<InlineData(                                        "sechsmillionendreißigtausend",    6030000)>]
[<InlineData(              "neunmillionenzweihunderteinstausendsechshundertachtzig",    9201680)>]
[<InlineData(                                                       "zehnmillionen",   10000000)>]
[<InlineData(                                                   "zehnmillionenneun",   10000009)>]
[<InlineData(                                              "einundzwanzigmillionen",   21000000)>]
[<InlineData( "siebenundvierzigmillionensechshunderteinundsechzigtausendundsechzig",   47661060)>]
[<InlineData(                                                    "hundertmillionen",  100000000)>]
[<InlineData(                                                 "einhundertmillionen",  100000000)>]
[<InlineData(                                            "zweihundertfünfmillionen",  205000000)>]
[<InlineData(                                   "drei-hundert-und-sieben-millionen",  307000000)>]
[<InlineData(         "vierhunderteinundsechzigmillionensechzigtausendsechshundert",  461060600)>]
[<InlineData(                                                       "einemilliarde", 1000000000)>]
[<InlineData(                                                      "zweimilliarden", 2000000000)>]
//[<InlineData(          "zweimilliardenneunundvierzigmillionenfünfundsechzigtausend", 2049650000)>]
//[<InlineData(
//    "zweimilliardeneinhundertsiebenundvierzigmillionenvierhundertdreiundachtzigtausendsechshundertsiebenundvierzig",
//    System.Int32.MaxValue)>] //2147483647
let ``tryOfGerman returns correct result`` (german, expected) =
    let actual = Numeral.tryParseGerman german
    Some expected =! actual
(*
[<Theory>]
[<InlineData(         0, "zero")>]
[<InlineData(         1, "eins")>]
[<InlineData(         2, "zwei")>]
[<InlineData(         3, "drei")>]
[<InlineData(         4, "vier")>]
[<InlineData(         5, "fünf")>]
[<InlineData(         6, "sechs")>]
[<InlineData(         7, "sieben")>]
[<InlineData(         8, "acht")>]
[<InlineData(         9, "neun")>]
[<InlineData(        10, "zehn")>]
[<InlineData(        11, "elf")>]
[<InlineData(        12, "zwölf")>]
[<InlineData(        13, "dreizehn")>]
[<InlineData(        14, "vierzehn")>]
[<InlineData(        15, "fünfzehn")>]
[<InlineData(        16, "sechszehn")>]
[<InlineData(        17, "siebzehn")>]
[<InlineData(        18, "achtzehn")>]
[<InlineData(        19, "neunzehn")>]
[<InlineData(        20, "zwanzig")>]
[<InlineData(        21, "ein-und-zwanzig")>]
[<InlineData(        30, "dreisig")>]
[<InlineData(        34, "vier-und.dreisig")>]
[<InlineData(        40, "vierzig")>]
[<InlineData(        42, "zwei-und-vierzig")>]
[<InlineData(        50, "fünfzig")>]
[<InlineData(        58, "acht-und-fünfzig")>]
[<InlineData(        60, "sechzig")>]
[<InlineData(        65, "fünf-und-sechzig")>]
[<InlineData(        70, "siebzig")>]
[<InlineData(        79, "neun-und-siebzig")>]
[<InlineData(        80, "achtzig")>]
[<InlineData(        86, "sechs-und-achtzig")>]
[<InlineData(        90, "neunzig")>]
[<InlineData(        93, "drei-und-neunzig")>]
[<InlineData(       100, "ein-hundert")>]
[<InlineData(       101, "ein-hundert-eins")>]
[<InlineData(       110, "ein-hundert-zehn")>]
[<InlineData(       114, "ein-hundert-vierzehn")>]
[<InlineData(       135, "ein-hundert-fünf-und-dreisig")>]
[<InlineData(       200, "zwei-hundert")>]
[<InlineData(       282, "zwei-hundert-zwei-und-achtzig")>]
[<InlineData(       331, "drei-hundert-ein-und-dreisig")>]
[<InlineData(       407, "vier-hundert-sieben")>]
[<InlineData(       520, "fünf-hundert-zwanzig")>]
[<InlineData(       666, "sechs-hundert-sechs-und-sechzig")>]
[<InlineData(       798, "sieben-hundert-acht-und-neunzig")>]
[<InlineData(       857, "acht-hundert-sieben-und-fünfzig")>]
[<InlineData(       999, "neun-hundert-neun-und-neunzig")>]
[<InlineData(      1000, "ein-tausend")>]
[<InlineData(      1001, "ein-tausend-eins")>]
[<InlineData(      1010, "ein-tausend-zehn")>]
[<InlineData(      1066, "ein-tausend-sechs-und-sechzig")>]
[<InlineData(      1337, "ein-tausend-drei-hundert-sieben-und-dreisig")>]
[<InlineData(      1984, "ein-tausend-neun-hundert-vier-und-achtzig")>]
[<InlineData(      2015, "zwei-tausend-fünfzehn")>]
[<InlineData(      3000, "drei-tausend")>]
[<InlineData(      3297, "drei-tausend-zwei-hundert-sieben-und-neunzig")>]
[<InlineData(      4080, "vier-tausend-achtzig")>]
[<InlineData(      5011, "fünf-tausend-elf")>]
[<InlineData(      6025, "sechs-tausend-fünf-und-zwanzig")>]
[<InlineData(      7441, "sieben-tausend-vier-hundert-ein-und-vierzig")>]
[<InlineData(      8513, "acht-tausend-fünf-hundert-dreizehn")>]
[<InlineData(      9000, "neun-tausend")>]
[<InlineData(     10000, "zehn-tausend")>]
[<InlineData(     12001, "zwölf-tausend-eins")>]
[<InlineData(     23456, "drei-und-zwanzig-vier-hundert-sechs-und-fünfzig")>]
[<InlineData(     32109, "zwei-und-dreisig-ein-hundert-neun")>]
[<InlineData(     40404, "vierzig-tausend-vier-hundert-vier")>]
[<InlineData(     56789, "sechs-und-fünfzig-sieben-hundert-neun-und-achtzig")>]
[<InlineData(     60015, "sechzig-tausend-und-fünfzehn")>]
[<InlineData(     71003, "ein-und-siebzig-tausend-und-drei")>]
[<InlineData(     80522, "achtzig-tausend-fünf-hundert-zwei-und-zwanzig")>]
[<InlineData(     98765, "acht-und-neunzig-tausend-sieben-hundert-fünf-und-sechzig")>]
[<InlineData(    100000, "ein-hundert-tausend")>]
[<InlineData(    100001, "ein-hundert-tausend-eins")>]
[<InlineData(    100010, "ein-hundert-tausend-zehn")>]
[<InlineData(    101010, "ein-hundert-ein-tausend-und-zehn")>]
[<InlineData(    200000, "zwei-hundert-tausend")>]
[<InlineData(    321000, "drei-hundert-ein-und-zwanzig-tausend")>]
[<InlineData(    411416, "vier-hundert-elf-tausend-vier-hundert-sechzehn")>]
[<InlineData(    530121, "fünf-hundert-dreisig-tausend-ein-hundert-ein-und-zwanzig")>]
[<InlineData(    600000, "sechs-hundert-tausend")>]
[<InlineData(    788000, "sieben-hundert-acht-und-achtzig-tausend")>]
[<InlineData(    876540, "acht-hundert-sechs-und-siebzig-tausend-fünf-hundert-vierzig")>]
[<InlineData(    908077, "neun-hundert-acht-tausend-sieben-und-siebzig")>]
[<InlineData(   1000000, "eine-million")>]
[<InlineData(   2000002, "zwei-millionen-und-zwei")>]
[<InlineData(   3040506, "drei-millionen-vierzig-tausend-fünf-hundert-sechs")>]
[<InlineData(   4321000, "vier-millionen-drei-hundert-ein-und-zwanzig-tausend")>]
[<InlineData(   5004621, "fünf-millionen-vier-tausend-sechs-hundert-ein-und-zwanzig")>]
[<InlineData(   6982001, "sechs-millionen-neun-hundert-zwei-und-achtzig-tausend-eins")>]
[<InlineData(   7000000, "sieben-millionen")>]
[<InlineData(   8000220, "acht-millionen-zwei-hundert-zwanzig")>]
[<InlineData(   9099000, "neun-millionen-neun-und-neunzig-tausend")>]
[<InlineData(  10000000, "zehn-millionen")>]
[<InlineData(  24000000, "vier-und-zwanzig-millionen")>]
[<InlineData(  39020011, "neun-und-dreisig-millionen-zwanzig-tausend-elf")>]
[<InlineData(  40606100, "vierzig-millionen-sechs-hundert-sechs-tausend-ein-hundert")>]
[<InlineData(  53000000, "drei-und-fünfzig-millionen")>]
[<InlineData(  64000098, "vier-und-sechzig-millionen-acht-und-neunzig")>]
[<InlineData(  70003190, "siebzig-millionen-drei-tausend-ein-hundert-neunzig")>]
[<InlineData(  80000000, "achtzig-millionen")>]
[<InlineData(  99000099, "neun-und-neunzig-millionen-neun-und-neunzig")>]
[<InlineData( 100000000, "ein-hundert-millionen")>]
[<InlineData( 209000000, "zwei-hundert-neun-millionen")>]
[<InlineData( 398000000, "drei-hundert-acht-und-neunzig-millionen")>]
[<InlineData( 439011000, "vier-hundert-neun-und-dreisig-neun-millionen-elf-tausend")>]
[<InlineData( 560400000, "fünf-hundert-sechzig-millionen-vier-hundert-tausend")>]
[<InlineData( 600010900, "sechs-hundert-millionen-zehn-tausend-neun-hundert")>]
[<InlineData( 700000000, "sieben-hundert-millionen")>]
[<InlineData( 800116000, "acht-hundert-millionen-ein-hundert-sechzehn-tausend")>]
[<InlineData( 900800007, "neun-hundert-millionen-acht-hundert-tausend-sieben")>]
[<InlineData(1000000000, "eine-milliarde")>]
//[<InlineData(2121000000, "zwei-milliarde-ein-hundert-ein-und-zwanzig-millionen")>]
//[<InlineData(
//    System.Int32.MaxValue,
//    "zwei-milliarden-ein-hundert-sieben-und-vierzig-millionen-vier-hundert-drei-und-achtzig-tausend-sechs-hundert-sieben-und-vierzig")>]
let ``toGerman returns correct result`` (i, expected) =
    let actual = Numeral.toGerman i
    expected =! actual
*)
