module Ploeh.Numsense.GermanExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                                                "null",          0)>]
[<InlineData(                                                               " null",          0)>]
[<InlineData(                                                               "null ",          0)>]
[<InlineData(                                                            "  null  ",          0)>]
[<InlineData(                                                                "Null",          0)>]
[<InlineData(                                                                "NULL",          0)>]
[<InlineData(                                                             " nULL\t",          0)>]
[<InlineData(                                                                "eins",          1)>]
[<InlineData(                                                                "zwei",          2)>]
[<InlineData(                                                               " zwei",          2)>]
[<InlineData(                                                                "drei",          3)>]
[<InlineData(                                                              "drei  ",          3)>]
[<InlineData(                                                                "vier",          4)>]
[<InlineData(                                                             "  vier ",          4)>]
[<InlineData(                                                                "fünf",          5)>]
[<InlineData(                                                                "FünF",          5)>]
[<InlineData(                                                               "sechs",          6)>]
[<InlineData(                                                           "  SECHS  ",          6)>]
[<InlineData(                                                              "sieben",          7)>]
[<InlineData(                                                          "    sieBen",          7)>]
[<InlineData(                                                                "acht",          8)>]
[<InlineData(                                                                "aCHT",          8)>]
[<InlineData(                                                                "neun",          9)>]
[<InlineData(                                                              "NeUn  ",          9)>]
[<InlineData(                                                                "zehn",         10)>]
[<InlineData(                                                                 "elf",         11)>]
[<InlineData(                                                               "zwölf",         12)>]
[<InlineData(                                                            "dreizehn",         13)>]
[<InlineData(                                                            "vierzehn",         14)>]
[<InlineData(                                                            "fünfzehn",         15)>]
[<InlineData(                                                            "sechzehn",         16)>]
[<InlineData(                                                          "siebenzehn",         17)>]
[<InlineData(                                                            "achtzehn",         18)>]
[<InlineData(                                                            "neunzehn",         19)>]
[<InlineData(                                                             "zwanzig",         20)>]
[<InlineData(                                                     "ein und zwanzig",         21)>]
[<InlineData(                                                       "einundzwanzig",         21)>]
[<InlineData(                                                             "dreißig",         30)>]
[<InlineData(                                                      "vierunddreißig",         34)>]
[<InlineData(                                                    "acht und dreißig",         38)>]
[<InlineData(                                                             "vierzig",         40)>]
[<InlineData(                                                     "ein-und-vierzig",         41)>]
[<InlineData(                                                      "vierundvierzig",         44)>]
[<InlineData(                                                             "fünfzig",         50)>]
[<InlineData(                                                    "siebenundfünfzig",         57)>]
[<InlineData(                                                             "sechzig",         60)>]
[<InlineData(                                                      "fünfundsechzig",         65)>]
[<InlineData(                                                             "siebzig",         70)>]
[<InlineData(                                                  "sieben und siebzig",         77)>]
[<InlineData(                                                    "neun und siebzig",         79)>]
[<InlineData(                                                             "achtzig",         80)>]
[<InlineData(                                                     "sechsundachtzig",         86)>]
[<InlineData(                                                             "neunzig",         90)>]
[<InlineData(                                                    "drei-und-neunzig",         93)>]
[<InlineData(                                                             "hundert",        100)>]
[<InlineData(                                                          "einhundert",        100)>]
[<InlineData(                                                         "hunderteins",        101)>]
[<InlineData(                                                      "hundertundeins",        101)>]
[<InlineData(                                                    "hundert-und-eins",        101)>]
[<InlineData(                                                      "einhunderteins",        101)>]
[<InlineData(                                                   "einhundertundeins",        101)>]
[<InlineData(                                                "ein-hundert-und-eins",        101)>]
[<InlineData(                                                         "zweihundert",        200)>]
[<InlineData(                                         "zweihundertsiebenunddreißig",        237)>]
[<InlineData(                                           "dreihundertfünfundsiebzig",        375)>]
[<InlineData(                                                  "vierhundertneunzig",        490)>]
[<InlineData(                                           "fünfhundertdreiundsechzig",        563)>]
[<InlineData(                                                "sechshundertachtzehn",        618)>]
[<InlineData(                                       "siebenhundertsiebenundsiebzig",        777)>]
[<InlineData(                                                     "achthundertfünf",        805)>]
[<InlineData(                                                 "achthundertundsechs",        806)>]
[<InlineData(                                             "acht-hundert-und-sieben",        807)>]
[<InlineData(                                           "neunhundertneunundfünfzig",        959)>]
[<InlineData(                                                             "tausend",       1000)>]
[<InlineData(                                                          "eintausend",       1000)>]
[<InlineData(                                                         "tausendeins",       1001)>]
[<InlineData(                                                      "eintausendzwei",       1002)>]
[<InlineData(                                            "eintausendvierundsechzig",       1064)>]
[<InlineData(                                                         "zweitausend",       2000)>]
[<InlineData(                               "achttausendsiebenhunderteinundzwanzig",       8721)>]
[<InlineData(                           "neun-tausend-ein-hundert-drei-und-zwanzig",       9123)>]
[<InlineData(                                                         "zehntausend",      10000)>]
[<InlineData(                                           "zehntausendeinhunderteins",      10101)>]
[<InlineData(                                   "zehn-tausend-ein-hundert-und-zwei",      10102)>]
[<InlineData(                      "dreiundzwanzigtausendfünfhundertvierundsechzig",      23564)>]
[<InlineData(                                                  "achtzigtausendzehn",      80010)>]
[<InlineData(                                                      "hunderttausend",     100000)>]
[<InlineData(                                                   "einhunderttausend",     100000)>]
[<InlineData(                                            "einhunderttausendundeins",     100001)>]
[<InlineData(                 "dreihundertneunzehntausenddreihundertneunundvierzig",     319349)>]
[<InlineData(                                                         "einemillion",    1000000)>]
[<InlineData(                                                     "einemillioneins",    1000001)>]
[<InlineData(                                                  "einemillionundeins",    1000001)>]
[<InlineData(                                                   "zweimillionenzehn",    2000010)>]
[<InlineData(                                        "sechsmillionendreißigtausend",    6030000)>]
[<InlineData(              "neunmillionenzweihunderteinstausendsechshundertachtzig",    9201680)>]
[<InlineData(                                                       "zehnmillionen",   10000000)>]
[<InlineData(                                                   "zehnmillionenneun",   10000009)>]
[<InlineData(                                              "einundzwanzigmillionen",   21000000)>]
[<InlineData( "siebenundvierzigmillionensechshunderteinundsechzigtausendundsechzig",   47661060)>]
[<InlineData(                                                    "hundertmillionen",  100000000)>]
[<InlineData(                                                 "einhundertmillionen",  100000000)>]
[<InlineData(                                            "zweihundertfünfmillionen",  205000000)>]
[<InlineData(                                   "drei-hundert-und-sieben-millionen",  307000000)>]
[<InlineData(         "vierhunderteinundsechzigmillionensechzigtausendsechshundert",  461060600)>]
[<InlineData(                                                       "einemilliarde", 1000000000)>]
[<InlineData(                                                      "zweimilliarden", 2000000000)>]
let ``tryOfGerman returns correct result`` (german, expected) =
    let actual = Numeral.tryParseGerman german
    Some expected =! actual

[<Theory>]
[<InlineData(                                                         "minus null",          -0)>]
[<InlineData(                                                        "minus  null",          -0)>]
[<InlineData(                                                        "minus null ",          -0)>]
[<InlineData(                                                     "minus   null  ",          -0)>]
[<InlineData(                                                         "minus Null",          -0)>]
[<InlineData(                                                         "minus NULL",          -0)>]
[<InlineData(                                                      "minus  nULL\t",          -0)>]
[<InlineData(                                                         "minus eins",          -1)>]
[<InlineData(                                                         "minus zwei",          -2)>]
[<InlineData(                                                        "minus  zwei",          -2)>]
[<InlineData(                                                         "minus drei",          -3)>]
[<InlineData(                                                       "minus drei  ",          -3)>]
[<InlineData(                                                         "minus vier",          -4)>]
[<InlineData(                                                      "minus   vier ",          -4)>]
[<InlineData(                                                         "minus fünf",          -5)>]
[<InlineData(                                                         "minus FünF",          -5)>]
[<InlineData(                                                        "minus sechs",          -6)>]
[<InlineData(                                                    "minus   SECHS  ",          -6)>]
[<InlineData(                                                       "minus sieben",          -7)>]
[<InlineData(                                                   "minus     sieBen",          -7)>]
[<InlineData(                                                         "minus acht",          -8)>]
[<InlineData(                                                         "minus aCHT",          -8)>]
[<InlineData(                                                         "minus neun",          -9)>]
[<InlineData(                                                       "minus NeUn  ",          -9)>]
[<InlineData(                                                         "minus zehn",         -10)>]
[<InlineData(                                                          "minus elf",         -11)>]
[<InlineData(                                                        "minus zwölf",         -12)>]
[<InlineData(                                                     "minus dreizehn",         -13)>]
[<InlineData(                                                     "minus vierzehn",         -14)>]
[<InlineData(                                                     "minus fünfzehn",         -15)>]
[<InlineData(                                                     "minus sechzehn",         -16)>]
[<InlineData(                                                   "minus siebenzehn",         -17)>]
[<InlineData(                                                     "minus achtzehn",         -18)>]
[<InlineData(                                                     "minus neunzehn",         -19)>]
[<InlineData(                                                      "minus zwanzig",         -20)>]
[<InlineData(                                              "minus ein und zwanzig",         -21)>]
[<InlineData(                                                "minus einundzwanzig",         -21)>]
[<InlineData(                                                      "minus dreißig",         -30)>]
[<InlineData(                                               "minus vierunddreißig",         -34)>]
[<InlineData(                                             "minus acht und dreißig",         -38)>]
[<InlineData(                                                      "minus vierzig",         -40)>]
[<InlineData(                                              "minus ein-und-vierzig",         -41)>]
[<InlineData(                                               "minus vierundvierzig",         -44)>]
[<InlineData(                                                      "minus fünfzig",         -50)>]
[<InlineData(                                             "minus siebenundfünfzig",         -57)>]
[<InlineData(                                                      "minus sechzig",         -60)>]
[<InlineData(                                               "minus fünfundsechzig",         -65)>]
[<InlineData(                                                      "minus siebzig",         -70)>]
[<InlineData(                                           "minus sieben und siebzig",         -77)>]
[<InlineData(                                             "minus neun und siebzig",         -79)>]
[<InlineData(                                                      "minus achtzig",         -80)>]
[<InlineData(                                              "minus sechsundachtzig",         -86)>]
[<InlineData(                                                      "minus neunzig",         -90)>]
[<InlineData(                                             "minus drei-und-neunzig",         -93)>]
[<InlineData(                                                      "minus hundert",        -100)>]
[<InlineData(                                                   "minus einhundert",        -100)>]
[<InlineData(                                                  "minus hunderteins",        -101)>]
[<InlineData(                                               "minus hundertundeins",        -101)>]
[<InlineData(                                             "minus hundert-und-eins",        -101)>]
[<InlineData(                                               "minus einhunderteins",        -101)>]
[<InlineData(                                            "minus einhundertundeins",        -101)>]
[<InlineData(                                         "minus ein-hundert-und-eins",        -101)>]
[<InlineData(                                                  "minus zweihundert",        -200)>]
[<InlineData(                                  "minus zweihundertsiebenunddreißig",        -237)>]
[<InlineData(                                    "minus dreihundertfünfundsiebzig",        -375)>]
[<InlineData(                                           "minus vierhundertneunzig",        -490)>]
[<InlineData(                                    "minus fünfhundertdreiundsechzig",        -563)>]
[<InlineData(                                         "minus sechshundertachtzehn",        -618)>]
[<InlineData(                                "minus siebenhundertsiebenundsiebzig",        -777)>]
[<InlineData(                                              "minus achthundertfünf",        -805)>]
[<InlineData(                                          "minus achthundertundsechs",        -806)>]
[<InlineData(                                      "minus acht-hundert-und-sieben",        -807)>]
[<InlineData(                                    "minus neunhundertneunundfünfzig",        -959)>]
[<InlineData(                                                      "minus tausend",       -1000)>]
[<InlineData(                                                   "minus eintausend",       -1000)>]
[<InlineData(                                                  "minus tausendeins",       -1001)>]
[<InlineData(                                               "minus eintausendzwei",       -1002)>]
[<InlineData(                                     "minus eintausendvierundsechzig",       -1064)>]
[<InlineData(                                                  "minus zweitausend",       -2000)>]
[<InlineData(                        "minus achttausendsiebenhunderteinundzwanzig",       -8721)>]
[<InlineData(                    "minus neun-tausend-ein-hundert-drei-und-zwanzig",       -9123)>]
[<InlineData(                                                  "minus zehntausend",      -10000)>]
[<InlineData(                                    "minus zehntausendeinhunderteins",      -10101)>]
[<InlineData(                            "minus zehn-tausend-ein-hundert-und-zwei",      -10102)>]
[<InlineData(               "minus dreiundzwanzigtausendfünfhundertvierundsechzig",      -23564)>]
[<InlineData(                                           "minus achtzigtausendzehn",      -80010)>]
[<InlineData(                                               "minus hunderttausend",     -100000)>]
[<InlineData(                                            "minus einhunderttausend",     -100000)>]
[<InlineData(                                     "minus einhunderttausendundeins",     -100001)>]
[<InlineData(          "minus dreihundertneunzehntausenddreihundertneunundvierzig",     -319349)>]
[<InlineData(                                                  "minus einemillion",    -1000000)>]
[<InlineData(                                              "minus einemillioneins",    -1000001)>]
[<InlineData(                                           "minus einemillionundeins",    -1000001)>]
[<InlineData(                                            "minus zweimillionenzehn",    -2000010)>]
[<InlineData(                                 "minus sechsmillionendreißigtausend",    -6030000)>]
[<InlineData(       "minus neunmillionenzweihunderteinstausendsechshundertachtzig",    -9201680)>]
[<InlineData(                                                "minus zehnmillionen",   -10000000)>]
[<InlineData(                                            "minus zehnmillionenneun",   -10000009)>]
[<InlineData(                                       "minus einundzwanzigmillionen",   -21000000)>]
[<InlineData("minussiebenundvierzigmillionensechshunderteinundsechzigtausendundsechzig",   -47661060)>]
[<InlineData(                                             "minus hundertmillionen",  -100000000)>]
[<InlineData(                                          "minus einhundertmillionen",  -100000000)>]
[<InlineData(                                     "minus zweihundertfünfmillionen",  -205000000)>]
[<InlineData(                            "minus drei-hundert-und-sieben-millionen",  -307000000)>]
[<InlineData(  "minus vierhunderteinundsechzigmillionensechzigtausendsechshundert",  -461060600)>]
[<InlineData(                                                "minus einemilliarde", -1000000000)>]
[<InlineData(                                               "minus zweimilliarden", -2000000000)>]
let ``tryOfGerman returns correct negative result`` (german, expected) =
    let actual = Numeral.tryParseGerman german
    Some expected =! actual

[<Theory>]
[<InlineData(         0, "null")>]
[<InlineData(         1, "eins")>]
[<InlineData(         2, "zwei")>]
[<InlineData(         3, "drei")>]
[<InlineData(         4, "vier")>]
[<InlineData(         5, "fünf")>]
[<InlineData(         6, "sechs")>]
[<InlineData(         7, "sieben")>]
[<InlineData(         8, "acht")>]
[<InlineData(         9, "neun")>]
[<InlineData(        10, "zehn")>]
[<InlineData(        11, "elf")>]
[<InlineData(        12, "zwölf")>]
[<InlineData(        13, "dreizehn")>]
[<InlineData(        14, "vierzehn")>]
[<InlineData(        15, "fünfzehn")>]
[<InlineData(        16, "sechzehn")>]
[<InlineData(        17, "siebzehn")>]
[<InlineData(        18, "achtzehn")>]
[<InlineData(        19, "neunzehn")>]
[<InlineData(        20, "zwanzig")>]
[<InlineData(        21, "ein-und-zwanzig")>]
[<InlineData(        30, "dreißig")>]
[<InlineData(        34, "vier-und-dreißig")>]
[<InlineData(        40, "vierzig")>]
[<InlineData(        42, "zwei-und-vierzig")>]
[<InlineData(        50, "fünfzig")>]
[<InlineData(        58, "acht-und-fünfzig")>]
[<InlineData(        60, "sechzig")>]
[<InlineData(        65, "fünf-und-sechzig")>]
[<InlineData(        70, "siebzig")>]
[<InlineData(        79, "neun-und-siebzig")>]
[<InlineData(        80, "achtzig")>]
[<InlineData(        86, "sechs-und-achtzig")>]
[<InlineData(        90, "neunzig")>]
[<InlineData(        93, "drei-und-neunzig")>]
[<InlineData(       100, "ein-hundert")>]
[<InlineData(       101, "ein-hundert-eins")>]
[<InlineData(       110, "ein-hundert-zehn")>]
[<InlineData(       114, "ein-hundert-vierzehn")>]
[<InlineData(       135, "ein-hundert-fünf-und-dreißig")>]
[<InlineData(       200, "zwei-hundert")>]
[<InlineData(       282, "zwei-hundert-zwei-und-achtzig")>]
[<InlineData(       331, "drei-hundert-ein-und-dreißig")>]
[<InlineData(       407, "vier-hundert-sieben")>]
[<InlineData(       520, "fünf-hundert-zwanzig")>]
[<InlineData(       666, "sechs-hundert-sechs-und-sechzig")>]
[<InlineData(       798, "sieben-hundert-acht-und-neunzig")>]
[<InlineData(       857, "acht-hundert-sieben-und-fünfzig")>]
[<InlineData(       999, "neun-hundert-neun-und-neunzig")>]
[<InlineData(      1000, "ein-tausend")>]
[<InlineData(      1001, "ein-tausend-eins")>]
[<InlineData(      1010, "ein-tausend-zehn")>]
[<InlineData(      1066, "ein-tausend-sechs-und-sechzig")>]
[<InlineData(      1337, "ein-tausend-drei-hundert-sieben-und-dreißig")>]
[<InlineData(      1984, "ein-tausend-neun-hundert-vier-und-achtzig")>]
[<InlineData(      2015, "zwei-tausend-fünfzehn")>]
[<InlineData(      3000, "drei-tausend")>]
[<InlineData(      3297, "drei-tausend-zwei-hundert-sieben-und-neunzig")>]
[<InlineData(      4080, "vier-tausend-achtzig")>]
[<InlineData(      5011, "fünf-tausend-elf")>]
[<InlineData(      6025, "sechs-tausend-fünf-und-zwanzig")>]
[<InlineData(      7441, "sieben-tausend-vier-hundert-ein-und-vierzig")>]
[<InlineData(      8513, "acht-tausend-fünf-hundert-dreizehn")>]
[<InlineData(      9000, "neun-tausend")>]
[<InlineData(     10000, "zehn-tausend")>]
[<InlineData(     12001, "zwölf-tausend-eins")>]
[<InlineData(     23456, "drei-und-zwanzig-tausend-vier-hundert-sechs-und-fünfzig")>]
[<InlineData(     32109, "zwei-und-dreißig-tausend-ein-hundert-neun")>]
[<InlineData(     40404, "vierzig-tausend-vier-hundert-vier")>]
[<InlineData(     56789, "sechs-und-fünfzig-tausend-sieben-hundert-neun-und-achtzig")>]
[<InlineData(     60015, "sechzig-tausend-fünfzehn")>]
[<InlineData(     71003, "ein-und-siebzig-tausend-drei")>]
[<InlineData(     80522, "achtzig-tausend-fünf-hundert-zwei-und-zwanzig")>]
[<InlineData(     98765, "acht-und-neunzig-tausend-sieben-hundert-fünf-und-sechzig")>]
[<InlineData(    100000, "ein-hundert-tausend")>]
[<InlineData(    100001, "ein-hundert-tausend-eins")>]
[<InlineData(    100010, "ein-hundert-tausend-zehn")>]
[<InlineData(    101010, "ein-hundert-eins-tausend-zehn")>]
[<InlineData(    200000, "zwei-hundert-tausend")>]
[<InlineData(    321000, "drei-hundert-ein-und-zwanzig-tausend")>]
[<InlineData(    411416, "vier-hundert-elf-tausend-vier-hundert-sechzehn")>]
[<InlineData(    530121, "fünf-hundert-dreißig-tausend-ein-hundert-ein-und-zwanzig")>]
[<InlineData(    600000, "sechs-hundert-tausend")>]
[<InlineData(    788000, "sieben-hundert-acht-und-achtzig-tausend")>]
[<InlineData(    876540, "acht-hundert-sechs-und-siebzig-tausend-fünf-hundert-vierzig")>]
[<InlineData(    908077, "neun-hundert-acht-tausend-sieben-und-siebzig")>]
[<InlineData(   1000000, "eine-million")>]
[<InlineData(   2000002, "zwei-millionen-zwei")>]
[<InlineData(   3040506, "drei-millionen-vierzig-tausend-fünf-hundert-sechs")>]
[<InlineData(   4321000, "vier-millionen-drei-hundert-ein-und-zwanzig-tausend")>]
[<InlineData(   5004621, "fünf-millionen-vier-tausend-sechs-hundert-ein-und-zwanzig")>]
[<InlineData(   6982001, "sechs-millionen-neun-hundert-zwei-und-achtzig-tausend-eins")>]
[<InlineData(   7000000, "sieben-millionen")>]
[<InlineData(   8000220, "acht-millionen-zwei-hundert-zwanzig")>]
[<InlineData(   9099000, "neun-millionen-neun-und-neunzig-tausend")>]
[<InlineData(  10000000, "zehn-millionen")>]
[<InlineData(  24000000, "vier-und-zwanzig-millionen")>]
[<InlineData(  39020011, "neun-und-dreißig-millionen-zwanzig-tausend-elf")>]
[<InlineData(  40606100, "vierzig-millionen-sechs-hundert-sechs-tausend-ein-hundert")>]
[<InlineData(  53000000, "drei-und-fünfzig-millionen")>]
[<InlineData(  64000098, "vier-und-sechzig-millionen-acht-und-neunzig")>]
[<InlineData(  70003190, "siebzig-millionen-drei-tausend-ein-hundert-neunzig")>]
[<InlineData(  80000000, "achtzig-millionen")>]
[<InlineData(  99000099, "neun-und-neunzig-millionen-neun-und-neunzig")>]
[<InlineData( 100000000, "ein-hundert-millionen")>]
[<InlineData( 209000000, "zwei-hundert-neun-millionen")>]
[<InlineData( 398000000, "drei-hundert-acht-und-neunzig-millionen")>]
[<InlineData( 439011000, "vier-hundert-neun-und-dreißig-millionen-elf-tausend")>]
[<InlineData( 560400000, "fünf-hundert-sechzig-millionen-vier-hundert-tausend")>]
[<InlineData( 600010900, "sechs-hundert-millionen-zehn-tausend-neun-hundert")>]
[<InlineData( 700000000, "sieben-hundert-millionen")>]
[<InlineData( 800116000, "acht-hundert-millionen-ein-hundert-sechzehn-tausend")>]
[<InlineData( 900800007, "neun-hundert-millionen-acht-hundert-tausend-sieben")>]
[<InlineData(1000000000, "eine-milliarde")>]
let ``toGerman returns correct result`` (i, expected) =
    let actual = Numeral.toGerman i
    expected =! actual

[<Theory>]
[<InlineData(          0, "null")>]
[<InlineData(         -1, "minus-eins")>]
[<InlineData(         -2, "minus-zwei")>]
[<InlineData(         -3, "minus-drei")>]
[<InlineData(         -4, "minus-vier")>]
[<InlineData(         -5, "minus-fünf")>]
[<InlineData(         -6, "minus-sechs")>]
[<InlineData(         -7, "minus-sieben")>]
[<InlineData(         -8, "minus-acht")>]
[<InlineData(         -9, "minus-neun")>]
[<InlineData(        -10, "minus-zehn")>]
[<InlineData(        -11, "minus-elf")>]
[<InlineData(        -12, "minus-zwölf")>]
[<InlineData(        -13, "minus-dreizehn")>]
[<InlineData(        -14, "minus-vierzehn")>]
[<InlineData(        -15, "minus-fünfzehn")>]
[<InlineData(        -16, "minus-sechzehn")>]
[<InlineData(        -17, "minus-siebzehn")>]
[<InlineData(        -18, "minus-achtzehn")>]
[<InlineData(        -19, "minus-neunzehn")>]
[<InlineData(        -20, "minus-zwanzig")>]
[<InlineData(        -21, "minus-ein-und-zwanzig")>]
[<InlineData(        -30, "minus-dreißig")>]
[<InlineData(        -34, "minus-vier-und-dreißig")>]
[<InlineData(        -40, "minus-vierzig")>]
[<InlineData(        -42, "minus-zwei-und-vierzig")>]
[<InlineData(        -50, "minus-fünfzig")>]
[<InlineData(        -58, "minus-acht-und-fünfzig")>]
[<InlineData(        -60, "minus-sechzig")>]
[<InlineData(        -65, "minus-fünf-und-sechzig")>]
[<InlineData(        -70, "minus-siebzig")>]
[<InlineData(        -79, "minus-neun-und-siebzig")>]
[<InlineData(        -80, "minus-achtzig")>]
[<InlineData(        -86, "minus-sechs-und-achtzig")>]
[<InlineData(        -90, "minus-neunzig")>]
[<InlineData(        -93, "minus-drei-und-neunzig")>]
[<InlineData(       -100, "minus-ein-hundert")>]
[<InlineData(       -101, "minus-ein-hundert-eins")>]
[<InlineData(       -110, "minus-ein-hundert-zehn")>]
[<InlineData(       -114, "minus-ein-hundert-vierzehn")>]
[<InlineData(       -135, "minus-ein-hundert-fünf-und-dreißig")>]
[<InlineData(       -200, "minus-zwei-hundert")>]
[<InlineData(       -282, "minus-zwei-hundert-zwei-und-achtzig")>]
[<InlineData(       -331, "minus-drei-hundert-ein-und-dreißig")>]
[<InlineData(       -407, "minus-vier-hundert-sieben")>]
[<InlineData(       -520, "minus-fünf-hundert-zwanzig")>]
[<InlineData(       -666, "minus-sechs-hundert-sechs-und-sechzig")>]
[<InlineData(       -798, "minus-sieben-hundert-acht-und-neunzig")>]
[<InlineData(       -857, "minus-acht-hundert-sieben-und-fünfzig")>]
[<InlineData(       -999, "minus-neun-hundert-neun-und-neunzig")>]
[<InlineData(      -1000, "minus-ein-tausend")>]
[<InlineData(      -1001, "minus-ein-tausend-eins")>]
[<InlineData(      -1010, "minus-ein-tausend-zehn")>]
[<InlineData(      -1066, "minus-ein-tausend-sechs-und-sechzig")>]
[<InlineData(      -1337, "minus-ein-tausend-drei-hundert-sieben-und-dreißig")>]
[<InlineData(      -1984, "minus-ein-tausend-neun-hundert-vier-und-achtzig")>]
[<InlineData(      -2015, "minus-zwei-tausend-fünfzehn")>]
[<InlineData(      -3000, "minus-drei-tausend")>]
[<InlineData(      -3297, "minus-drei-tausend-zwei-hundert-sieben-und-neunzig")>]
[<InlineData(      -4080, "minus-vier-tausend-achtzig")>]
[<InlineData(      -5011, "minus-fünf-tausend-elf")>]
[<InlineData(      -6025, "minus-sechs-tausend-fünf-und-zwanzig")>]
[<InlineData(      -7441, "minus-sieben-tausend-vier-hundert-ein-und-vierzig")>]
[<InlineData(      -8513, "minus-acht-tausend-fünf-hundert-dreizehn")>]
[<InlineData(      -9000, "minus-neun-tausend")>]
[<InlineData(     -10000, "minus-zehn-tausend")>]
[<InlineData(     -12001, "minus-zwölf-tausend-eins")>]
[<InlineData(     -23456, "minus-drei-und-zwanzig-tausend-vier-hundert-sechs-und-fünfzig")>]
[<InlineData(     -32109, "minus-zwei-und-dreißig-tausend-ein-hundert-neun")>]
[<InlineData(     -40404, "minus-vierzig-tausend-vier-hundert-vier")>]
[<InlineData(     -56789, "minus-sechs-und-fünfzig-tausend-sieben-hundert-neun-und-achtzig")>]
[<InlineData(     -60015, "minus-sechzig-tausend-fünfzehn")>]
[<InlineData(     -71003, "minus-ein-und-siebzig-tausend-drei")>]
[<InlineData(     -80522, "minus-achtzig-tausend-fünf-hundert-zwei-und-zwanzig")>]
[<InlineData(     -98765, "minus-acht-und-neunzig-tausend-sieben-hundert-fünf-und-sechzig")>]
[<InlineData(    -100000, "minus-ein-hundert-tausend")>]
[<InlineData(    -100001, "minus-ein-hundert-tausend-eins")>]
[<InlineData(    -100010, "minus-ein-hundert-tausend-zehn")>]
[<InlineData(    -101010, "minus-ein-hundert-eins-tausend-zehn")>]
[<InlineData(    -200000, "minus-zwei-hundert-tausend")>]
[<InlineData(    -321000, "minus-drei-hundert-ein-und-zwanzig-tausend")>]
[<InlineData(    -411416, "minus-vier-hundert-elf-tausend-vier-hundert-sechzehn")>]
[<InlineData(    -530121, "minus-fünf-hundert-dreißig-tausend-ein-hundert-ein-und-zwanzig")>]
[<InlineData(    -600000, "minus-sechs-hundert-tausend")>]
[<InlineData(    -788000, "minus-sieben-hundert-acht-und-achtzig-tausend")>]
[<InlineData(    -876540, "minus-acht-hundert-sechs-und-siebzig-tausend-fünf-hundert-vierzig")>]
[<InlineData(    -908077, "minus-neun-hundert-acht-tausend-sieben-und-siebzig")>]
[<InlineData(   -1000000, "minus-eine-million")>]
[<InlineData(   -2000002, "minus-zwei-millionen-zwei")>]
[<InlineData(   -3040506, "minus-drei-millionen-vierzig-tausend-fünf-hundert-sechs")>]
[<InlineData(   -4321000, "minus-vier-millionen-drei-hundert-ein-und-zwanzig-tausend")>]
[<InlineData(   -5004621, "minus-fünf-millionen-vier-tausend-sechs-hundert-ein-und-zwanzig")>]
[<InlineData(   -6982001, "minus-sechs-millionen-neun-hundert-zwei-und-achtzig-tausend-eins")>]
[<InlineData(   -7000000, "minus-sieben-millionen")>]
[<InlineData(   -8000220, "minus-acht-millionen-zwei-hundert-zwanzig")>]
[<InlineData(   -9099000, "minus-neun-millionen-neun-und-neunzig-tausend")>]
[<InlineData(  -10000000, "minus-zehn-millionen")>]
[<InlineData(  -24000000, "minus-vier-und-zwanzig-millionen")>]
[<InlineData(  -39020011, "minus-neun-und-dreißig-millionen-zwanzig-tausend-elf")>]
[<InlineData(  -40606100, "minus-vierzig-millionen-sechs-hundert-sechs-tausend-ein-hundert")>]
[<InlineData(  -53000000, "minus-drei-und-fünfzig-millionen")>]
[<InlineData(  -64000098, "minus-vier-und-sechzig-millionen-acht-und-neunzig")>]
[<InlineData(  -70003190, "minus-siebzig-millionen-drei-tausend-ein-hundert-neunzig")>]
[<InlineData(  -80000000, "minus-achtzig-millionen")>]
[<InlineData(  -99000099, "minus-neun-und-neunzig-millionen-neun-und-neunzig")>]
[<InlineData( -100000000, "minus-ein-hundert-millionen")>]
[<InlineData( -209000000, "minus-zwei-hundert-neun-millionen")>]
[<InlineData( -398000000, "minus-drei-hundert-acht-und-neunzig-millionen")>]
[<InlineData( -439011000, "minus-vier-hundert-neun-und-dreißig-millionen-elf-tausend")>]
[<InlineData( -560400000, "minus-fünf-hundert-sechzig-millionen-vier-hundert-tausend")>]
[<InlineData( -600010900, "minus-sechs-hundert-millionen-zehn-tausend-neun-hundert")>]
[<InlineData( -700000000, "minus-sieben-hundert-millionen")>]
[<InlineData( -800116000, "minus-acht-hundert-millionen-ein-hundert-sechzehn-tausend")>]
[<InlineData( -900800007, "minus-neun-hundert-millionen-acht-hundert-tausend-sieben")>]
[<InlineData(-1000000000, "minus-eine-milliarde")>]
let ``toGerman returns correct negativ result`` (i, expected) =
    let actual = Numeral.toGerman i
    expected =! actual
