module Ploeh.Numsense.LithuanianExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData("nulis", 0)>]
[<InlineData(" nulis", 0)>]
[<InlineData("nulis ", 0)>]
[<InlineData("  nulis  ", 0)>]
[<InlineData("Nulis", 0)>]
[<InlineData("NULIS", 0)>]
[<InlineData(" nULIs\t", 0)>]
[<InlineData("vienas", 1)>]
[<InlineData("VIENAS", 1)>]
[<InlineData("VIENA", 1)>]
[<InlineData("viENa", 1)>]
[<InlineData("du", 2)>]
[<InlineData(" du", 2)>]
[<InlineData(" dvi", 2)>]
[<InlineData("Dvi", 2)>]
[<InlineData("trys", 3)>]
[<InlineData("trys  ", 3)>]
[<InlineData("keturi", 4)>]
[<InlineData("  keturi ", 4)>]
[<InlineData("  keturios ", 4)>]
[<InlineData("penki", 5)>]
[<InlineData("PenkI", 5)>]
[<InlineData("PenKios", 5)>]
[<InlineData("šeši", 6)>]
[<InlineData("  ŠEŠI  ", 6)>]
[<InlineData("šešios", 6)>]
[<InlineData("septyni", 7)>]
[<InlineData("    sepTyni", 7)>]
[<InlineData("septynios", 7)>]
[<InlineData("aštuoni", 8)>]
[<InlineData("ašTUONI", 8)>]
[<InlineData("aštuonios", 8)>]
[<InlineData("devyni", 9)>]
[<InlineData("devyni  ", 9)>]
[<InlineData("devynios", 9)>]
[<InlineData("dešimt", 10)>]
[<InlineData("vienuolika", 11)>]
[<InlineData("dvylika", 12)>]
[<InlineData("trylika", 13)>]
[<InlineData("keturiolika", 14)>]
[<InlineData("penkiolika", 15)>]
[<InlineData("šešiolika", 16)>]
[<InlineData("septyniolika", 17)>]
[<InlineData("aštuoniolika", 18)>]
[<InlineData("devyniolika", 19)>]
[<InlineData("dvidešimt", 20)>]
[<InlineData("dvidešimtvienas", 21)>]
[<InlineData("dvidešimtdvi", 22)>]
[<InlineData("dvidešimt-vienas", 21)>]
[<InlineData("trisdešimt", 30)>]
[<InlineData("trisdešimtketuri", 34)>]
[<InlineData("trisdešimtketurios", 34)>]
[<InlineData("trisdešimt-aštuoni", 38)>]
[<InlineData("keturiasdešimt", 40)>]
[<InlineData("keturiasdešimt-vienas", 41)>]
[<InlineData("keturiasdešimt-viena", 41)>]
[<InlineData("keturiasdešimtketuri", 44)>]
[<InlineData("penkiasdešimt", 50)>]
[<InlineData("penkiasdešimtseptyni", 57)>]
[<InlineData("penkiasdešimtseptynios", 57)>]
[<InlineData("šešiasdešimt", 60)>]
[<InlineData("šešiasdešimtpenki", 65)>]
[<InlineData("šešiasdešimtpenkios", 65)>]
[<InlineData("septyniasdešimt", 70)>]
[<InlineData("septyniasdešimt-septyni", 77)>]
[<InlineData("septyniasdešimt-septynios", 77)>]
[<InlineData("septyniasdešimtdevyni", 79)>]
[<InlineData("septyniasdešimtdevynios", 79)>]
[<InlineData("aštuoniasdešimt", 80)>]
[<InlineData("aštuoniasdešimtšeši", 86)>]
[<InlineData("aštuoniasdešimtšešios", 86)>]
[<InlineData("devyniasdešimt", 90)>]
[<InlineData("devyniasdešimttrys", 93)>]
[<InlineData("šimtas", 100)>]
[<InlineData("vienasšimtas", 100)>]
[<InlineData("šimtasvienas", 101)>]
[<InlineData("šimtas-vienas", 101)>]
[<InlineData("šimtasviena", 101)>]
[<InlineData("vienasšimtasirvienas", 101)>]
[<InlineData("vienasšimtasirviena", 101)>]
[<InlineData("šimtas-ir-vienas", 101)>]
[<InlineData("dušimtai", 200)>]
[<InlineData("dušimtaitrisdešimtseptyni", 237)>]
[<InlineData("trysšimtaiseptyniasdešimtpenki", 375)>]
[<InlineData("keturišimtaidevyniasdešimt", 490)>]
[<InlineData("penkišimtaišešiasdešimttrys", 563)>]
[<InlineData("šešišimtaiaštuoniolika", 618)>]
[<InlineData("septynišimtaiseptyniasdešimtseptyni", 777)>]
[<InlineData("septynišimtaiseptyniasdešimtseptynios", 777)>]
[<InlineData("aštuonišimtaipenki", 805)>]
[<InlineData("aštuonišimtaiiršeši", 806)>]
[<InlineData("aštuoni-šimtai-ir-septyni", 807)>]
[<InlineData("devynišimtaipenkiasdešimtdevyni", 959)>]
[<InlineData("tūkstantis", 1000)>]
[<InlineData("vienastūkstantis", 1000)>]
[<InlineData("tūkstantisvienas", 1001)>]
[<InlineData("tūkstantis-irviena", 1001)>]
[<InlineData("vienastūkstantisdu", 1002)>]
[<InlineData("vienastūkstantisdvi", 1002)>]
[<InlineData("vienastūkstantisšešiasdešimtketuri", 1064)>]
[<InlineData("dutūkstančiai", 2000)>]
[<InlineData("aštuonitūkstančiaiseptynišimtaidvidešimtvienas", 8721)>]
[<InlineData("devyni-tūkstančiai-šimtas-dvidešimt-trys", 9123)>]
[<InlineData("dešimttūkstančių", 10000)>]
[<InlineData("dešimttūkstančiųvienasšimtasvienas", 10101)>]
[<InlineData("dešimt-tūkstančių-šimtas-du", 10102)>]
[<InlineData("dvidešimttrystūkstančiaipenkišimtaišešiasdešimtketuri", 23564)>]
[<InlineData("aštuoniasdešimttūkstančiųdešimt", 80010)>]
[<InlineData("šimtastūkstančių", 100000)>]
[<InlineData("vienasšimtastūkstančių", 100000)>]
[<InlineData("šimtastūkstančiųvienas", 100001)>]
[<InlineData("trysšimtaidevyniolikatūkstančiųtrysšimtaiketuriasdešimtdevyni", 319349)>]
[<InlineData("trysšimtaidevyniolikatūkstančiųtrysšimtaiketuriasdešimtdevynios", 319349)>]
[<InlineData("vienasmilijonas", 1000000)>]
[<InlineData("milijonasvienas", 1000001)>]
[<InlineData("dumilijonaidešimt", 2000010)>]
[<InlineData("šešimilijonaitrisdešimttūkstančių", 6030000)>]
[<InlineData("devynimilijonaidušimtaivienastūkstantisšešišimtaiaštuoniasdešimt", 9201680)>]
[<InlineData("dešimtmilijonų", 10000000)>]
[<InlineData("dešimtmilijonųdevyni", 10000009)>]
[<InlineData("dvidešimtvienasmilijonas", 21000000)>]
[<InlineData("keturiasdešimtseptynimilijonaišešišimtaišešiasdešimtvienastūkstantisšešiasdešimt", 47661060)>]
[<InlineData("šimtasmilijonų", 100000000)>]
[<InlineData("vienasšimtasmilijonų", 100000000)>]
[<InlineData("dušimtaipenkimilijonai", 205000000)>]
[<InlineData("trys-šimtai-ir-septyni-milijonai", 307000000)>]
[<InlineData("keturišimtaišešiasdešimtvienasmilijonasšešiasdešimttūkstančiųšešišimtai", 461060600)>]
[<InlineData("vienasmilijardas", 1000000000)>]
[<InlineData("dumilijardai", 2000000000)>]
[<InlineData("dumilijardaiketuriasdešimtdevynimilijonaišešišimtaipenkiasdešimttūkstančių", 2049650000)>]
[<InlineData(
    "dumilijardaivienasšimtasketuriasdešimtseptynimilijonaiketurišimtaiaštuoniasdešimttrystūkstančiaišešišimtaiketuriasdešimtseptyni", 
    System.Int32.MaxValue)>]
[<InlineData(
    "dumilijardaivienasšimtasketuriasdešimtseptynimilijonaiketurišimtaiaštuoniasdešimttrystūkstančiaišešišimtaiketuriasdešimtseptynios", 
    System.Int32.MaxValue)>]
let ``tryParseLithuanian returns correct result`` (lithuanian, expected) = 
    let actual = Numeral.tryParseLithuanian lithuanian
    Some expected =! actual

[<Theory>]
[<InlineData(0, "nulis")>]
[<InlineData(1, "vienas")>]
[<InlineData(2, "du")>]
[<InlineData(3, "trys")>]
[<InlineData(4, "keturi")>]
[<InlineData(5, "penki")>]
[<InlineData(6, "šeši")>]
[<InlineData(7, "septyni")>]
[<InlineData(8, "aštuoni")>]
[<InlineData(9, "devyni")>]
[<InlineData(10, "dešimt")>]
[<InlineData(11, "vienuolika")>]
[<InlineData(12, "dvylika")>]
[<InlineData(13, "trylika")>]
[<InlineData(14, "keturiolika")>]
[<InlineData(15, "penkiolika")>]
[<InlineData(16, "šešiolika")>]
[<InlineData(17, "septyniolika")>]
[<InlineData(18, "aštuoniolika")>]
[<InlineData(19, "devyniolika")>]
[<InlineData(20, "dvidešimt")>]
[<InlineData(21, "dvidešimt-vienas")>]
[<InlineData(30, "trisdešimt")>]
[<InlineData(34, "trisdešimt-keturi")>]
[<InlineData(40, "keturiasdešimt")>]
[<InlineData(42, "keturiasdešimt-du")>]
[<InlineData(50, "penkiasdešimt")>]
[<InlineData(58, "penkiasdešimt-aštuoni")>]
[<InlineData(60, "šešiasdešimt")>]
[<InlineData(65, "šešiasdešimt-penki")>]
[<InlineData(70, "septyniasdešimt")>]
[<InlineData(79, "septyniasdešimt-devyni")>]
[<InlineData(80, "aštuoniasdešimt")>]
[<InlineData(86, "aštuoniasdešimt-šeši")>]
[<InlineData(90, "devyniasdešimt")>]
[<InlineData(93, "devyniasdešimt-trys")>]
[<InlineData(100, "šimtas")>]
[<InlineData(101, "šimtas-vienas")>]
[<InlineData(110, "šimtas-dešimt")>]
[<InlineData(114, "šimtas-keturiolika")>]
[<InlineData(135, "šimtas-trisdešimt-penki")>]
[<InlineData(200, "du-šimtai")>]
[<InlineData(282, "du-šimtai-aštuoniasdešimt-du")>]
[<InlineData(331, "trys-šimtai-trisdešimt-vienas")>]
[<InlineData(407, "keturi-šimtai-septyni")>]
[<InlineData(520, "penki-šimtai-dvidešimt")>]
[<InlineData(666, "šeši-šimtai-šešiasdešimt-šeši")>]
[<InlineData(798, "septyni-šimtai-devyniasdešimt-aštuoni")>]
[<InlineData(857, "aštuoni-šimtai-penkiasdešimt-septyni")>]
[<InlineData(999, "devyni-šimtai-devyniasdešimt-devyni")>]
[<InlineData(1000, "tūkstantis")>]
[<InlineData(1001, "tūkstantis-vienas")>]
[<InlineData(1010, "tūkstantis-dešimt")>]
[<InlineData(1066, "tūkstantis-šešiasdešimt-šeši")>]
[<InlineData(1337, "tūkstantis-trys-šimtai-trisdešimt-septyni")>]
[<InlineData(1984, "tūkstantis-devyni-šimtai-aštuoniasdešimt-keturi")>]
[<InlineData(2015, "du-tūkstančiai-penkiolika")>]
[<InlineData(3000, "trys-tūkstančiai")>]
[<InlineData(3297, "trys-tūkstančiai-du-šimtai-devyniasdešimt-septyni")>]
[<InlineData(4080, "keturi-tūkstančiai-aštuoniasdešimt")>]
[<InlineData(5011, "penki-tūkstančiai-vienuolika")>]
[<InlineData(6025, "šeši-tūkstančiai-dvidešimt-penki")>]
[<InlineData(7441, "septyni-tūkstančiai-keturi-šimtai-keturiasdešimt-vienas")>]
[<InlineData(8513, "aštuoni-tūkstančiai-penki-šimtai-trylika")>]
[<InlineData(9000, "devyni-tūkstančiai")>]
[<InlineData(10000, "dešimt-tūkstančių")>]
[<InlineData(12001, "dvylika-tūkstančių-vienas")>]
[<InlineData(23456, "dvidešimt-trys-tūkstančiai-keturi-šimtai-penkiasdešimt-šeši")>]
[<InlineData(32109, "trisdešimt-du-tūkstančiai-šimtas-devyni")>]
[<InlineData(40404, "keturiasdešimt-tūkstančių-keturi-šimtai-keturi")>]
[<InlineData(56789, "penkiasdešimt-šeši-tūkstančiai-septyni-šimtai-aštuoniasdešimt-devyni")>]
[<InlineData(60015, "šešiasdešimt-tūkstančių-penkiolika")>]
[<InlineData(71003, "septyniasdešimt-vienas-tūkstantis-trys")>]
[<InlineData(80522, "aštuoniasdešimt-tūkstančių-penki-šimtai-dvidešimt-du")>]
[<InlineData(98765, "devyniasdešimt-aštuoni-tūkstančiai-septyni-šimtai-šešiasdešimt-penki")>]
[<InlineData(100000, "šimtas-tūkstančių")>]
[<InlineData(100001, "šimtas-tūkstančių-vienas")>]
[<InlineData(100010, "šimtas-tūkstančių-dešimt")>]
[<InlineData(101010, "šimtas-vienas-tūkstantis-dešimt")>]
[<InlineData(200000, "du-šimtai-tūkstančių")>]
[<InlineData(321000, "trys-šimtai-dvidešimt-vienas-tūkstantis")>]
[<InlineData(411416, "keturi-šimtai-vienuolika-tūkstančių-keturi-šimtai-šešiolika")>]
[<InlineData(530121, "penki-šimtai-trisdešimt-tūkstančių-šimtas-dvidešimt-vienas")>]
[<InlineData(600000, "šeši-šimtai-tūkstančių")>]
[<InlineData(788000, "septyni-šimtai-aštuoniasdešimt-aštuoni-tūkstančiai")>]
[<InlineData(876540, "aštuoni-šimtai-septyniasdešimt-šeši-tūkstančiai-penki-šimtai-keturiasdešimt")>]
[<InlineData(908077, "devyni-šimtai-aštuoni-tūkstančiai-septyniasdešimt-septyni")>]
[<InlineData(1000000, "milijonas")>]
[<InlineData(2000002, "du-milijonai-du")>]
[<InlineData(3040506, "trys-milijonai-keturiasdešimt-tūkstančių-penki-šimtai-šeši")>]
[<InlineData(4321000, "keturi-milijonai-trys-šimtai-dvidešimt-vienas-tūkstantis")>]
[<InlineData(5004621, "penki-milijonai-keturi-tūkstančiai-šeši-šimtai-dvidešimt-vienas")>]
[<InlineData(6982001, "šeši-milijonai-devyni-šimtai-aštuoniasdešimt-du-tūkstančiai-vienas")>]
[<InlineData(7000000, "septyni-milijonai")>]
[<InlineData(8000220, "aštuoni-milijonai-du-šimtai-dvidešimt")>]
[<InlineData(9099000, "devyni-milijonai-devyniasdešimt-devyni-tūkstančiai")>]
[<InlineData(10000000, "dešimt-milijonų")>]
[<InlineData(24000000, "dvidešimt-keturi-milijonai")>]
[<InlineData(39020011, "trisdešimt-devyni-milijonai-dvidešimt-tūkstančių-vienuolika")>]
[<InlineData(40606100, "keturiasdešimt-milijonų-šeši-šimtai-šeši-tūkstančiai-šimtas")>]
[<InlineData(53000000, "penkiasdešimt-trys-milijonai")>]
[<InlineData(64000098, "šešiasdešimt-keturi-milijonai-devyniasdešimt-aštuoni")>]
[<InlineData(70003190, "septyniasdešimt-milijonų-trys-tūkstančiai-šimtas-devyniasdešimt")>]
[<InlineData(80000000, "aštuoniasdešimt-milijonų")>]
[<InlineData(99000099, "devyniasdešimt-devyni-milijonai-devyniasdešimt-devyni")>]
[<InlineData(100000000, "šimtas-milijonų")>]
[<InlineData(209000000, "du-šimtai-devyni-milijonai")>]
[<InlineData(398000000, "trys-šimtai-devyniasdešimt-aštuoni-milijonai")>]
[<InlineData(439011000, "keturi-šimtai-trisdešimt-devyni-milijonai-vienuolika-tūkstančių")>]
[<InlineData(560400000, "penki-šimtai-šešiasdešimt-milijonų-keturi-šimtai-tūkstančių")>]
[<InlineData(600010900, "šeši-šimtai-milijonų-dešimt-tūkstančių-devyni-šimtai")>]
[<InlineData(700000000, "septyni-šimtai-milijonų")>]
[<InlineData(800116000, "aštuoni-šimtai-milijonų-šimtas-šešiolika-tūkstančių")>]
[<InlineData(900800007, "devyni-šimtai-milijonų-aštuoni-šimtai-tūkstančių-septyni")>]
[<InlineData(1000000000, "milijardas")>]
[<InlineData(2110000000, "du-milijardai-šimtas-dešimt-milijonų")>]
[<InlineData(
    System.Int32.MaxValue, 
    "du-milijardai-šimtas-keturiasdešimt-septyni-milijonai-keturi-šimtai-aštuoniasdešimt-trys-tūkstančiai-šeši-šimtai-keturiasdešimt-septyni")>]
let ``toLithuanian returns correct result`` (i, expected) = 
    let actual = Numeral.toLithuanian i
    expected =! actual
