module Ploeh.Numsense.PolishExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                             "zero",          0)>]
[<InlineData(                                            " zero",          0)>]
[<InlineData(                                            "zero ",          0)>]
[<InlineData(                                         "  zero  ",          0)>]
[<InlineData(                                             "Zero",          0)>]
[<InlineData(                                             "ZERO",          0)>]
[<InlineData(                                          " zERo\t",          0)>]
[<InlineData(                                            "jeden",          1)>]
[<InlineData(                                            "JEDEN",          1)>]
[<InlineData(                                              "dwa",          2)>]
[<InlineData(                                             " dwa",          2)>]
[<InlineData(                                             "trzy",          3)>]
[<InlineData(                                           "trzy  ",          3)>]
[<InlineData(                                           "cztery",          4)>]
[<InlineData(                                        "  cztery ",          4)>]
[<InlineData(                                             "pięć",          5)>]
[<InlineData(                                             "PięĆ",          5)>]
[<InlineData(                                            "sześć",          6)>]
[<InlineData(                                        "  SZEŚĆ  ",          6)>]
[<InlineData(                                           "siedem",          7)>]
[<InlineData(                                       "    siEdem",          7)>]
[<InlineData(                                            "osiem",          8)>]
[<InlineData(                                            "oSIEM",          8)>]
[<InlineData(                                         "dziewięć",          9)>]
[<InlineData(                                       "DzIeWiĘć  ",          9)>]
[<InlineData(                                         "dziesięć",         10)>]
[<InlineData(                                       "jedenaście",         11)>]
[<InlineData(                                        "dwanaście",         12)>]
[<InlineData(                                       "trzynaście",         13)>]
[<InlineData(                                      "czternaście",         14)>]
[<InlineData(                                       "piętnaście",         15)>]
[<InlineData(                                       "szesnaście",         16)>]
[<InlineData(                                     "siedemnaście",         17)>]
[<InlineData(                                      "osiemnaście",         18)>]
[<InlineData(                                   "dziewiętnaście",         19)>]
[<InlineData(                                      "dwadzieścia",         20)>]
[<InlineData(                                 "dwadzieściajeden",         21)>]
[<InlineData(                                "dwadzieścia-jeden",         21)>]
[<InlineData(                                      "trzydzieści",         30)>]
[<InlineData(                                "trzydzieścicztery",         34)>]
[<InlineData(                                "trzydzieści-osiem",         38)>]
[<InlineData(                                     "czterdzieści",         40)>]
[<InlineData(                               "czterdzieści-jeden",         41)>]
[<InlineData(                               "czterdzieścicztery",         44)>]
[<InlineData(                                     "pięćdziesiąt",         50)>]
[<InlineData(                               "pięćdziesiątsiedem",         57)>]
[<InlineData(                                    "sześćdziesiąt",         60)>]
[<InlineData(                                "sześćdziesiątpięć",         65)>]
[<InlineData(                                   "siedemdziesiąt",         70)>]
[<InlineData(                            "siedemdziesiąt-siedem",         77)>]
[<InlineData(                           "siedemdziesiątdziewięć",         79)>]
[<InlineData(                                    "osiemdziesiąt",         80)>]
[<InlineData(                               "osiemdziesiątsześć",         86)>]
[<InlineData(                                 "dziewięćdziesiąt",         90)>]
[<InlineData(                             "dziewięćdziesiąttrzy",         93)>]
[<InlineData(                                              "sto",        100)>]
[<InlineData(                                         "stojeden",        101)>]
[<InlineData(                                        "sto-jeden",        101)>]
[<InlineData(                                         "dwieście",        200)>]
[<InlineData(                        "dwieścietrzydzieścisiedem",        237)>]
[<InlineData(                        "trzystasiedemdziesiątpięć",        375)>]
[<InlineData(                        "czterystadziewięćdziesiąt",        490)>]
[<InlineData(                         "pięćsetsześćdziesiąttrzy",        563)>]
[<InlineData(                              "sześćsetosiemnaście",        618)>]
[<InlineData(                    "siedemsetsiedemdziesiątsiedem",        777)>]
[<InlineData(                                     "osiemsetpięć",        805)>]
[<InlineData(                                    "osiemsetsześć",        806)>]
[<InlineData(                                  "osiemset-siedem",        807)>]
[<InlineData(                  "dziewięćsetpięćdziesiątdziewięć",        959)>]
[<InlineData(                                           "tysiąc",       1000)>]
[<InlineData(                                      "jedentysiąc",       1000)>]
[<InlineData(                                      "tysiącjeden",       1001)>]
[<InlineData(                                        "tysiącdwa",       1002)>]
[<InlineData(                        "tysiącsześćdziesiątcztery",       1064)>]
[<InlineData(                                       "dwatysiące",       2000)>]
[<InlineData(            "osiemtysięcysiedemsetdwadzieściajeden",       8721)>]
[<InlineData(            "dziewięć-tysięcy-sto-dwadzieścia-trzy",       9123)>]
[<InlineData(                                  "dziesięćtysięcy",      10000)>]
[<InlineData(                          "dziesięćtysięcystojeden",      10101)>]
[<InlineData(                         "dziesięć-tysięcy-sto-dwa",      10102)>]
[<InlineData( "dwadzieściatrzytysiącepięćsetsześćdziesiątcztery",      23564)>]
[<InlineData(                     "osiemdziesiąttysięcydziesięć",      80010)>]
[<InlineData(                                       "stotysięcy",     100000)>]
[<InlineData(                                      "sto-tysięcy",     100000)>]
[<InlineData(                                  "stotysięcyjeden",     100001)>]
[<InlineData(                                           "milion",    1000000)>]
[<InlineData(                                      "jedenmilion",    1000000)>]
[<InlineData(                                      "milionjeden",    1000001)>]
[<InlineData(                               "dwamilionydziesięć",    2000010)>]
[<InlineData(                  "sześćmilionówtrzydzieścitysięcy",    6030000)>]
[<InlineData(                                 "dziesięćmilionów",   10000000)>]
[<InlineData(                         "dziesięćmilionówdziewięć",   10000009)>]
[<InlineData(                         "dwadzieściajedenmilionów",   21000000)>]
[<InlineData(                                      "stomilionów",  100000000)>]
[<InlineData(                                     "sto-milionów",  100000000)>]
[<InlineData(                                 "stojedenmilionów",  101000000)>]
[<InlineData(                             "dwieściepięćmilionów",  205000000)>]
[<InlineData(                          "trzysta-siedem-milionów",  307000000)>]
[<InlineData(                                          "miliard", 1000000000)>]
[<InlineData(                                    "jeden-miliard", 1000000000)>]
[<InlineData(                                      "dwamiliardy", 2000000000)>]
[<InlineData(
    "trzystadziewiętnaścietysięcytrzystaczterdzieścidziewięć",
    319349)>]
[<InlineData(
    "dziewięćmilionówdwieściejedentysięcysześćsetosiemdziesiąt",
    9201680)>]
[<InlineData(
    "czterdzieścisiedemmilionówsześćsetsześćdziesiątjedentysięcysześćdziesiąt",
    47661060)>]
[<InlineData(
    "czterystasześćdziesiątjedenmilionówsześćdziesiąttysięcysześćset",
    461060600)>]
[<InlineData(
    "dwamiliardyczterdzieścidziewięćmilionówsześćsetpięćdziesiąttysięcy",
    2049650000)>]
[<InlineData(
    "dwamiliardystoczterdzieścisiedemmilionówczterystaosiemdziesiąttrzytysiącesześćsetczterdzieścisiedem",
    System.Int32.MaxValue)>]
let ``tryOfPolish returns correct result`` (polish, expected) =
    let actual = Numeral.tryParsePolish polish
    Some expected =! actual

[<Theory>]
[<InlineData(         0, "zero")>]
[<InlineData(         1, "jeden")>]
[<InlineData(         2, "dwa")>]
[<InlineData(         3, "trzy")>]
[<InlineData(         4, "cztery")>]
[<InlineData(         5, "pięć")>]
[<InlineData(         6, "sześć")>]
[<InlineData(         7, "siedem")>]
[<InlineData(         8, "osiem")>]
[<InlineData(         9, "dziewięć")>]
[<InlineData(        10, "dziesięć")>]
[<InlineData(        11, "jedenaście")>]
[<InlineData(        12, "dwanaście")>]
[<InlineData(        13, "trzynaście")>]
[<InlineData(        14, "czternaście")>]
[<InlineData(        15, "piętnaście")>]
[<InlineData(        16, "szesnaście")>]
[<InlineData(        17, "siedemnaście")>]
[<InlineData(        18, "osiemnaście")>]
[<InlineData(        19, "dziewiętnaście")>]
[<InlineData(        20, "dwadzieścia")>]
[<InlineData(        21, "dwadzieścia-jeden")>]
[<InlineData(        30, "trzydzieści")>]
[<InlineData(        34, "trzydzieści-cztery")>]
[<InlineData(        40, "czterdzieści")>]
[<InlineData(        42, "czterdzieści-dwa")>]
[<InlineData(        50, "pięćdziesiąt")>]
[<InlineData(        58, "pięćdziesiąt-osiem")>]
[<InlineData(        60, "sześćdziesiąt")>]
[<InlineData(        65, "sześćdziesiąt-pięć")>]
[<InlineData(        70, "siedemdziesiąt")>]
[<InlineData(        79, "siedemdziesiąt-dziewięć")>]
[<InlineData(        80, "osiemdziesiąt")>]
[<InlineData(        86, "osiemdziesiąt-sześć")>]
[<InlineData(        90, "dziewięćdziesiąt")>]
[<InlineData(        93, "dziewięćdziesiąt-trzy")>]
[<InlineData(       100, "sto")>]
[<InlineData(       101, "sto-jeden")>]
[<InlineData(       110, "sto-dziesięć")>]
[<InlineData(       114, "sto-czternaście")>]
[<InlineData(       135, "sto-trzydzieści-pięć")>]
[<InlineData(       200, "dwieście")>]
[<InlineData(       282, "dwieście-osiemdziesiąt-dwa")>]
[<InlineData(       331, "trzysta-trzydzieści-jeden")>]
[<InlineData(       407, "czterysta-siedem")>]
[<InlineData(       520, "pięćset-dwadzieścia")>]
[<InlineData(       666, "sześćset-sześćdziesiąt-sześć")>]
[<InlineData(       798, "siedemset-dziewięćdziesiąt-osiem")>]
[<InlineData(       857, "osiemset-pięćdziesiąt-siedem")>]
[<InlineData(       999, "dziewięćset-dziewięćdziesiąt-dziewięć")>]
[<InlineData(      1000, "tysiąc")>]
[<InlineData(      1001, "tysiąc-jeden")>]
[<InlineData(      1010, "tysiąc-dziesięć")>]
[<InlineData(      1066, "tysiąc-sześćdziesiąt-sześć")>]
[<InlineData(      1337, "tysiąc-trzysta-trzydzieści-siedem")>]
[<InlineData(      1984, "tysiąc-dziewięćset-osiemdziesiąt-cztery")>]
[<InlineData(      2015, "dwa-tysiące-piętnaście")>]
[<InlineData(      3000, "trzy-tysiące")>]
[<InlineData(      3297, "trzy-tysiące-dwieście-dziewięćdziesiąt-siedem")>]
[<InlineData(      4080, "cztery-tysiące-osiemdziesiąt")>]
[<InlineData(      5011, "pięć-tysięcy-jedenaście")>]
[<InlineData(      6025, "sześć-tysięcy-dwadzieścia-pięć")>]
[<InlineData(      7441, "siedem-tysięcy-czterysta-czterdzieści-jeden")>]
[<InlineData(      8513, "osiem-tysięcy-pięćset-trzynaście")>]
[<InlineData(      9000, "dziewięć-tysięcy")>]
[<InlineData(     10000, "dziesięć-tysięcy")>]
[<InlineData(     12001, "dwanaście-tysięcy-jeden")>]
[<InlineData(     32109, "trzydzieści-dwa-tysiące-sto-dziewięć")>]
[<InlineData(     40404, "czterdzieści-tysięcy-czterysta-cztery")>]
[<InlineData(     60015, "sześćdziesiąt-tysięcy-piętnaście")>]
[<InlineData(     71003, "siedemdziesiąt-jeden-tysięcy-trzy")>]
[<InlineData(     80522, "osiemdziesiąt-tysięcy-pięćset-dwadzieścia-dwa")>]
[<InlineData(    100000, "sto-tysięcy")>]
[<InlineData(    100001, "sto-tysięcy-jeden")>]
[<InlineData(    100010, "sto-tysięcy-dziesięć")>]
[<InlineData(    101010, "sto-jeden-tysięcy-dziesięć")>]
[<InlineData(    200000, "dwieście-tysięcy")>]
[<InlineData(    321000, "trzysta-dwadzieścia-jeden-tysięcy")>]
[<InlineData(    411416, "czterysta-jedenaście-tysięcy-czterysta-szesnaście")>]
[<InlineData(    530121, "pięćset-trzydzieści-tysięcy-sto-dwadzieścia-jeden")>]
[<InlineData(    600000, "sześćset-tysięcy")>]
[<InlineData(    788000, "siedemset-osiemdziesiąt-osiem-tysięcy")>]
[<InlineData(    908077, "dziewięćset-osiem-tysięcy-siedemdziesiąt-siedem")>]
[<InlineData(   1000000, "milion")>]
[<InlineData(   2000002, "dwa-miliony-dwa")>]
[<InlineData(   3040506, "trzy-miliony-czterdzieści-tysięcy-pięćset-sześć")>]
[<InlineData(   4321000, "cztery-miliony-trzysta-dwadzieścia-jeden-tysięcy")>]
[<InlineData(   7000000, "siedem-milionów")>]
[<InlineData(   8000220, "osiem-milionów-dwieście-dwadzieścia")>]
[<InlineData(  10000000, "dziesięć-milionów")>]
[<InlineData(  24000000, "dwadzieścia-cztery-miliony")>]
[<InlineData(  40606100, "czterdzieści-milionów-sześćset-sześć-tysięcy-sto")>]
[<InlineData(  53000000, "pięćdziesiąt-trzy-miliony")>]
[<InlineData(  80000000, "osiemdziesiąt-milionów")>]
[<InlineData( 100000000, "sto-milionów")>]
[<InlineData( 209000000, "dwieście-dziewięć-milionów")>]
[<InlineData( 398000000, "trzysta-dziewięćdziesiąt-osiem-milionów")>]
[<InlineData( 560400000, "pięćset-sześćdziesiąt-milionów-czterysta-tysięcy")>]
[<InlineData( 600010900, "sześćset-milionów-dziesięć-tysięcy-dziewięćset")>]
[<InlineData( 700000000, "siedemset-milionów")>]
[<InlineData( 800116000, "osiemset-milionów-sto-szesnaście-tysięcy")>]
[<InlineData( 900800007, "dziewięćset-milionów-osiemset-tysięcy-siedem")>]
[<InlineData(1000000000, "miliard")>]
[<InlineData(2121000000, "dwa-miliardy-sto-dwadzieścia-jeden-milionów")>]
[<InlineData(
    23456,
    "dwadzieścia-trzy-tysiące-czterysta-pięćdziesiąt-sześć")>]
[<InlineData(
    56789,
    "pięćdziesiąt-sześć-tysięcy-siedemset-osiemdziesiąt-dziewięć")>]
[<InlineData(
    98765,
    "dziewięćdziesiąt-osiem-tysięcy-siedemset-sześćdziesiąt-pięć")>]
[<InlineData(
    876540,
    "osiemset-siedemdziesiąt-sześć-tysięcy-pięćset-czterdzieści")>]
[<InlineData(
    5004621,
    "pięć-milionów-cztery-tysiące-sześćset-dwadzieścia-jeden")>]
[<InlineData(
    6982001,
    "sześć-milionów-dziewięćset-osiemdziesiąt-dwa-tysiące-jeden")>]
[<InlineData(
    9099000,
    "dziewięć-milionów-dziewięćdziesiąt-dziewięć-tysięcy")>]
[<InlineData(
    39020011,
    "trzydzieści-dziewięć-milionów-dwadzieścia-tysięcy-jedenaście")>]
[<InlineData(
    64000098,
    "sześćdziesiąt-cztery-miliony-dziewięćdziesiąt-osiem")>]
[<InlineData(
    70003190,
    "siedemdziesiąt-milionów-trzy-tysiące-sto-dziewięćdziesiąt")>]
[<InlineData(
    99000099,
    "dziewięćdziesiąt-dziewięć-milionów-dziewięćdziesiąt-dziewięć")>]
[<InlineData(
    439011000,
    "czterysta-trzydzieści-dziewięć-milionów-jedenaście-tysięcy")>]
[<InlineData(
    System.Int32.MaxValue,
    "dwa-miliardy-sto-czterdzieści-siedem-milionów-czterysta-osiemdziesiąt-trzy-tysiące-sześćset-czterdzieści-siedem")>]
let ``toPolish returns correct result`` (i, expected) =
    let actual = Numeral.toPolish i
    expected =! actual