module Ploeh.Numsense.PortugueseExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(               "menos mil-quinhentos-sessenta-oito",      -1568)>]
[<InlineData(                                         "menos um",         -1)>]
[<InlineData(                                             "zero",          0)>]
[<InlineData(                                            " zero",          0)>]
[<InlineData(                                            "zero ",          0)>]
[<InlineData(                                         "  zero  ",          0)>]
[<InlineData(                                             "Zero",          0)>]
[<InlineData(                                             "ZERO",          0)>]
[<InlineData(                                          " zERo\t",          0)>]
[<InlineData(                                               "um",          1)>]
[<InlineData(                                               "UM",          1)>]
[<InlineData(                                             "dois",          2)>]
[<InlineData(                                            " dois",          2)>]
[<InlineData(                                             "três",          3)>]
[<InlineData(                                           "três  ",          3)>]
[<InlineData(                                           "quatro",          4)>]
[<InlineData(                                        "  quatro ",          4)>]
[<InlineData(                                            "cinco",          5)>]
[<InlineData(                                            "CiNcO",          5)>]
[<InlineData(                                             "seis",          6)>]
[<InlineData(                                         "  seis  ",          6)>]
[<InlineData(                                             "sete",          7)>]
[<InlineData(                                         "    seTe",          7)>]
[<InlineData(                                             "oito",          8)>]
[<InlineData(                                             "oITO",          8)>]
[<InlineData(                                             "nove",          9)>]
[<InlineData(                                           "nOvE  ",          9)>]
[<InlineData(                                              "dez",         10)>]
[<InlineData(                                             "onze",         11)>]
[<InlineData(                                             "doze",         12)>]
[<InlineData(                                            "treze",         13)>]
[<InlineData(                                         "quatorze",         14)>]
[<InlineData(                                          "catorze",         14)>]
[<InlineData(                                           "quinze",         15)>]
[<InlineData(                                        "dezasseis",         16)>]
[<InlineData(                                        "dezassete",         17)>]
[<InlineData(                                          "dezoito",         18)>]
[<InlineData(                                         "dezanove",         19)>]
[<InlineData(                                            "vinte",         20)>]
[<InlineData(                                         "vinteeum",         21)>]
[<InlineData(                                       "vinte-e-um",         21)>]
[<InlineData(                                           "trinta",         30)>]
[<InlineData(                                    "trintaequatro",         34)>]
[<InlineData(                                    "trinta-e-oito",         38)>]
[<InlineData(                                         "quarenta",         40)>]
[<InlineData(                                    "quarenta-e-um",         41)>]
[<InlineData(                                "quarenta-e-quatro",         44)>]
[<InlineData(                                        "cinquenta",         50)>]
[<InlineData(                                   "cinquentaesete",         57)>]
[<InlineData(                                         "sessenta",         60)>]
[<InlineData(                                   "sessentaecinco",         65)>]
[<InlineData(                                          "setenta",         70)>]
[<InlineData(                                   "setenta-e-sete",         77)>]
[<InlineData(                                     "setentaenove",         79)>]
[<InlineData(                                          "oitenta",         80)>]
[<InlineData(                                     "oitentaeseis",         86)>]
[<InlineData(                                          "noventa",         90)>]
[<InlineData(                                     "noventaetrês",         93)>]
[<InlineData(                                              "cem",        100)>]
[<InlineData(                                         "centoeum",        101)>]
[<InlineData(                                       "cento-e-um",        101)>]
[<InlineData(                                         "duzentos",        200)>]
[<InlineData(                             "duzentosetrintaesete",        237)>]
[<InlineData(                          "trezentosesetentaecinco",        375)>]
[<InlineData(                             "quatrocentosenoventa",        490)>]
[<InlineData(                         "quinhentosesessentaetrês",        563)>]
[<InlineData(                               "seiscentosedezoito",        618)>]
[<InlineData(                         "setecentosesetentaesete",         777)>]
[<InlineData(                                 "oitocentosecinco",        805)>]
[<InlineData(                                  "oitocentoseseis",        806)>]
[<InlineData(                        "novecentosecinquentaenove",        959)>]
[<InlineData(                                              "mil",       1000)>]
[<InlineData(                                           "mileum",       1001)>]
[<InlineData(                                         "miledois",       1002)>]
[<InlineData(                              "milesessentaequatro",       1064)>]
[<InlineData(                                          "doismil",       2000)>]
[<InlineData(                       "oitomilsetecentosevinteeum",       8721)>]
[<InlineData(                          "novemilcentoevinteetrês",       9123)>]
[<InlineData(                                           "dezmil",      10000)>]
[<InlineData(                                   "dezmilcentoeum",      10101)>]
[<InlineData(                                 "dezmilcentoedois",      10102)>]
[<InlineData(          "vinteetrêsmilquinhentosesessentaequatro",      23564)>]
[<InlineData(                                   "oitentamiledez",      80010)>]
[<InlineData(                                           "cemmil",     100000)>]
[<InlineData(                                        "cemmileum",     100001)>]
[<InlineData(     "trezentosedezanovemiltrezentosequarentaenove",     319349)>]
[<InlineData(                                         "ummilhão",    1000000)>]
[<InlineData(                                      "ummilhãoeum",    1000001)>]
[<InlineData(                                  "doismilhõesedez",    2000010)>]
[<InlineData(                            "seismilhõesetrintamil",    6030000)>]
[<InlineData(      "novemilhõesduzentoseummilseiscentoseoitenta",    9201680)>]
[<InlineData(                                       "dezmilhões",   10000000)>]
[<InlineData(                                  "dezmilhõesenove",   10000009)>]
[<InlineData(                                  "vinteeummilhões",   21000000)>]
[<InlineData(
        "quarentaesetemilhõesseiscentosesessentaeummilesessenta",   47661060)>]
[<InlineData(                                       "cemmilhões",  100000000)>]
[<InlineData(                            "duzentosecincomilhões",  205000000)>]
[<InlineData(                         "trezentos-e-sete-milhões",  307000000)>]
[<InlineData(
         "quatrocentosesessentaeummilhõessessentamileseiscentos",  461060600)>]
[<InlineData(                                       "milmilhões", 1000000000)>]
[<InlineData(                                   "doismilmilhões", 2000000000)>]
[<InlineData(
           "doismilequarentaenovemilhõesseiscentosecinquentamil", 2049650000)>]
[<InlineData(
    "doismilcentoequarentaesetemilhõesquatrocentoseoitentaetrêsmilseiscentosequarentaesete",
    System.Int32.MaxValue)>]
let ``tryParsePortuguese returns correct result`` (portuguese, expected) =
    let actual = Numeral.tryParsePortuguese portuguese
    Some expected =! actual

[<Theory>]
[<InlineData(     -1586, "menos mil-quinhentos-oitenta-seis")>]
[<InlineData(        -1, "menos um")>]
[<InlineData(         0, "zero")>]
[<InlineData(         1, "um")>]
[<InlineData(         2, "dois")>]
[<InlineData(         3, "três")>]
[<InlineData(         4, "quatro")>]
[<InlineData(         5, "cinco")>]
[<InlineData(         6, "seis")>]
[<InlineData(         7, "sete")>]
[<InlineData(         8, "oito")>]
[<InlineData(         9, "nove")>]
[<InlineData(        10, "dez")>]
[<InlineData(        11, "onze")>]
[<InlineData(        12, "doze")>]
[<InlineData(        13, "treze")>]
[<InlineData(        14, "catorze")>]
[<InlineData(        15, "quinze")>]
[<InlineData(        16, "dezasseis")>]
[<InlineData(        17, "dezassete")>]
[<InlineData(        18, "dezoito")>]
[<InlineData(        19, "dezanove")>]
[<InlineData(        20, "vinte")>]
[<InlineData(        21, "vinte-um")>]
[<InlineData(        30, "trinta")>]
[<InlineData(        34, "trinta-quatro")>]
[<InlineData(        40, "quarenta")>]
[<InlineData(        42, "quarenta-dois")>]
[<InlineData(        50, "cinquenta")>]
[<InlineData(        58, "cinquenta-oito")>]
[<InlineData(        60, "sessenta")>]
[<InlineData(        65, "sessenta-cinco")>]
[<InlineData(        70, "setenta")>]
[<InlineData(        79, "setenta-nove")>]
[<InlineData(        80, "oitenta")>]
[<InlineData(        86, "oitenta-seis")>]
[<InlineData(        90, "noventa")>]
[<InlineData(        93, "noventa-três")>]
[<InlineData(       100, "cem")>]
[<InlineData(       101, "cento-um")>]
[<InlineData(       110, "cento-dez")>]
[<InlineData(       114, "cento-catorze")>]
[<InlineData(       135, "cento-trinta-cinco")>]
[<InlineData(       200, "duzentos")>]
[<InlineData(       282, "duzentos-oitenta-dois")>]
[<InlineData(       331, "trezentos-trinta-um")>]
[<InlineData(       407, "quatrocentos-sete")>]
[<InlineData(       520, "quinhentos-vinte")>]
[<InlineData(       666, "seiscentos-sessenta-seis")>]
[<InlineData(       798, "setecentos-noventa-oito")>]
[<InlineData(       857, "oitocentos-cinquenta-sete")>]
[<InlineData(       999, "novecentos-noventa-nove")>]
[<InlineData(      1000, "mil")>]
[<InlineData(      1001, "mil-um")>]
[<InlineData(      1010, "mil-dez")>]
[<InlineData(      1066, "mil-sessenta-seis")>]
[<InlineData(      1337, "mil-trezentos-trinta-sete")>]
[<InlineData(      1984, "mil-novecentos-oitenta-quatro")>]
[<InlineData(      7441, "sete-mil-quatrocentos-quarenta-um")>]
[<InlineData(      8513, "oito-mil-quinhentos-treze")>]
[<InlineData(    908077, "novecentos-oito-mil-setenta-sete")>]
[<InlineData(   1000000, "um-milhão")>]
[<InlineData(   2000002, "dois-milhões-dois")>]
[<InlineData(   3040506, "três-milhões-quarenta-mil-quinhentos-seis")>]
[<InlineData(   4321000, "quatro-milhões-trezentos-vinte-um-mil")>]
[<InlineData(   5004621, "cinco-milhões-quatro-mil-seiscentos-vinte-um")>]
[<InlineData(   6982001, "seis-milhões-novecentos-oitenta-dois-mil-um")>]
[<InlineData(   7000000, "sete-milhões")>]
[<InlineData(   8000220, "oito-milhões-duzentos-vinte")>]
[<InlineData(   9099000, "nove-milhões-noventa-nove-mil")>]
[<InlineData(  10000000, "dez-milhões")>]
[<InlineData(  24000000, "vinte-quatro-milhões")>]
[<InlineData(  39020011, "trinta-nove-milhões-vinte-mil-onze")>]
[<InlineData(  40606100, "quarenta-milhões-seiscentos-seis-mil-cem")>]
[<InlineData(  53000000, "cinquenta-três-milhões")>]
[<InlineData(  64000098, "sessenta-quatro-milhões-noventa-oito")>]
[<InlineData(  70003190, "setenta-milhões-três-mil-cento-noventa")>]
[<InlineData(  80000000, "oitenta-milhões")>]
[<InlineData(  99000099, "noventa-nove-milhões-noventa-nove")>]
[<InlineData( 100000000, "cem-milhões")>]
[<InlineData( 209000000, "duzentos-nove-milhões")>]
[<InlineData( 398000000, "trezentos-noventa-oito-milhões")>]
[<InlineData( 439011000, "quatrocentos-trinta-nove-milhões-onze-mil")>]
[<InlineData( 560400000, "quinhentos-sessenta-milhões-quatrocentos-mil")>]
[<InlineData( 600010900, "seiscentos-milhões-dez-mil-novecentos")>]
[<InlineData( 700000000, "setecentos-milhões")>]
[<InlineData( 800116000, "oitocentos-milhões-cento-dezasseis-mil")>]
[<InlineData( 900800007, "novecentos-milhões-oitocentos-mil-sete")>]
[<InlineData(1000000000, "mil-milhões")>]
[<InlineData(2121000000, "dois-mil-milhões-cento-vinte-um-milhões")>]
[<InlineData(
    System.Int32.MaxValue,
    "dois-mil-milhões-cento-quarenta-sete-milhões-quatrocentos-oitenta-três-mil-seiscentos-quarenta-sete")>]

let ``toPortuguese returns correct result`` (i, expected) =
    let actual = Numeral.toPortuguese i
    expected =! actual
