module Ploeh.Numsense.RomanianExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                                       "zero",          0)>]
[<InlineData(                                                      " zero",          0)>]
[<InlineData(                                                      "zero ",          0)>]
[<InlineData(                                                   "  zero  ",          0)>]
[<InlineData(                                                       "Zero",          0)>]
[<InlineData(                                                       "ZERO",          0)>]
[<InlineData(                                                    " zERo\t",          0)>]
[<InlineData(                                                        "unu",          1)>]
[<InlineData(                                                        "UNU",          1)>]
[<InlineData(                                                        "doi",          2)>]
[<InlineData(                                                       " doi",          2)>]
[<InlineData(                                                       "trei",          3)>]
[<InlineData(                                                     "trei  ",          3)>]
[<InlineData(                                                      "patru",          4)>]
[<InlineData(                                                   "  patru ",          4)>]
[<InlineData(                                                      "cinci",          5)>]
[<InlineData(                                                      "CincI",          5)>]
[<InlineData(                                                       "șase",          6)>]
[<InlineData(                                                   "  ȘASE  ",          6)>]
[<InlineData(                                                      "șapte",          7)>]
[<InlineData(                                                  "    șaPte",          7)>]
[<InlineData(                                                        "opt",          8)>]
[<InlineData(                                                        "oPT",          8)>]
[<InlineData(                                                       "nouă",          9)>]
[<InlineData(                                                     "NoUă  ",          9)>]
[<InlineData(                                                       "zece",         10)>]
[<InlineData(                                                 "unsprezece",         11)>]
[<InlineData(                                                "doisprezece",         12)>]
[<InlineData(                                               "treisprezece",         13)>]
[<InlineData(                                                "paisprezece",         14)>]
[<InlineData(                                              "cincisprezece",         15)>]
[<InlineData(                                                "șaisprezece",         16)>]
[<InlineData(                                              "șaptesprezece",         17)>]
[<InlineData(                                                "optsprezece",         18)>]
[<InlineData(                                               "nouăsprezece",         19)>]
[<InlineData(                                                   "douăzeci",         20)>]
[<InlineData(                                              "douăzecișiunu",         21)>]
[<InlineData(                                            "douăzeci-și-unu",         21)>]
[<InlineData(                                                   "treizeci",         30)>]
[<InlineData(                                            "treizecișipatru",         34)>]
[<InlineData(                                            "treizeci-și-opt",         38)>]
[<InlineData(                                                  "patruzeci",         40)>]
[<InlineData(                                           "patruzeci-și-unu",         41)>]
[<InlineData(                                           "patruzecișipatru",         44)>]
[<InlineData(                                                  "cincizeci",         50)>]
[<InlineData(                                           "cincizecișișapte",         57)>]
[<InlineData(                                                    "șaizeci",         60)>]
[<InlineData(                                             "șaizecișicinci",         65)>]
[<InlineData(                                                  "șaptezeci",         70)>]
[<InlineData(                                         "șaptezeci-și-șapte",         77)>]
[<InlineData(                                            "șaptezecișinouă",         79)>]
[<InlineData(                                                    "optzeci",         80)>]
[<InlineData(                                              "optzecișișase",         86)>]
[<InlineData(                                                   "nouăzeci",         90)>]
[<InlineData(                                             "nouăzecișitrei",         93)>]
[<InlineData(                                                      "osută",        100)>]
[<InlineData(                                                   "osutăunu",        101)>]
[<InlineData(                                                 "o-sută-unu",        101)>]
[<InlineData(                                                   "douăsute",        200)>]
[<InlineData(                                    "douăsutetreizecișișapte",        237)>]
[<InlineData(                                   "treisuteșaptezecișicinci",        375)>]
[<InlineData(                                          "patrusutenouăzeci",        490)>]
[<InlineData(                                     "cincisuteșaizecișitrei",        563)>]
[<InlineData(                                        "șasesuteoptsprezece",        618)>]
[<InlineData(                                  "șaptesuteșaptezecișișapte",        777)>]
[<InlineData(                                               "optsutecinci",        805)>]
[<InlineData(                                                "optsuteșase",        806)>]
[<InlineData(                                             "opt-sute-șapte",        807)>]
[<InlineData(                                    "nouăsutecincizecișinouă",        959)>]
[<InlineData(                                                       "omie",       1000)>]
[<InlineData(                                                    "omieunu",       1001)>]
[<InlineData(                                                    "omiedoi",       1002)>]
[<InlineData(                                         "omieșaizecișipatru",       1064)>]
[<InlineData(                                                    "douămii",       2000)>]
[<InlineData(                               "optmiișaptesutedouăzecișiunu",       8721)>]
[<InlineData(                           "nouă-mii-o-sută-douăzeci-și-trei",       9123)>]
[<InlineData(                                                    "zecemii",      10000)>]
[<InlineData(                                            "zecemiiosutăunu",      10101)>]
[<InlineData(                                        "zece-mii-o-sută-doi",      10102)>]
[<InlineData(                 "douăzecișitreidemiicincisuteșaizecișipatru",      23564)>]
[<InlineData(                                           "optzecidemiizece",      80010)>]
[<InlineData(                                                 "osutădemii",     100000)>]
[<InlineData(                                              "osutădemiiunu",     100001)>]
[<InlineData(             "treisutenouăsprezecemiitreisutepatruzecișinouă",     319349)>]
[<InlineData(                                                   "unmilion",    1000000)>]
[<InlineData(                                                "unmilionunu",    1000001)>]
[<InlineData(                                           "douămilioanezece",    2000010)>]
[<InlineData(                                  "șasemilioanetreizecidemii",    6030000)>]
[<InlineData(                  "nouămilioanedouăsuteunamiișasesuteoptzeci",    9201680)>]
[<InlineData(                                               "zecemilioane",   10000000)>]
[<InlineData(                                           "zecemilioanenouă",   10000009)>]
[<InlineData(                                    "douăzecișiunudemilioane",   21000000)>]
[<InlineData( "patruzecișișaptedemilioaneșasesuteșaizecișiunademiișaizeci",   47661060)>]
[<InlineData(                                            "osutădemilioane",  100000000)>]
[<InlineData(                                      "douăsutecincimilioane",  205000000)>]
[<InlineData(                                   "trei-sute-șapte-milioane",  307000000)>]
[<InlineData(        "patrusuteșaizecișiunudemilioaneșaizecidemiișasesute",  461060600)>]
[<InlineData(                                                  "unmiliard", 1000000000)>]
[<InlineData(                                               "douămiliarde", 2000000000)>]
[<InlineData("douămiliardepatruzecișinouădemilioaneșasesutecincizecidemii", 2049650000)>]
[<InlineData(
    "douămiliardeosutăpatruzecișișaptedemilioanepatrusuteoptzecișitreidemiișasesutepatruzecișișapte",
    System.Int32.MaxValue)>]
let ``tryParseRomanian returns correct result`` (romanian, expected) =
    let actual = Numeral.tryParseRomanian romanian
    Some expected =! actual

[<Theory>]
[<InlineData(         0, "zero")>]
[<InlineData(         1, "unu")>]
[<InlineData(         2, "doi")>]
[<InlineData(         3, "trei")>]
[<InlineData(         4, "patru")>]
[<InlineData(         5, "cinci")>]
[<InlineData(         6, "șase")>]
[<InlineData(         7, "șapte")>]
[<InlineData(         8, "opt")>]
[<InlineData(         9, "nouă")>]
[<InlineData(        10, "zece")>]
[<InlineData(        11, "unsprezece")>]
[<InlineData(        12, "doisprezece")>]
[<InlineData(        13, "treisprezece")>]
[<InlineData(        14, "paisprezece")>]
[<InlineData(        15, "cincisprezece")>]
[<InlineData(        16, "șaisprezece")>]
[<InlineData(        17, "șaptesprezece")>]
[<InlineData(        18, "optsprezece")>]
[<InlineData(        19, "nouăsprezece")>]
[<InlineData(        20, "douăzeci")>]
[<InlineData(        21, "douăzeci-și-unu")>]
[<InlineData(        30, "treizeci")>]
[<InlineData(        34, "treizeci-și-patru")>]
[<InlineData(        40, "patruzeci")>]
[<InlineData(        42, "patruzeci-și-doi")>]
[<InlineData(        50, "cincizeci")>]
[<InlineData(        58, "cincizeci-și-opt")>]
[<InlineData(        60, "șaizeci")>]
[<InlineData(        65, "șaizeci-și-cinci")>]
[<InlineData(        70, "șaptezeci")>]
[<InlineData(        79, "șaptezeci-și-nouă")>]
[<InlineData(        80, "optzeci")>]
[<InlineData(        86, "optzeci-și-șase")>]
[<InlineData(        90, "nouăzeci")>]
[<InlineData(        93, "nouăzeci-și-trei")>]
[<InlineData(       100, "o-sută")>]
[<InlineData(       101, "o-sută-unu")>]
[<InlineData(       110, "o-sută-zece")>]
[<InlineData(       114, "o-sută-paisprezece")>]
[<InlineData(       135, "o-sută-treizeci-și-cinci")>]
[<InlineData(       200, "două-sute")>]
[<InlineData(       282, "două-sute-optzeci-și-doi")>]
[<InlineData(       331, "trei-sute-treizeci-și-unu")>]
[<InlineData(       407, "patru-sute-șapte")>]
[<InlineData(       520, "cinci-sute-douăzeci")>]
[<InlineData(       666, "șase-sute-șaizeci-și-șase")>]
[<InlineData(       798, "șapte-sute-nouăzeci-și-opt")>]
[<InlineData(       857, "opt-sute-cincizeci-și-șapte")>]
[<InlineData(       999, "nouă-sute-nouăzeci-și-nouă")>]
[<InlineData(      1000, "o-mie")>]
[<InlineData(      1001, "o-mie-unu")>]
[<InlineData(      1010, "o-mie-zece")>]
[<InlineData(      1066, "o-mie-șaizeci-și-șase")>]
[<InlineData(      1337, "o-mie-trei-sute-treizeci-și-șapte")>]
[<InlineData(      1984, "o-mie-nouă-sute-optzeci-și-patru")>]
[<InlineData(      2015, "două-mii-cincisprezece")>]
[<InlineData(      3000, "trei-mii")>]
[<InlineData(      3297, "trei-mii-două-sute-nouăzeci-și-șapte")>]
[<InlineData(      4080, "patru-mii-optzeci")>]
[<InlineData(      5011, "cinci-mii-unsprezece")>]
[<InlineData(      6025, "șase-mii-douăzeci-și-cinci")>]
[<InlineData(      7441, "șapte-mii-patru-sute-patruzeci-și-unu")>]
[<InlineData(      8513, "opt-mii-cinci-sute-treisprezece")>]
[<InlineData(      9000, "nouă-mii")>]
[<InlineData(     10000, "zece-mii")>]
[<InlineData(     12001, "douăsprezece-mii-unu")>]
[<InlineData(     23456, "douăzeci-și-trei-de-mii-patru-sute-cincizeci-și-șase")>]
[<InlineData(     32109, "treizeci-și-două-de-mii-o-sută-nouă")>]
[<InlineData(     40404, "patruzeci-de-mii-patru-sute-patru")>]
[<InlineData(     56789, "cincizeci-și-șase-de-mii-șapte-sute-optzeci-și-nouă")>]
[<InlineData(     60015, "șaizeci-de-mii-cincisprezece")>]
[<InlineData(     71003, "șaptezeci-și-una-de-mii-trei")>]
[<InlineData(     80522, "optzeci-de-mii-cinci-sute-douăzeci-și-doi")>]
[<InlineData(     98765, "nouăzeci-și-opt-de-mii-șapte-sute-șaizeci-și-cinci")>]
[<InlineData(    100000, "o-sută-de-mii")>]
[<InlineData(    100001, "o-sută-de-mii-unu")>]
[<InlineData(    100010, "o-sută-de-mii-zece")>]
[<InlineData(    101010, "o-sută-una-mii-zece")>]
[<InlineData(    200000, "două-sute-de-mii")>]
[<InlineData(    321000, "trei-sute-douăzeci-și-una-de-mii")>]
[<InlineData(    411416, "patru-sute-unsprezece-mii-patru-sute-șaisprezece")>]
[<InlineData(    530121, "cinci-sute-treizeci-de-mii-o-sută-douăzeci-și-unu")>]
[<InlineData(    600000, "șase-sute-de-mii")>]
[<InlineData(    788000, "șapte-sute-optzeci-și-opt-de-mii")>]
[<InlineData(    876540, "opt-sute-șaptezeci-și-șase-de-mii-cinci-sute-patruzeci")>]
[<InlineData(    908077, "nouă-sute-opt-mii-șaptezeci-și-șapte")>]
[<InlineData(   1000000, "un-milion")>]
[<InlineData(   2000002, "două-milioane-doi")>]
[<InlineData(   3040506, "trei-milioane-patruzeci-de-mii-cinci-sute-șase")>]
[<InlineData(   4321000, "patru-milioane-trei-sute-douăzeci-și-una-de-mii")>]
[<InlineData(   5004621, "cinci-milioane-patru-mii-șase-sute-douăzeci-și-unu")>]
[<InlineData(   6982001, "șase-milioane-nouă-sute-optzeci-și-două-de-mii-unu")>]
[<InlineData(   7000000, "șapte-milioane")>]
[<InlineData(   8000220, "opt-milioane-două-sute-douăzeci")>]
[<InlineData(   9099000, "nouă-milioane-nouăzeci-și-nouă-de-mii")>]
[<InlineData(  10000000, "zece-milioane")>]
[<InlineData(  24000000, "douăzeci-și-patru-de-milioane")>]
[<InlineData(  39020011, "treizeci-și-nouă-de-milioane-douăzeci-de-mii-unsprezece")>]
[<InlineData(  40606100, "patruzeci-de-milioane-șase-sute-șase-mii-o-sută")>]
[<InlineData(  53000000, "cincizeci-și-trei-de-milioane")>]
[<InlineData(  64000098, "șaizeci-și-patru-de-milioane-nouăzeci-și-opt")>]
[<InlineData(  70003190, "șaptezeci-de-milioane-trei-mii-o-sută-nouăzeci")>]
[<InlineData(  80000000, "optzeci-de-milioane")>]
[<InlineData(  99000099, "nouăzeci-și-nouă-de-milioane-nouăzeci-și-nouă")>]
[<InlineData( 100000000, "o-sută-de-milioane")>]
[<InlineData( 209000000, "două-sute-nouă-milioane")>]
[<InlineData( 398000000, "trei-sute-nouăzeci-și-opt-de-milioane")>]
[<InlineData( 439011000, "patru-sute-treizeci-și-nouă-de-milioane-unsprezece-mii")>]
[<InlineData( 560400000, "cinci-sute-șaizeci-de-milioane-patru-sute-de-mii")>]
[<InlineData( 600010900, "șase-sute-de-milioane-zece-mii-nouă-sute")>]
[<InlineData( 700000000, "șapte-sute-de-milioane")>]
[<InlineData( 800116000, "opt-sute-de-milioane-o-sută-șaisprezece-mii")>]
[<InlineData( 900800007, "nouă-sute-de-milioane-opt-sute-de-mii-șapte")>]
[<InlineData(1000000000, "un-miliard")>]
[<InlineData(2121000000, "două-miliarde-o-sută-douăzeci-și-unu-de-milioane")>]
[<InlineData(
    System.Int32.MaxValue,
    "două-miliarde-o-sută-patruzeci-și-șapte-de-milioane-patru-sute-optzeci-și-trei-de-mii-șase-sute-patruzeci-și-șapte")>]
let ``toRomanian returns correct result`` (i, expected) =
    let actual = Numeral.toRomanian i
    expected =! actual
