module Ploeh.Numsense.SlovakExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                             "nula",          0)>]
[<InlineData(                                            " nula",          0)>]
[<InlineData(                                            "nula ",          0)>]
[<InlineData(                                         "  nula  ",          0)>]
[<InlineData(                                             "Nula",          0)>]
[<InlineData(                                             "NULA",          0)>]
[<InlineData(                                          " nULa\t",          0)>]
[<InlineData(                                            "jeden",          1)>]
[<InlineData(                                            "JEDEN",          1)>]
[<InlineData(                                            "JEDna",          1)>]
[<InlineData(                                            "JEDno",          1)>]
[<InlineData(                                              "dva",          2)>]
[<InlineData(                                             " dve",          2)>]
[<InlineData(                                           " dvaja",          2)>]
[<InlineData(                                            "traja",          3)>]
[<InlineData(                                             "tri ",          3)>]
[<InlineData(                                            "štyri",          4)>]
[<InlineData(                                           "štyria",          4)>]
[<InlineData(                                          "  päť  ",          5)>]
[<InlineData(                                              "PÄŤ",          5)>]
[<InlineData(                                             "ŠESť",          6)>]
[<InlineData(                                          "  šesť ",          6)>]
[<InlineData(                                            "sedem",          7)>]
[<InlineData(                                        "    seDeM",          7)>]
[<InlineData(                                             "osem",          8)>]
[<InlineData(                                             "OSEM",          8)>]
[<InlineData(                                            "deväť",          9)>]
[<InlineData(                                           "DeväŤ ",          9)>]
[<InlineData(                                            "desať",         10)>]
[<InlineData(                                         "jedenásť",         11)>]
[<InlineData(                                          "dvanásť",         12)>]
[<InlineData(                                          "trinásť",         13)>]
[<InlineData(                                          "štrnÁSŤ",         14)>]
[<InlineData(                                          "pätnásŤ",         15)>]
[<InlineData(                                         "šestnásť",         16)>]
[<InlineData(                                        "sedemnásť",         17)>]
[<InlineData(                                         "osemnásť",         18)>]
[<InlineData(                                        "devätnásť",         19)>]
[<InlineData(                                          "dvadsať",         20)>]
[<InlineData(                                    "dvadsať jeden",         21)>]
[<InlineData(                                     "dvadsaťjeden",         21)>]
[<InlineData(                                          "tridsať",         30)>]
[<InlineData(                                     "tridsaťštyri",         34)>]
[<InlineData(                                     "tridsať osem",         38)>]
[<InlineData(                                        "štyridsať",         40)>]
[<InlineData(                                   "štyridsaťjeden",         41)>]
[<InlineData(                                   "ŠTyriDSAŤŠtyri",         44)>]
[<InlineData(                                        "päťdesiat",         50)>]
[<InlineData(                                   "päťdesiatsedem",         57)>]
[<InlineData(                                       "šesťdesiat",         60)>]
[<InlineData(                                    "šesťdesiatpäŤ",         65)>]
[<InlineData(                                      "sedemdesiat",         70)>]
[<InlineData(                                "sedemdesiaT SEDEM",         77)>]
[<InlineData(                                 "sedemdesiatDEVäŤ",         79)>]
[<InlineData(                                       "osemdesiat",         80)>]
[<InlineData(                                   "osemdesiatŠEsť",         86)>]
[<InlineData(                                      "deväŤdesiat",         90)>]
[<InlineData(                                  "deväťdesiat tri",         93)>]
[<InlineData(                                          "  sto  ",        100)>]
[<InlineData(                                       "stojeden  ",        101)>]
[<InlineData(                                       "sto jeden ",        101)>]
[<InlineData(                                           "dvesto",        200)>]
[<InlineData(                               "dvestotridsaťsedem",        237)>]
[<InlineData(                          "triSTO sedemdesiat päť",         375)>]
[<InlineData(                              "štyristodeväťdesiat",        490)>]
[<InlineData(                            "päťsto šesťdesiattri ",        563)>]
[<InlineData(                               "šesťstoosemnásť   ",        618)>]
[<InlineData(                         "sedemstosedemdesiatsedem",        777)>]
[<InlineData(                                     "osemsto päť",         805)>]
[<InlineData(                                      "osemstošesť",        806)>]
[<InlineData(                                   "osemsto sedem",         807)>]
[<InlineData(                           "deväťstopäťdesiatdeväť",        959)>]
[<InlineData(                                            "TIsÍC",       1000)>]
[<InlineData(                                       "tisícjeden",       1001)>]
[<InlineData(                                      "tisíc jeden",       1001)>]
[<InlineData(                                        "tisíc dva",       1002)>]
[<InlineData(                                     "tisíc stodva",       1102)>]
[<InlineData(                            "tisíc šesťdesiatštyri",       1064)>]
[<InlineData(                                         "dvetisíc",       2000)>]
[<InlineData(                    "osemtisícsedemstodvadsaťjeden",       8721)>]
[<InlineData(                        "deväťtisíc sto dvadsaťtri",       9123)>]
[<InlineData(                                       "desaťtisíc",      10000)>]
[<InlineData(                               "desaťtisícstojeden",      10101)>]
[<InlineData(                                 "desaťtisícstodva",      10102)>]
[<InlineData(           "dvadsaťtritisíc päťsto šesťdesiatštyri",      23564)>]
[<InlineData(                            "osemdesiattisíc desať",      80010)>]
[<InlineData(                                         "stotisíc",     100000)>]
[<InlineData(                                   "stotisíc jeden",     100001)>]
[<InlineData(        "tristodevätnásťtisíctristoštyridsať deväť",     319349)>]
[<InlineData(                                           "milión",    1000000)>]
[<InlineData(                                    "milión jeden ",    1000001)>]
[<InlineData(                               "jeden milión jeden",    1000001)>]
[<InlineData(                              "milión tisíc dvesto",    1001200)>]
[<InlineData(                                "dva milióny desať",    2000010)>]
[<InlineData(                       "šesť miliónov tridsaŤTisíc",    6030000)>]
[<InlineData(
    "deväť miliónov dvestojeden tisícšesťstoosemdesiat",
    9201680)>]
[<InlineData(                                   "desať miliónov",   10000000)>]
[<InlineData(                             "desať miliónov deväť",   10000009)>]
[<InlineData(                            "dvadsaťjeden miliónov",   21000000)>]
[<InlineData(
    "štyridsaťsedemmiliónovšesťstošesťdesiatjedentisícšesťdesiat",
    47661060)>]
[<InlineData(                                     "sto miliónov",  100000000)>]
[<InlineData(                               "dvestopäť miliónov",  205000000)>]
[<InlineData(                            "tristo sedem miliónov",  307000000)>]
[<InlineData(
    "štyristošesťdesiatjeden miliónov šesťdesiattisícšesťsto",
    461060600)>]
[<InlineData(                                         "miliaRDA", 1000000000)>]
[<InlineData(                                   "jedna miliarda", 1000000000)>]
[<InlineData(                                     "dve miliardy", 2000000000)>]
[<InlineData(                    "dve miliardy milión tisíc sto", 2001001100)>]
[<InlineData(              "dve miliardy jeden milión tisíc sto", 2001001100)>]
[<InlineData(
    "dve miliardy štyridsaťdeväť miliónov šesťstopäťdesiattisíc",
    2049650000)>]
[<InlineData(
    "dve miliardy stoštyridsaťsedem miliónov štyristoosemdesiattritisícšesťstoštyridsaťsedem",
    System.Int32.MaxValue)>]
let ``tryParseSlovak returns correct result`` (slovak, expected) =
    let actual = Numeral.tryParseSlovak slovak
    Some expected =! actual

[<Theory>]
[<InlineData(         0, "nula")>]
[<InlineData(         1, "jeden")>]
[<InlineData(         2, "dva")>]
[<InlineData(         3, "tri")>]
[<InlineData(         4, "štyri")>]
[<InlineData(         5, "päť")>]
[<InlineData(         6, "šesť")>]
[<InlineData(         7, "sedem")>]
[<InlineData(         8, "osem")>]
[<InlineData(         9, "deväť")>]
[<InlineData(        10, "desať")>]
[<InlineData(        11, "jedenásť")>]
[<InlineData(        12, "dvanásť")>]
[<InlineData(        13, "trinásť")>]
[<InlineData(        14, "štrnásť")>]
[<InlineData(        15, "pätnásť")>]
[<InlineData(        16, "šestnásť")>]
[<InlineData(        17, "sedemnásť")>]
[<InlineData(        18, "osemnásť")>]
[<InlineData(        19, "devätnásť")>]
[<InlineData(        20, "dvadsať")>]
[<InlineData(        21, "dvadsať jeden")>]
[<InlineData(        30, "tridsať")>]
[<InlineData(        31, "tridsať jeden")>]
[<InlineData(        32, "tridsať dva")>]
[<InlineData(        33, "tridsať tri")>]
[<InlineData(        34, "tridsať štyri")>]
[<InlineData(        40, "štyridsať")>]
[<InlineData(        42, "štyridsať dva")>]
[<InlineData(        50, "päťdesiat")>]
[<InlineData(        58, "päťdesiat osem")>]
[<InlineData(        60, "šesťdesiat")>]
[<InlineData(        65, "šesťdesiat päť")>]
[<InlineData(        70, "sedemdesiat")>]
[<InlineData(        79, "sedemdesiat deväť")>]
[<InlineData(        80, "osemdesiat")>]
[<InlineData(        86, "osemdesiat šesť")>]
[<InlineData(        90, "deväťdesiat")>]
[<InlineData(        93, "deväťdesiat tri")>]
[<InlineData(       100, "sto")>]
[<InlineData(       101, "sto jeden")>]
[<InlineData(       110, "sto desať")>]
[<InlineData(       114, "sto štrnásť")>]
[<InlineData(       135, "sto tridsať päť")>]
[<InlineData(       182, "sto osemdesiat dva")>]
[<InlineData(       218, "dve sto osemnásť")>]
[<InlineData(       282, "dve sto osemdesiat dva")>]
[<InlineData(       331, "tri sto tridsať jeden")>]
[<InlineData(       407, "štyri sto sedem")>]
[<InlineData(       520, "päť sto dvadsať")>]
[<InlineData(       666, "šesť sto šesťdesiat šesť")>]
[<InlineData(       798, "sedem sto deväťdesiat osem")>]
[<InlineData(       857, "osem sto päťdesiat sedem")>]
[<InlineData(       999, "deväť sto deväťdesiat deväť")>]
[<InlineData(      1000, "tisíc")>]
[<InlineData(      1001, "tisíc jeden")>]
[<InlineData(      1110, "tisíc sto desať")>]
[<InlineData(      1066, "tisíc šesťdesiat šesť")>]
[<InlineData(      1337, "tisíc tri sto tridsať sedem")>]
[<InlineData(      1984, "tisíc deväť sto osemdesiat štyri")>]
[<InlineData(      2015, "dve tisíc pätnásť")>]
[<InlineData(      3000, "tri tisíc")>]
[<InlineData(      3297, "tri tisíc dve sto deväťdesiat sedem")>]
[<InlineData(      4080, "štyri tisíc osemdesiat")>]
[<InlineData(      5011, "päť tisíc jedenásť")>]
[<InlineData(      6025, "šesť tisíc dvadsať päť")>]
[<InlineData(      7441, "sedem tisíc štyri sto štyridsať jeden")>]
[<InlineData(      8513, "osem tisíc päť sto trinásť")>]
[<InlineData(      9000, "deväť tisíc")>]
[<InlineData(     10000, "desať tisíc")>]
[<InlineData(     12001, "dvanásť tisíc jeden")>]
[<InlineData(     23456, "dvadsať tri tisíc štyri sto päťdesiat šesť")>]
[<InlineData(     32109, "tridsať dva tisíc sto deväť")>]
[<InlineData(     40404, "štyridsať tisíc štyri sto štyri")>]
[<InlineData(     56789, "päťdesiat šesť tisíc sedem sto osemdesiat deväť")>]
[<InlineData(     60015, "šesťdesiat tisíc pätnásť")>]
[<InlineData(     71003, "sedemdesiat jeden tisíc tri")>]
[<InlineData(     80522, "osemdesiat tisíc päť sto dvadsať dva")>]
[<InlineData(     98765, "deväťdesiat osem tisíc sedem sto šesťdesiat päť")>]
[<InlineData(    100000, "sto tisíc")>]
[<InlineData(    100001, "sto tisíc jeden")>]
[<InlineData(    100010, "sto tisíc desať")>]
[<InlineData(    101001, "sto jeden tisíc jeden")>]
[<InlineData(    200000, "dve sto tisíc")>]
[<InlineData(    302000, "tri sto dva tisíc")>]
[<InlineData(    321000, "tri sto dvadsať jeden tisíc")>]
[<InlineData(    411416, "štyri sto jedenásť tisíc štyri sto šestnásť")>]
[<InlineData(    530121, "päť sto tridsať tisíc sto dvadsať jeden")>]
[<InlineData(    600000, "šesť sto tisíc")>]
[<InlineData(    788000, "sedem sto osemdesiat osem tisíc")>]
[<InlineData(    876540, "osem sto sedemdesiat šesť tisíc päť sto štyridsať")>]
[<InlineData(    908077, "deväť sto osem tisíc sedemdesiat sedem")>]
[<InlineData(   1000000, "milión")>]
[<InlineData(   2000002, "dva milióny dva")>]
[<InlineData(   3040506, "tri milióny štyridsať tisíc päť sto šesť")>]
[<InlineData(   4321000, "štyri milióny tri sto dvadsať jeden tisíc")>]
[<InlineData(   5004621, "päť miliónov štyri tisíc šesť sto dvadsať jeden")>]
[<InlineData(   6982004, "šesť miliónov deväť sto osemdesiat dva tisíc štyri")>]
[<InlineData(   7000000, "sedem miliónov")>]
[<InlineData(   8000220, "osem miliónov dve sto dvadsať")>]
[<InlineData(   9099000, "deväť miliónov deväťdesiat deväť tisíc")>]
[<InlineData(  10000000, "desať miliónov")>]
[<InlineData(  24000000, "dvadsať štyri miliónov")>]
[<InlineData(  39020011, "tridsať deväť miliónov dvadsať tisíc jedenásť")>]
[<InlineData(  53000000, "päťdesiat tri miliónov")>]
[<InlineData(  64000098, "šesťdesiat štyri miliónov deväťdesiat osem")>]
[<InlineData(  70003190, "sedemdesiat miliónov tri tisíc sto deväťdesiat")>]
[<InlineData(  80000000, "osemdesiat miliónov")>]
[<InlineData(  99000099, "deväťdesiat deväť miliónov deväťdesiat deväť")>]
[<InlineData( 100000000, "sto miliónov")>]
[<InlineData( 209000000, "dve sto deväť miliónov")>]
[<InlineData( 398000000, "tri sto deväťdesiat osem miliónov")>]
[<InlineData( 439011000, "štyri sto tridsať deväť miliónov jedenásť tisíc")>]
[<InlineData( 560400000, "päť sto šesťdesiat miliónov štyri sto tisíc")>]
[<InlineData( 600010900, "šesť sto miliónov desať tisíc deväť sto")>]
[<InlineData( 700000000, "sedem sto miliónov")>]
[<InlineData( 800116000, "osem sto miliónov sto šestnásť tisíc")>]
[<InlineData( 900800007, "deväť sto miliónov osem sto tisíc sedem")>]
[<InlineData(1000000000, "miliarda")>]
[<InlineData(2121000000, "dve miliardy sto dvadsať jeden miliónov")>]
[<InlineData(
    System.Int32.MaxValue,
    "dve miliardy sto štyridsať sedem miliónov štyri sto osemdesiat tri tisíc šesť sto štyridsať sedem")>]
let ``toSlovak returns correct result`` (i, expected) =
    let actual = Numeral.toSlovak i
    expected =! actual