module Ploeh.Numsense.TraditionalFinancialChineseExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                    "零",          0)>]
[<InlineData(                                   " 零",          0)>]
[<InlineData(                                   "零 ",          0)>]
[<InlineData(                                "  零  ",          0)>]
[<InlineData(                                 " 零\t",          0)>]
[<InlineData(                                    "壹",          1)>]
[<InlineData(                                    "貳",          2)>]
[<InlineData(                                   " 兩",          2)>]
[<InlineData(                                    "叄",          3)>]
[<InlineData(                                  "叄  ",          3)>]
[<InlineData(                                    "肆",          4)>]
[<InlineData(                                 "  肆 ",          4)>]
[<InlineData(                                    "伍",          5)>]
[<InlineData(                                    "陸",          6)>]
[<InlineData(                                "  陸  ",          6)>]
[<InlineData(                                    "柒",          7)>]
[<InlineData(                                "    柒",          7)>]
[<InlineData(                                    "捌",          8)>]
[<InlineData(                                    "玖",          9)>]
[<InlineData(                                  "玖  ",          9)>]
[<InlineData(                                    "拾",         10)>]
[<InlineData(                                  "拾壹",         11)>]
[<InlineData(                                  "拾貳",         12)>]
[<InlineData(                                  "拾叄",         13)>]
[<InlineData(                                  "拾肆",         14)>]
[<InlineData(                                  "拾伍",         15)>]
[<InlineData(                                  "拾陸",         16)>]
[<InlineData(                                  "拾柒",         17)>]
[<InlineData(                                  "拾捌",         18)>]
[<InlineData(                                  "拾玖",         19)>]
[<InlineData(                                  "貳拾",         20)>]
[<InlineData(                                "貳拾壹",         21)>]
[<InlineData(                                  "叄拾",         30)>]
[<InlineData(                                "叄拾肆",         34)>]
[<InlineData(                                "叄拾捌",         38)>]
[<InlineData(                                  "肆拾",         40)>]
[<InlineData(                                "肆拾壹",         41)>]
[<InlineData(                                "肆拾肆",         44)>]
[<InlineData(                                  "伍拾",         50)>]
[<InlineData(                                "伍拾柒",         57)>]
[<InlineData(                                  "陸拾",         60)>]
[<InlineData(                                "陸拾伍",         65)>]
[<InlineData(                                  "柒拾",         70)>]
[<InlineData(                                "柒拾柒",         77)>]
[<InlineData(                                "柒拾玖",         79)>]
[<InlineData(                                  "捌拾",         80)>]
[<InlineData(                                "捌拾陸",         86)>]
[<InlineData(                                  "玖拾",         90)>]
[<InlineData(                                "玖拾叄",         93)>]
[<InlineData(                                  "壹佰",        100)>]
[<InlineData(                              "壹佰零壹",        101)>]
[<InlineData(                                  "兩佰",        200)>]
[<InlineData(                            "兩佰叄拾柒",        237)>]
[<InlineData(                            "叄佰柒拾伍",        375)>]
[<InlineData(                              "肆佰玖拾",        490)>]
[<InlineData(                            "伍佰陸拾叄",        563)>]
[<InlineData(                            "陸佰壹拾捌",        618)>]
[<InlineData(                            "柒佰柒拾柒",        777)>]
[<InlineData(                              "捌佰零伍",        805)>]
[<InlineData(                              "捌佰零陸",        806)>]
[<InlineData(                              "捌佰零柒",        807)>]
[<InlineData(                            "玖佰伍拾玖",        959)>]
[<InlineData(                                  "壹仟",       1000)>]
[<InlineData(                              "壹仟零壹",       1001)>]
[<InlineData(                              "壹仟零貳",       1002)>]
[<InlineData(                            "壹仟陸拾肆",       1064)>]
[<InlineData(                                  "兩仟",       2000)>]
[<InlineData(                        "捌仟柒佰貳拾壹",       8721)>]
[<InlineData(                        "玖仟壹佰貳拾叄",       9123)>]
[<InlineData(                                  "壹萬",      10000)>]
[<InlineData(                        "壹萬零壹佰零壹",      10101)>]
[<InlineData(                        "壹萬零壹佰零貳",      10102)>]
[<InlineData(                    "貳萬叄仟伍佰陸拾肆",      23564)>]
[<InlineData(                            "捌萬零壹拾",      80010)>]
[<InlineData(                                "壹拾萬",     100000)>]
[<InlineData(                            "壹拾萬零壹",     100001)>]
[<InlineData(                "叄拾壹萬玖仟叄佰肆拾玖",     319349)>]
[<InlineData(                                "壹佰萬",    1000000)>]
[<InlineData(                            "壹佰萬零壹",    1000001)>]
[<InlineData(                            "兩佰萬零拾",    2000010)>]
[<InlineData(                            "陸佰零叄萬",    6030000)>]
[<InlineData(                "玖佰貳拾萬壹仟陸佰捌拾",    9201680)>]
[<InlineData(                                "壹仟萬",   10000000)>]
[<InlineData(                            "壹仟萬零玖",   10000009)>]
[<InlineData(                            "兩仟壹佰萬",   21000000)>]
[<InlineData(            "肆仟柒佰陸拾陸萬壹仟零陸拾",   47661060)>]
[<InlineData(                                  "壹億",  100000000)>]
[<InlineData(                          "貳億零伍佰萬",  205000000)>]
[<InlineData(                          "叄億零柒佰萬",  307000000)>]
[<InlineData(                "肆億陸仟壹佰零陸萬陸佰",  461060600)>]
[<InlineData(                                "壹拾億", 1000000000)>]
[<InlineData(                                "貳拾億", 2000000000)>]
[<InlineData(                "貳拾億肆仟玖佰陸拾伍萬", 2049650000)>]
[<InlineData("貳拾壹億肆仟柒佰肆拾捌萬叄仟陸佰肆拾柒", System.Int32.MaxValue)>]
let ``tryOfTraditionalFinancialChinese returns correct result`` (chinese, expected) =
    let actual = Numeral.tryParseTraditionalFinancialChinese chinese
    Some expected =! actual

[<Theory>]
[<InlineData(                    0, "零")>]
[<InlineData(                    1, "壹")>]
[<InlineData(                    2, "兩")>]
[<InlineData(                    3, "叄")>]
[<InlineData(                    4, "肆")>]
[<InlineData(                    5, "伍")>]
[<InlineData(                    6, "陸")>]
[<InlineData(                    7, "柒")>]
[<InlineData(                    8, "捌")>]
[<InlineData(                    9, "玖")>]
[<InlineData(                   10, "拾")>]
[<InlineData(                   11, "拾壹")>]
[<InlineData(                   12, "拾貳")>]
[<InlineData(                   13, "拾叄")>]
[<InlineData(                   14, "拾肆")>]
[<InlineData(                   15, "拾伍")>]
[<InlineData(                   16, "拾陸")>]
[<InlineData(                   17, "拾柒")>]
[<InlineData(                   18, "拾捌")>]
[<InlineData(                   19, "拾玖")>]
[<InlineData(                   20, "貳拾")>]
[<InlineData(                   21, "貳拾壹")>]
[<InlineData(                   30, "叄拾")>]
[<InlineData(                   34, "叄拾肆")>]
[<InlineData(                   40, "肆拾")>]
[<InlineData(                   42, "肆拾貳")>]
[<InlineData(                   50, "伍拾")>]
[<InlineData(                   58, "伍拾捌")>]
[<InlineData(                   60, "陸拾")>]
[<InlineData(                   65, "陸拾伍")>]
[<InlineData(                   70, "柒拾")>]
[<InlineData(                   79, "柒拾玖")>]
[<InlineData(                   80, "捌拾")>]
[<InlineData(                   86, "捌拾陸")>]
[<InlineData(                   90, "玖拾")>]
[<InlineData(                   93, "玖拾叄")>]
[<InlineData(                  100, "壹佰")>]
[<InlineData(                  101, "壹佰零壹")>]
[<InlineData(                  110, "壹佰壹拾")>]
[<InlineData(                  114, "壹佰壹拾肆")>]
[<InlineData(                  135, "壹佰叄拾伍")>]
[<InlineData(                  200, "兩佰")>]
[<InlineData(                  282, "兩佰捌拾貳")>]
[<InlineData(                  331, "叄佰叄拾壹")>]
[<InlineData(                  407, "肆佰零柒")>]
[<InlineData(                  520, "伍佰貳拾")>]
[<InlineData(                  666, "陸佰陸拾陸")>]
[<InlineData(                  798, "柒佰玖拾捌")>]
[<InlineData(                  857, "捌佰伍拾柒")>]
[<InlineData(                  999, "玖佰玖拾玖")>]
[<InlineData(                 1000, "壹仟")>]
[<InlineData(                 1001, "壹仟零壹")>]
[<InlineData(                 1010, "壹仟零壹拾")>]
[<InlineData(                 1066, "壹仟零陸拾陸")>]
[<InlineData(                 1337, "壹仟叄佰叄拾柒")>]
[<InlineData(                 1984, "壹仟玖佰捌拾肆")>]
[<InlineData(                 2015, "兩仟零壹拾伍")>]
[<InlineData(                 3000, "叄仟")>]
[<InlineData(                 3297, "叄仟兩佰玖拾柒")>]
[<InlineData(                 4080, "肆仟零捌拾")>]
[<InlineData(                 5011, "伍仟零壹拾壹")>]
[<InlineData(                 6025, "陸仟零貳拾伍")>]
[<InlineData(                 7441, "柒仟肆佰肆拾壹")>]
[<InlineData(                 8513, "捌仟伍佰壹拾叄")>]
[<InlineData(                 9000, "玖仟")>]
[<InlineData(                10000, "壹萬")>]
[<InlineData(                12001, "壹萬兩仟零壹")>]
[<InlineData(                23456, "貳萬叄仟肆佰伍拾陸")>]
[<InlineData(                32109, "叄萬兩仟壹佰零玖")>]
[<InlineData(                40404, "肆萬零肆佰零肆")>]
[<InlineData(                56789, "伍萬陸仟柒佰捌拾玖")>]
[<InlineData(                60015, "陸萬零壹拾伍")>]
[<InlineData(                71003, "柒萬壹仟零叄")>]
[<InlineData(                80522, "捌萬零伍佰貳拾貳")>]
[<InlineData(                98765, "玖萬捌仟柒佰陸拾伍")>]
[<InlineData(               100000, "壹拾萬")>]
[<InlineData(               100001, "壹拾萬零壹")>]
[<InlineData(               100010, "壹拾萬零壹拾")>]
[<InlineData(               101010, "壹拾萬壹仟零壹拾")>]
[<InlineData(               200000, "貳拾萬")>]
[<InlineData(               321000, "叄拾貳萬壹仟")>]
[<InlineData(               411416, "肆拾壹萬壹仟肆佰壹拾陸")>]
[<InlineData(               530121, "伍拾叄萬零壹佰貳拾壹")>]
[<InlineData(               600000, "陸拾萬")>]
[<InlineData(               788000, "柒拾捌萬捌仟")>]
[<InlineData(               876540, "捌拾柒萬陸仟伍佰肆拾")>]
[<InlineData(               908077, "玖拾萬捌仟零柒拾柒")>]
[<InlineData(              1000000, "壹佰萬")>]
[<InlineData(              2000002, "兩佰萬零貳")>]
[<InlineData(              3040506, "叄佰零肆萬零伍佰零陸")>]
[<InlineData(              4321000, "肆佰叄拾貳萬壹仟")>]
[<InlineData(              5004621, "伍佰萬肆仟陸佰貳拾壹")>]
[<InlineData(              6982001, "陸佰玖拾捌萬兩仟零壹")>]
[<InlineData(              7000000, "柒佰萬")>]
[<InlineData(              8000220, "捌佰萬零兩佰貳拾")>]
[<InlineData(              9099000, "玖佰零玖萬玖仟")>]
[<InlineData(             10000000, "壹仟萬")>]
[<InlineData(             24000000, "兩仟肆佰萬")>]
[<InlineData(             39020011, "叄仟玖佰零貳萬零壹拾壹")>]
[<InlineData(             40606100, "肆仟零陸拾萬陸仟壹佰")>]
[<InlineData(             53000000, "伍仟叄佰萬")>]
[<InlineData(             64000098, "陸仟肆佰萬零玖拾捌")>]
[<InlineData(             70003190, "柒仟萬叄仟壹佰玖拾")>]
[<InlineData(             80000000, "捌仟萬")>]
[<InlineData(             99000099, "玖仟玖佰萬零玖拾玖")>]
[<InlineData(            100000000, "壹億")>]
[<InlineData(            209000000, "貳億零玖佰萬")>]
[<InlineData(            398000000, "叄億玖仟捌佰萬")>]
[<InlineData(            439011000, "肆億叄仟玖佰零壹萬壹仟")>]
[<InlineData(            560400000, "伍億陸仟零肆拾萬")>]
[<InlineData(            600010900, "陸億零壹萬零玖佰")>]
[<InlineData(            700000000, "柒億")>]
[<InlineData(            800116000, "捌億零壹拾壹萬陸仟")>]
[<InlineData(            900800007, "玖億零捌拾萬零柒")>]
[<InlineData(           1000000000, "壹拾億")>]
[<InlineData(           2121000000, "貳拾壹億兩仟壹佰萬")>]
[<InlineData(System.Int32.MaxValue, "貳拾壹億肆仟柒佰肆拾捌萬叄仟陸佰肆拾柒")>]
let ``toTraditionalFinancialChinese returns correct result`` (i, expected) =
    let actual = Numeral.toTraditionalFinancialChinese i
    expected =! actual