module Ploeh.Numsense.TraditionalChineseExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                    "零",          0)>]
[<InlineData(                                   " 零",          0)>]
[<InlineData(                                   "零 ",          0)>]
[<InlineData(                                "  零  ",          0)>]
[<InlineData(                                 " 零\t",          0)>]
[<InlineData(                                    "一",          1)>]
[<InlineData(                                    "二",          2)>]
[<InlineData(                                   " 兩",          2)>]
[<InlineData(                                    "三",          3)>]
[<InlineData(                                  "三  ",          3)>]
[<InlineData(                                    "四",          4)>]
[<InlineData(                                 "  四 ",          4)>]
[<InlineData(                                    "五",          5)>]
[<InlineData(                                    "六",          6)>]
[<InlineData(                                "  六  ",          6)>]
[<InlineData(                                    "七",          7)>]
[<InlineData(                                "    七",          7)>]
[<InlineData(                                    "八",          8)>]
[<InlineData(                                    "九",          9)>]
[<InlineData(                                  "九  ",          9)>]
[<InlineData(                                    "十",         10)>]
[<InlineData(                                  "十一",         11)>]
[<InlineData(                                  "十二",         12)>]
[<InlineData(                                  "十三",         13)>]
[<InlineData(                                  "十四",         14)>]
[<InlineData(                                  "十五",         15)>]
[<InlineData(                                  "十六",         16)>]
[<InlineData(                                  "十七",         17)>]
[<InlineData(                                  "十八",         18)>]
[<InlineData(                                  "十九",         19)>]
[<InlineData(                                  "二十",         20)>]
[<InlineData(                                "二十一",         21)>]
[<InlineData(                                  "三十",         30)>]
[<InlineData(                                "三十四",         34)>]
[<InlineData(                                "三十八",         38)>]
[<InlineData(                                  "四十",         40)>]
[<InlineData(                                "四十一",         41)>]
[<InlineData(                                "四十四",         44)>]
[<InlineData(                                  "五十",         50)>]
[<InlineData(                                "五十七",         57)>]
[<InlineData(                                  "六十",         60)>]
[<InlineData(                                "六十五",         65)>]
[<InlineData(                                  "七十",         70)>]
[<InlineData(                                "七十七",         77)>]
[<InlineData(                                "七十九",         79)>]
[<InlineData(                                  "八十",         80)>]
[<InlineData(                                "八十六",         86)>]
[<InlineData(                                  "九十",         90)>]
[<InlineData(                                "九十三",         93)>]
[<InlineData(                                  "一百",        100)>]
[<InlineData(                              "一百零一",        101)>]
[<InlineData(                                  "兩百",        200)>]
[<InlineData(                            "兩百三十七",        237)>]
[<InlineData(                            "三百七十五",        375)>]
[<InlineData(                              "四百九十",        490)>]
[<InlineData(                            "五百六十三",        563)>]
[<InlineData(                            "六百一十八",        618)>]
[<InlineData(                            "七百七十七",        777)>]
[<InlineData(                              "八百零五",        805)>]
[<InlineData(                              "八百零六",        806)>]
[<InlineData(                              "八百零七",        807)>]
[<InlineData(                            "九百五十九",        959)>]
[<InlineData(                                  "一千",       1000)>]
[<InlineData(                              "一千零一",       1001)>]
[<InlineData(                              "一千零二",       1002)>]
[<InlineData(                            "一千六十四",       1064)>]
[<InlineData(                                  "兩千",       2000)>]
[<InlineData(                        "八千七百二十一",       8721)>]
[<InlineData(                        "九千一百二十三",       9123)>]
[<InlineData(                                  "一萬",      10000)>]
[<InlineData(                        "一萬零一百零一",      10101)>]
[<InlineData(                        "一萬零一百零二",      10102)>]
[<InlineData(                    "二萬三千五百六十四",      23564)>]
[<InlineData(                            "八萬零一十",      80010)>]
[<InlineData(                                "一十萬",     100000)>]
[<InlineData(                            "一十萬零一",     100001)>]
[<InlineData(                "三十一萬九千三百四十九",     319349)>]
[<InlineData(                                "一百萬",    1000000)>]
[<InlineData(                            "一百萬零一",    1000001)>]
[<InlineData(                            "兩百萬零十",    2000010)>]
[<InlineData(                            "六百零三萬",    6030000)>]
[<InlineData(                "九百二十萬一千六百八十",    9201680)>]
[<InlineData(                                "一千萬",   10000000)>]
[<InlineData(                            "一千萬零九",   10000009)>]
[<InlineData(                            "兩千一百萬",   21000000)>]
[<InlineData(            "四千七百六十六萬一千零六十",   47661060)>]
[<InlineData(                                  "一億",  100000000)>]
[<InlineData(                          "二億零五百萬",  205000000)>]
[<InlineData(                          "三億零七百萬",  307000000)>]
[<InlineData(                "四億六千一百零六萬六百",  461060600)>]
[<InlineData(                                "一十億", 1000000000)>]
[<InlineData(                                "二十億", 2000000000)>]
[<InlineData(                "二十億四千九百六十五萬", 2049650000)>]
[<InlineData("二十一億四千七百四十八萬三千六百四十七", System.Int32.MaxValue)>]
let ``tryOfTraditionalChinese returns correct result`` (chinese, expected) =
    let actual = Numeral.tryParseTraditionalChinese chinese
    Some expected =! actual

[<Theory>]
[<InlineData(                    0, "零")>]
[<InlineData(                    1, "一")>]
[<InlineData(                    2, "兩")>]
[<InlineData(                    3, "三")>]
[<InlineData(                    4, "四")>]
[<InlineData(                    5, "五")>]
[<InlineData(                    6, "六")>]
[<InlineData(                    7, "七")>]
[<InlineData(                    8, "八")>]
[<InlineData(                    9, "九")>]
[<InlineData(                   10, "十")>]
[<InlineData(                   11, "十一")>]
[<InlineData(                   12, "十二")>]
[<InlineData(                   13, "十三")>]
[<InlineData(                   14, "十四")>]
[<InlineData(                   15, "十五")>]
[<InlineData(                   16, "十六")>]
[<InlineData(                   17, "十七")>]
[<InlineData(                   18, "十八")>]
[<InlineData(                   19, "十九")>]
[<InlineData(                   20, "二十")>]
[<InlineData(                   21, "二十一")>]
[<InlineData(                   30, "三十")>]
[<InlineData(                   34, "三十四")>]
[<InlineData(                   40, "四十")>]
[<InlineData(                   42, "四十二")>]
[<InlineData(                   50, "五十")>]
[<InlineData(                   58, "五十八")>]
[<InlineData(                   60, "六十")>]
[<InlineData(                   65, "六十五")>]
[<InlineData(                   70, "七十")>]
[<InlineData(                   79, "七十九")>]
[<InlineData(                   80, "八十")>]
[<InlineData(                   86, "八十六")>]
[<InlineData(                   90, "九十")>]
[<InlineData(                   93, "九十三")>]
[<InlineData(                  100, "一百")>]
[<InlineData(                  101, "一百零一")>]
[<InlineData(                  110, "一百一十")>]
[<InlineData(                  114, "一百一十四")>]
[<InlineData(                  135, "一百三十五")>]
[<InlineData(                  200, "兩百")>]
[<InlineData(                  282, "兩百八十二")>]
[<InlineData(                  331, "三百三十一")>]
[<InlineData(                  407, "四百零七")>]
[<InlineData(                  520, "五百二十")>]
[<InlineData(                  666, "六百六十六")>]
[<InlineData(                  798, "七百九十八")>]
[<InlineData(                  857, "八百五十七")>]
[<InlineData(                  999, "九百九十九")>]
[<InlineData(                 1000, "一千")>]
[<InlineData(                 1001, "一千零一")>]
[<InlineData(                 1010, "一千零一十")>]
[<InlineData(                 1066, "一千零六十六")>]
[<InlineData(                 1337, "一千三百三十七")>]
[<InlineData(                 1984, "一千九百八十四")>]
[<InlineData(                 2015, "兩千零一十五")>]
[<InlineData(                 3000, "三千")>]
[<InlineData(                 3297, "三千兩百九十七")>]
[<InlineData(                 4080, "四千零八十")>]
[<InlineData(                 5011, "五千零一十一")>]
[<InlineData(                 6025, "六千零二十五")>]
[<InlineData(                 7441, "七千四百四十一")>]
[<InlineData(                 8513, "八千五百一十三")>]
[<InlineData(                 9000, "九千")>]
[<InlineData(                10000, "一萬")>]
[<InlineData(                12001, "一萬兩千零一")>]
[<InlineData(                23456, "二萬三千四百五十六")>]
[<InlineData(                32109, "三萬兩千一百零九")>]
[<InlineData(                40404, "四萬零四百零四")>]
[<InlineData(                56789, "五萬六千七百八十九")>]
[<InlineData(                60015, "六萬零一十五")>]
[<InlineData(                71003, "七萬一千零三")>]
[<InlineData(                80522, "八萬零五百二十二")>]
[<InlineData(                98765, "九萬八千七百六十五")>]
[<InlineData(               100000, "一十萬")>]
[<InlineData(               100001, "一十萬零一")>]
[<InlineData(               100010, "一十萬零一十")>]
[<InlineData(               101010, "一十萬一千零一十")>]
[<InlineData(               200000, "二十萬")>]
[<InlineData(               321000, "三十二萬一千")>]
[<InlineData(               411416, "四十一萬一千四百一十六")>]
[<InlineData(               530121, "五十三萬零一百二十一")>]
[<InlineData(               600000, "六十萬")>]
[<InlineData(               788000, "七十八萬八千")>]
[<InlineData(               876540, "八十七萬六千五百四十")>]
[<InlineData(               908077, "九十萬八千零七十七")>]
[<InlineData(              1000000, "一百萬")>]
[<InlineData(              2000002, "兩百萬零二")>]
[<InlineData(              3040506, "三百零四萬零五百零六")>]
[<InlineData(              4321000, "四百三十二萬一千")>]
[<InlineData(              5004621, "五百萬四千六百二十一")>]
[<InlineData(              6982001, "六百九十八萬兩千零一")>]
[<InlineData(              7000000, "七百萬")>]
[<InlineData(              8000220, "八百萬零兩百二十")>]
[<InlineData(              9099000, "九百零九萬九千")>]
[<InlineData(             10000000, "一千萬")>]
[<InlineData(             24000000, "兩千四百萬")>]
[<InlineData(             39020011, "三千九百零二萬零一十一")>]
[<InlineData(             40606100, "四千零六十萬六千一百")>]
[<InlineData(             53000000, "五千三百萬")>]
[<InlineData(             64000098, "六千四百萬零九十八")>]
[<InlineData(             70003190, "七千萬三千一百九十")>]
[<InlineData(             80000000, "八千萬")>]
[<InlineData(             99000099, "九千九百萬零九十九")>]
[<InlineData(            100000000, "一億")>]
[<InlineData(            209000000, "二億零九百萬")>]
[<InlineData(            398000000, "三億九千八百萬")>]
[<InlineData(            439011000, "四億三千九百零一萬一千")>]
[<InlineData(            560400000, "五億六千零四十萬")>]
[<InlineData(            600010900, "六億零一萬零九百")>]
[<InlineData(            700000000, "七億")>]
[<InlineData(            800116000, "八億零一十一萬六千")>]
[<InlineData(            900800007, "九億零八十萬零七")>]
[<InlineData(           1000000000, "一十億")>]
[<InlineData(           2121000000, "二十一億兩千一百萬")>]
[<InlineData(System.Int32.MaxValue, "二十一億四千七百四十八萬三千六百四十七")>]
let ``toTraditionalChinese returns correct result`` (i, expected) =
    let actual = Numeral.toTraditionalChinese i
    expected =! actual