module Ploeh.Numsense.WelshExamples

open Xunit
open Swensen.Unquote

[<Theory>]
[<InlineData(                                              "dim",          0)>]
[<InlineData(                                             " dim",          0)>]
[<InlineData(                                             "dim ",          0)>]
[<InlineData(                                          "  dim  ",          0)>]
[<InlineData(                                              "Dim",          0)>]
[<InlineData(                                              "DIM",          0)>]
[<InlineData(                                           " dIm\t",          0)>]
[<InlineData(                                               "un",          1)>]
[<InlineData(                                               "UN",          1)>]
[<InlineData(                                              "dau",          2)>]
[<InlineData(                                             " dau",          2)>]
[<InlineData(                                              "dwy",          2)>]
[<InlineData(                                             " dwy",          2)>]
[<InlineData(                                              "tri",          3)>]
[<InlineData(                                            "tri  ",          3)>]
[<InlineData(                                             "tair",          3)>]
[<InlineData(                                           "tair  ",          3)>]
[<InlineData(                                           "pedwar",          4)>]
[<InlineData(                                        "  pedwar ",          4)>]
[<InlineData(                                           "pedair",          4)>]
[<InlineData(                                        "  pedair ",          4)>]
[<InlineData(                                             "pump",          5)>]
[<InlineData(                                             "PumP",          5)>]
[<InlineData(                                              "pum",          5)>]
[<InlineData(                                              "PuM",          5)>]
[<InlineData(                                           "chwech",          6)>]
[<InlineData(                                       "  CHWECH  ",          6)>]
[<InlineData(                                             "chwe",          6)>]
[<InlineData(                                         "  CHWE  ",          6)>]
[<InlineData(                                            "saith",          7)>]
[<InlineData(                                        "    saIth",          7)>]
[<InlineData(                                             "wyth",          8)>]
[<InlineData(                                             "wYTH",          8)>]
[<InlineData(                                              "naw",          9)>]
[<InlineData(                                            "NaW  ",          9)>]
[<InlineData(                                              "deg",         10)>]
[<InlineData(                                        "un-deg-un",         11)>]
[<InlineData(                                       "un-deg-dau",         12)>]
[<InlineData(                                       "un-deg-dwy",         12)>]
[<InlineData(                                       "un-deg-tri",         13)>]
[<InlineData(                                      "un-deg-tair",         13)>]
[<InlineData(                                    "un-deg-pedwar",         14)>]
[<InlineData(                                    "un-deg-pedair",         14)>]
[<InlineData(                                      "un-deg-pump",         15)>]
[<InlineData(                                    "un-deg-chwech",         16)>]
[<InlineData(                                     "un-deg-saith",         17)>]
[<InlineData(                                      "un-deg-wyth",         18)>]
[<InlineData(                                       "un-deg-naw",         19)>]
[<InlineData(                                         "dau-ddeg",         20)>]
[<InlineData(                                       "dau-ddegun",         21)>]
[<InlineData(                                      "dau-ddeg-un",         21)>]
[<InlineData(                                          "tri-deg",         30)>]
[<InlineData(                                     "tridegpedair",         34)>]
[<InlineData(                                     "tri-deg-wyth",         38)>]
[<InlineData(                                       "pedwar-deg",         40)>]
[<InlineData(                                    "pedwar-deg-un",         41)>]
[<InlineData(                                  "pedwardegpedwar",         44)>]
[<InlineData(                                          "pum-deg",         50)>]
[<InlineData(                                      "pumdegsaith",         57)>]
[<InlineData(                                         "chwe-deg",         60)>]
[<InlineData(                                      "chwedegpump",         65)>]
[<InlineData(                                        "saith-deg",         70)>]
[<InlineData(                                  "saith-deg-saith",         77)>]
[<InlineData(                                      "saithdegnaw",         79)>]
[<InlineData(                                         "wyth-deg",         80)>]
[<InlineData(                                    "wythdegchwech",         86)>]
[<InlineData(                                          "naw-deg",         90)>]
[<InlineData(                                       "nawdegtair",         93)>]
[<InlineData(                                             "cant",        100)>]
[<InlineData(                                           "cantun",        101)>]
[<InlineData(                                           "cantun",        101)>]
[<InlineData(                                          "cant-un",        101)>]
[<InlineData(                                          "daugant",        200)>]
[<InlineData(                               "dauganttridegsaith",        237)>]
[<InlineData(                             "trichantsaithdegpump",        375)>]
[<InlineData(                                 "pedwarcantnawdeg",        490)>]
[<InlineData(                                "pumcantchwedegtri",        563)>]
[<InlineData(                                        "chwechant",        600)>]
[<InlineData(                                       "chwe-chant",        600)>]
[<InlineData(                               "chwechantundegwyth",        618)>]
[<InlineData(                               "chwechantundegwyth",        618)>]
[<InlineData(                           "saithcantsaithdegsaith",        777)>]
[<InlineData(                                     "wythcantpump",        805)>]
[<InlineData(                                   "wythcantchwech",        806)>]
[<InlineData(                                  "wyth-cant-saith",        807)>]
[<InlineData(                                 "nawcantpumdegnaw",        959)>]
[<InlineData(                                              "mil",       1000)>]
[<InlineData(                                            "unmil",       1000)>]
[<InlineData(                                          "unmilun",       1001)>]
[<InlineData(                                         "unmildau",       1002)>]
[<InlineData(                               "unmilchwedegpedwar",       1064)>]
[<InlineData(                                           "daumil",       2000)>]
[<InlineData(                        "wythmilsaithcantdauddegun",       8721)>]
[<InlineData(                     "naw-mil-un-cant-dau-ddeg-tri",       9123)>]
[<InlineData(                                          "deg-mil",      10000)>]
[<InlineData(                                   "degmiluncantun",      10101)>]
[<InlineData(                              "deg-mil-un-cant-dau",      10102)>]
[<InlineData(                "dauddegtrimilpumcantchwedegpedwar",      23564)>]
[<InlineData(                                  "wythdegmilundeg",      80010)>]
[<InlineData(                                          "cantmil",     100000)>]
[<InlineData(                                        "uncantmil",     100000)>]
[<InlineData(                                      "uncantmilun",     100001)>]
[<InlineData(          "trichantundegnawmiltrichantpedwardegnaw",     319349)>]
[<InlineData(                                         "unmiliwn",    1000000)>]
[<InlineData(                                       "unmiliwnun",    1000001)>]
[<InlineData(                                   "daumiliwnundeg",    2000010)>]
[<InlineData(                              "chwemiliwntridegmil",    6030000)>]
[<InlineData(             "nawmiliwndaugantunmilchwecantwythdeg",    9201680)>]
[<InlineData(                                        "degmiliwn",   10000000)>]
[<InlineData(                                     "degmiliwnnaw",   10000009)>]
[<InlineData(                                  "dauddegunmiliwn",   21000000)>]
[<InlineData( "pedwardegsaithmiliwnchwechantchwedegunmilchwedeg",   47661060)>]
[<InlineData(                                       "cantmiliwn",  100000000)>]
[<InlineData(                                     "uncantmiliwn",  100000000)>]
[<InlineData(                                "daugantpumpmiliwn",  205000000)>]
[<InlineData(                           "tri-chant-saith-miliwn",  307000000)>]
[<InlineData(     "pedwarcantchwedegunmiliwnchwedegmilchwechant",  461060600)>]
[<InlineData(                                         "unbiliwn", 1000000000)>]
[<InlineData(                                        "daubiliwn", 2000000000)>]
[<InlineData(    "daubiliwnpedwardegnawmiliwnchwechantpumdegmil", 2049650000)>]
[<InlineData(
    "daubiliwncantpedwardegsaithmiliwnpedwarcantwythdegtrimilchwechantpedwardegsaith",
    System.Int32.MaxValue)>]
let ``tryOfWelsh returns correct result`` (welsh, expected) =
    let actual = Numeral.tryParseWelsh welsh
    Some expected =! actual

[<Theory>]
[<InlineData(         0, "dim")>]
[<InlineData(         1, "un")>]
[<InlineData(         2, "dau")>]
[<InlineData(         3, "tri")>]
[<InlineData(         4, "pedwar")>]
[<InlineData(         5, "pump")>]
[<InlineData(         6, "chwech")>]
[<InlineData(         7, "saith")>]
[<InlineData(         8, "wyth")>]
[<InlineData(         9, "naw")>]
[<InlineData(        10, "deg")>]
[<InlineData(        11, "un-deg-un")>]
[<InlineData(        12, "un-deg-dau")>]
[<InlineData(        13, "un-deg-tri")>]
[<InlineData(        14, "un-deg-pedwar")>]
[<InlineData(        15, "un-deg-pump")>]
[<InlineData(        16, "un-deg-chwech")>]
[<InlineData(        17, "un-deg-saith")>]
[<InlineData(        18, "un-deg-wyth")>]
[<InlineData(        19, "un-deg-naw")>]
[<InlineData(        20, "dau-ddeg")>]
[<InlineData(        21, "dau-ddeg-un")>]
[<InlineData(        30, "tri-deg")>]
[<InlineData(        34, "tri-deg-pedwar")>]
[<InlineData(        40, "pedwar-deg")>]
[<InlineData(        42, "pedwar-deg-dau")>]
[<InlineData(        50, "pum-deg")>]
[<InlineData(        58, "pum-deg-wyth")>]
[<InlineData(        60, "chwe-deg")>]
[<InlineData(        65, "chwe-deg-pump")>]
[<InlineData(        70, "saith-deg")>]
[<InlineData(        79, "saith-deg-naw")>]
[<InlineData(        80, "wyth-deg")>]
[<InlineData(        86, "wyth-deg-chwech")>]
[<InlineData(        90, "naw-deg")>]
[<InlineData(        93, "naw-deg-tri")>]
[<InlineData(       100, "cant")>]
[<InlineData(       101, "cant-un")>]
[<InlineData(       110, "cant-deg")>]
[<InlineData(       114, "cant-un-deg-pedwar")>]
[<InlineData(       135, "cant-tri-deg-pump")>]
[<InlineData(       200, "dau-gant")>]
[<InlineData(       282, "dau-gant-wyth-deg-dau")>]
[<InlineData(       331, "tri-chant-tri-deg-un")>]
[<InlineData(       407, "pedwar-cant-saith")>]
[<InlineData(       520, "pum-cant-dau-ddeg")>]
[<InlineData(       666, "chwe-chant-chwe-deg-chwech")>]
[<InlineData(       798, "saith-cant-naw-deg-wyth")>]
[<InlineData(       857, "wyth-cant-pum-deg-saith")>]
[<InlineData(       999, "naw-cant-naw-deg-naw")>]
[<InlineData(      1000, "un-mil")>]
[<InlineData(      1001, "un-mil-un")>]
[<InlineData(      1010, "un-mil-deg")>]
[<InlineData(      1066, "un-mil-chwe-deg-chwech")>]
[<InlineData(      1337, "un-mil-tri-chant-tri-deg-saith")>]
[<InlineData(      1984, "un-mil-naw-cant-wyth-deg-pedwar")>]
[<InlineData(      2015, "dau-mil-un-deg-pump")>]
[<InlineData(      3000, "tri-mil")>]
[<InlineData(      3297, "tri-mil-dau-gant-naw-deg-saith")>]
[<InlineData(      4080, "pedwar-mil-wyth-deg")>]
[<InlineData(      5011, "pump-mil-un-deg-un")>]
[<InlineData(      6025, "chwech-mil-dau-ddeg-pump")>]
[<InlineData(      7441, "saith-mil-pedwar-cant-pedwar-deg-un")>]
[<InlineData(      8513, "wyth-mil-pum-cant-un-deg-tri")>]
[<InlineData(      9000, "naw-mil")>]
[<InlineData(     10000, "deg-mil")>]
[<InlineData(     12001, "un-deg-dau-mil-un")>]
[<InlineData(     23456, "dau-ddeg-tri-mil-pedwar-cant-pum-deg-chwech")>]
[<InlineData(     32109, "tri-deg-dau-mil-cant-naw")>]
[<InlineData(     40404, "pedwar-deg-mil-pedwar-cant-pedwar")>]
[<InlineData(     56789, "pum-deg-chwech-mil-saith-cant-wyth-deg-naw")>]
[<InlineData(     60015, "chwe-deg-mil-un-deg-pump")>]
[<InlineData(     71003, "saith-deg-un-mil-tri")>]
[<InlineData(     80522, "wyth-deg-mil-pum-cant-dau-ddeg-dau")>]
[<InlineData(     98765, "naw-deg-wyth-mil-saith-cant-chwe-deg-pump")>]
[<InlineData(    100000, "cant-mil")>]
[<InlineData(    100001, "cant-mil-un")>]
[<InlineData(    100010, "cant-mil-deg")>]
[<InlineData(    101010, "cant-un-mil-deg")>]
[<InlineData(    200000, "dau-gant-mil")>]
[<InlineData(    321000, "tri-chant-dau-ddeg-un-mil")>]
[<InlineData(    411416, "pedwar-cant-un-deg-un-mil-pedwar-cant-un-deg-chwech")>]
[<InlineData(    530121, "pum-cant-tri-deg-mil-cant-dau-ddeg-un")>]
[<InlineData(    600000, "chwe-chant-mil")>]
[<InlineData(    788000, "saith-cant-wyth-deg-wyth-mil")>]
[<InlineData(    876540, "wyth-cant-saith-deg-chwech-mil-pum-cant-pedwar-deg")>]
[<InlineData(    908077, "naw-cant-wyth-mil-saith-deg-saith")>]
[<InlineData(   1000000, "un-miliwn")>]
[<InlineData(   2000002, "dau-miliwn-dau")>]
[<InlineData(   3040506, "tri-miliwn-pedwar-deg-mil-pum-cant-chwech")>]
[<InlineData(   4321000, "pedwar-miliwn-tri-chant-dau-ddeg-un-mil")>]
[<InlineData(   5004621, "pump-miliwn-pedwar-mil-chwe-chant-dau-ddeg-un")>]
[<InlineData(   6982001, "chwech-miliwn-naw-cant-wyth-deg-dau-mil-un")>]
[<InlineData(   7000000, "saith-miliwn")>]
[<InlineData(   8000220, "wyth-miliwn-dau-gant-dau-ddeg")>]
[<InlineData(   9099000, "naw-miliwn-naw-deg-naw-mil")>]
[<InlineData(  10000000, "deg-miliwn")>]
[<InlineData(  24000000, "dau-ddeg-pedwar-miliwn")>]
[<InlineData(  39020011, "tri-deg-naw-miliwn-dau-ddeg-mil-un-deg-un")>]
[<InlineData(  40606100, "pedwar-deg-miliwn-chwe-chant-chwech-mil-cant")>]
[<InlineData(  53000000, "pum-deg-tri-miliwn")>]
[<InlineData(  64000098, "chwe-deg-pedwar-miliwn-naw-deg-wyth")>]
[<InlineData(  70003190, "saith-deg-miliwn-tri-mil-cant-naw-deg")>]
[<InlineData(  80000000, "wyth-deg-miliwn")>]
[<InlineData(  99000099, "naw-deg-naw-miliwn-naw-deg-naw")>]
[<InlineData( 100000000, "cant-miliwn")>]
[<InlineData( 209000000, "dau-gant-naw-miliwn")>]
[<InlineData( 398000000, "tri-chant-naw-deg-wyth-miliwn")>]
[<InlineData( 439011000, "pedwar-cant-tri-deg-naw-miliwn-un-deg-un-mil")>]
[<InlineData( 560400000, "pum-cant-chwe-deg-miliwn-pedwar-cant-mil")>]
[<InlineData( 600010900, "chwe-chant-miliwn-deg-mil-naw-cant")>]
[<InlineData( 700000000, "saith-cant-miliwn")>]
[<InlineData( 800116000, "wyth-cant-miliwn-cant-un-deg-chwech-mil")>]
[<InlineData( 900800007, "naw-cant-miliwn-wyth-cant-mil-saith")>]
[<InlineData(1000000000, "un-biliwn")>]
[<InlineData(2121000000, "dau-biliwn-cant-dau-ddeg-un-miliwn")>]
[<InlineData(
    System.Int32.MaxValue,
    "dau-biliwn-cant-pedwar-deg-saith-miliwn-pedwar-cant-wyth-deg-tri-mil-chwe-chant-pedwar-deg-saith")>]
let ``toWelsh returns correct result`` (i, expected) =
    let actual = Numeral.toWelsh i
    expected =! actual
